### ISSUE TITLE
[Bug] 打开后点击直播，会卡顿，闪退，无法正常观看直播

### ISSUE THREAD

**Issue by TobyLi223** [Richasy/Bili.Copilot#103]
### Bug 描述

[applog.2023-08-27.log](https://github.com/Richasy/Bili.Copilot/files/12447848/applog.2023-08-27.log)

### 复现问题的步骤

```plain text
如标题
```

### 预期行为

恢复正常

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

在描述栏

### 人人为我，我为人人

我更擅长发现问题

**Comment by Earplug** [comment]
是不是把直播弹幕关了，打开以后再试试，不想看弹幕可以设置弹幕透明度拉满
