### ISSUE TITLE
可以尝试把部分API换回Android

### ISSUE THREAD

**Issue by BlameTwo** [Richasy/Bili.Copilot#105]
### 问题描述

在最新的抓包中我发现多了一行这样的UA:
![image](https://github.com/Richasy/Bili.Copilot/assets/65759143/a3bd73ab-3e8b-4d1a-937b-83370254b488)

值为：Mozilla/5.0 BiliDroid/7.43.0 (bbcallen@gmail.com) os/android model/ALA-AN70 mobi_app/android build/7430300 channel/bili innerVer/7430300 osVer/12 network/2

这个格式和gRpc的UA很相似，基本上一眼能看出各自代表什么。

### 描述解决方案

当然，现在所有的安卓API接口基本上都寄了，除去一些特殊的资源接口还没问题。

### 备选方案

这里必须使用原二维码扫描的结果access_token进行请求，
在我的测试中，使用`https://passport.bilibili.com/login/app/third`返回的数据依然会鉴权失败。

### 附加信息

![image](https://github.com/Richasy/Bili.Copilot/assets/65759143/2dd6a7bd-cf84-4bf2-b2f7-3defc5e8c4cc)
测试首页API通过。

希望被翻到啊🙌

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩中

**Comment by Richasy** [comment]
目前哔哩所使用的 API 都能工作，绝大部分用的 UA 是 ios 的，切换回安卓 API 有什么好处吗？

**Comment by BlameTwo** [comment]
确实对于现阶段的哔哩没什么大的帮助😂，关了
