### ISSUE TITLE
[Feature] 每次点击都打开一个新的播放窗口，这个不符合个人习惯

### ISSUE THREAD

**Issue by watano** [Richasy/Bili.Copilot#106]
### 问题描述

每次点击都打开一个新的播放窗口，导致经常出现多个窗口同时播放，声音也混在一起。

### 描述解决方案

正常人的播放应该都是一个一个地观看吧？能不能增加个选项控制这个行为。
1. 替换当前播放窗口
2. 打开新的播放窗口

### 备选方案

或者增加一个快捷键，比如按住ctrl键点击时打开新的播放窗口，默认替换当前播放窗口

### 附加信息

类似浏览器打开链接的方式

### 人人为我，我为人人

None

**Comment by staoran** [comment]
已经加了播放结束后自动关闭播放器以缓解这个问题
