### ISSUE TITLE
[Bug] 视频播放问题

### ISSUE THREAD

**Issue by Overjoyed5938** [Richasy/Bili.Copilot#115]
### Bug 描述

在播放某些视频时，会出现一直加载视频而无法正常播放的情况

### 复现问题的步骤

```plain text
1.打开应用
2.打开一个视频
3.问题出现
```

### 预期行为

修复此bug

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 10 22H2 (Build 19045)

### 运行设备

桌面/台式机

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
给个视频ID啊

**Comment by Overjoyed5938** [comment]
这是个概率性问题，不是特定的某个视频，有的时候会出现问题，但过一会儿可能就好了（使用b站网页版没出现过这种情况）

**Comment by Richasy** [comment]
无法复现该问题，暂时关闭
