### ISSUE TITLE
[Feature] 建议加入主题色,播放器实例手动选项

### ISSUE THREAD

**Issue by GoodJohnMa** [Richasy/Bili.Copilot#117]
### 问题描述

其实是两个功能需求建议啦
1. 加入主题色选项
2. 点击播放后的UI呈现,建议加入单独播放器实例的手动选项
emmmm..
![屏幕截图 2023-09-03 211848](https://github.com/Richasy/Bili.Copilot/assets/25892473/a4453fc2-9a05-4ce1-b5aa-e421dea79f34)

### 描述解决方案

同上描述.
感谢开发者

### 人人为我，我为人人

None

**Comment by JiZPaper** [comment]
主题色不是跟随系统主题色的吗？
