### ISSUE TITLE
[Bug] 视频播放问题

### ISSUE THREAD

**Issue by Keima-Katsuragi** [Richasy/Bili.Copilot#119]
### Bug 描述

有的视频打开一直转圈没网速，不加载。比如：【【Vmoe字幕组】fripSide LIVE TOUR 2016-2017 FINAL in SSA【特效字幕】】 https://www.bilibili.com/video/BV1Kb411P7su/?share_source=copy_web&vd_source=1424901e9d152e2ad35b6bf1cfa5da24
但在edge网页上能4k播放

### 复现问题的步骤

```plain text
1.打开软件
2.随便搜索一个视频或打开收藏
3.大部分不能看（表现为没网速视频转圈圈）
```

### 预期行为

修复bug

### 应用来源

- [ ] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 其它系统版本

Arm64最新系统

### 运行设备

ARM64 设备

### 日志记录

无

### 备注

从任务管理器看软件是没网速，但edge上有能看
8月25号左右看的时候还是没问题，但今天更新（之后又安装回上版本-原来安装版本）播放就失败了。

### 人人为我，我为人人

None

**Comment by Keima-Katsuragi** [comment]
设置里面都是默认，
少部分能看：如https://www.bilibili.com/video/av233121232/

**Comment by Richasy** [comment]
你是不是开了VPN一类的工具？

**Comment by Keima-Katsuragi** [comment]
我控制变量试试

**Comment by Keima-Katsuragi** [comment]
1.
设置：手动设置代理关闭，猫猫关闭，【Vmoe字幕组】fripSide LIVE TOUR 2016-2017 FINAL in SSA【特效字幕】打开没网速，动态大部分不能看,https://www.bilibili.com/video/BV1YH4y1Q785这个能看。无日志（感觉是因为就是没网速，也不是错误）

edge网页端一切正常

**Comment by Keima-Katsuragi** [comment]
UWP Loopback中应用并未解锁

**Comment by Keima-Katsuragi** [comment]
2.在打开猫猫下，手动设置代理打开，应用回环UWP loopback关闭下，原来能看的（见上回复）依旧能看，不能看的依旧不能

**Comment by Richasy** [comment]
看上去问题解决了，那我先关闭这个issue
