### ISSUE TITLE
[Bug] 哔哩助理页面卡顿

### ISSUE THREAD

**Issue by JiZPaper** [Richasy/Bili.Copilot#123]
### Bug 描述

页面滚动不流畅，动画卡顿

### 复现问题的步骤

```plain text
打开应用立即出现
```

### 预期行为

修复此问题

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

Windows Microsoft Store

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 Insider Preview Build 25941

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
这个……能力有限，暂时无法修复
