### ISSUE TITLE
[Bug] 无法登录

### ISSUE THREAD

**Issue by pigeonssss** [Richasy/Bili.Copilot#124]
### Bug 描述

扫码登录并同意后显示二维码过期

### 复现问题的步骤

```plain text
1.打开应用
2.打开移动端哔哩哔哩
3.扫码登录
```

### 预期行为

它应该登录进界面

### 截图

https://github.com/Richasy/Bili.Copilot/assets/133509962/a009a9a7-8e76-494d-8d92-471db2209dc2

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

MS store

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

版本        Windows 11 专业工作站版 版本        23H2 安装日期      2023/06/27 星期二 操作系统版本    22631.2265 体验        Windows 功能体验包 1000.22674.1000.0

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
本周会发布一个更新，应该可以解决这个问题
