### ISSUE TITLE
[Bug] surface3 使用触控笔点击时闪退

### ISSUE THREAD

**Issue by bailuobuzhibailuo** [Richasy/Bili.Copilot#127]
### Bug 描述

surface3 使用触控笔时闪退

### 复现问题的步骤

```plain text
使用触控笔点击软件任意位置均发生无响应紧接着发生闪退，但是用手指能正常使用不会发生闪退
```

### 预期行为

希望能在使用触控笔的情况下正常使用软件

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

微软商店

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

windows最新的canary版本（build 25947）

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2023-09-13.log](https://github.com/Richasy/Bili.Copilot/files/12596837/applog.2023-09-13.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
你可以试下最新版还会不会有这个问题，这个可能是依赖框架的问题或者是系统原因
