### ISSUE TITLE
[Bug] 打开APP一段时间后或出现信息获取失败错误

### ISSUE THREAD

**Issue by mwnu** [Richasy/Bili.Copilot#129]
### Bug 描述

打开应用，看会儿视频，或者刷新一会儿推荐，然后就无法继续播放或刷新了，显示视频播放信息请求失败和信息获取失败

### 复现问题的步骤

```plain text
1.打开APP
2. 连续播放“未播放列表” 或者刷新“推荐视频”
3. 显示“视频播放信息请求失败和信息获取失败”
```

### 预期行为

持续使用

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/45463732/68a77819-226d-4a02-b757-7518be620335)

### 应用来源

- [X] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

Microsoft Store

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by 1747672002** [comment]
我也遇到了同样的问题，不知道什么原因，期望作者大大能看看

**Comment by renos-oscar** [comment]
我也是一样的问题，看了几个视频，跳了几个直播间就所有信息获取失败
用的是微软商店版本1.2310.3.0
