### ISSUE TITLE
[问题] 大佬，以后不提供Arm版更新了吗？

### ISSUE THREAD

**Issue by Keima-Katsuragi** [Richasy/Bili.Copilot#132]
### 问题描述

如题，如果不提供，怎么自己根据源码编译？在网上找不到教程。

### 描述解决方案

如不提供，希望大佬指个明路（比如给个相关文章或编译的网站教程）

### 人人为我，我为人人

None

**Comment by ziBoTop** [comment]
同反馈 arm版本挺好的

**Comment by Richasy** [comment]
会提供
