### ISSUE TITLE
[Bug] 点击开始下载后，只闪过命令行窗口而不下载

### ISSUE THREAD

**Issue by KarasjokMing** [Richasy/Bili.Copilot#134]
### Bug 描述

如上，而且输出的配置文件也是空文件。已安装BBDown

### 复现问题的步骤

```plain text
打开应用
选定视频
点击 开始下载
出现命令行窗口后马上关闭
```

### 预期行为

命令行窗口应不马上关闭，显示下载进程。

### 截图

![图片](https://github.com/Richasy/Bili.Copilot/assets/92253850/cfec869c-cda6-4632-9761-83d01778d87f)
![图片](https://github.com/Richasy/Bili.Copilot/assets/92253850/5efd7e5c-ad37-4634-bc52-7129137c5e38)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Oceanlzj** [comment]
bbdown依赖ffmpeg进行下载 请检查ffmpeg是否正确安装
（可使用 winget install ffmpeg进行安装

**Comment by Richasy** [comment]
安装 BBDown 之后可以先尝试使用命令行下载一个视频，跑通之后再用哔哩助理
