### ISSUE TITLE
[Bug] Win11无法登录

### ISSUE THREAD

**Issue by pigeonssss** [Richasy/Bili.Copilot#136]
### Bug 描述

[同issues#124，](https://github.com/Richasy/Bili.Copilot/issues/124)

### 复现问题的步骤

```plain text
1.打开应用
2.打开移动端哔哩哔哩
3.扫码登录
```

### 预期行为

![屏幕截图 2023-10-01 105902](https://github.com/Richasy/Bili.Copilot/assets/133509962/2908f21c-155c-4d60-8200-4fc6eaac3e36)

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/133509962/7811ed87-2fe7-4e4e-b717-a9fd7ef47079)
在win10上可以登录
![image](https://github.com/Richasy/Bili.Copilot/assets/133509962/09b39de5-4b88-4081-a6ea-86e3c5c7c763)
老版本也可登录
![image](https://github.com/Richasy/Bili.Copilot/assets/133509962/c7a9e917-59f2-4cf9-9d62-357e87dfd478)
似乎是win11 beta版本的原因？

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

ms store

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 专业工作站版   操作系统版本  23H2  22631.2338 

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
如果是因系统版本才出现这个问题，那我这边应该是修不了的，可以先使用稳定版本
