### ISSUE TITLE
[Bug] 视频清晰度1080p及以上切换失效

### ISSUE THREAD

**Issue by PIut02** [Richasy/Bili.Copilot#14]
### Bug 描述

尝试切换1080p及以上选项均无效，视频最高只有720p，尝试重新登录和重启应用无效，测试了哔哩没有该问题

### 复现问题的步骤

```plain text
任意视频均有该问题
```

### 预期行为

能切换1080p及以上清晰度

### 截图

后面的是哔哩，前面的是哔哩助理
![image](https://github.com/Richasy/Bili.Copilot/assets/39442130/28064f0e-fe12-4e55-a5d1-1312d29d40e5)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2023-08-06.log](https://github.com/Richasy/Bili.Copilot/files/12269101/applog.2023-08-06.log)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你是大会员吗？

**Comment by PIut02** [comment]
是的

**Comment by Richasy** [comment]
重启一下应用看看呢？

**Comment by PIut02** [comment]
重启后问题依旧
