### ISSUE TITLE
[Feature] 播放页面右键菜单加入播放器解码元数据

### ISSUE THREAD

**Issue by Oceanlzj** [Richasy/Bili.Copilot#142]
### 问题描述

我希望在视频播放中可以可以查看解码器元数据信息
如：使用的编码格式、码率等信息

### 描述解决方案

播放器组件应该可以获取相关解码信息（或许
就和直播页面点击用户头像展示的窗口那样

### 备选方案

BBDown（什

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
原生播放器暂时无法获取相关的信息，如果你想看，可以切换到 ffmpeg 播放
