### ISSUE TITLE
[Bug] ARM64设备下无法加载ffmpeg

### ISSUE THREAD

**Issue by driver1998** [Richasy/Bili.Copilot#149]
### Bug 描述

 ARM64设备下依然无法加载ffmpeg

### 复现问题的步骤

```plain text
启动应用，试图打开直播
```

### 预期行为

应该可以看直播

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/22699485/fa54df44-a38f-494e-87f6-91e787678650)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

ARM64 设备

### 备注

用dumpbin看了一下ARM64 ffmpeg dll的依赖，似乎arm64版本引入了libx264，但没有提供x264的dll
![image](https://github.com/Richasy/Bili.Copilot/assets/22699485/7d536890-0c0c-4f5c-9447-2da3260dc4ef)

而x64版本没有引入x264

哔哩助理本身也是GPLv3协议，引用x264应该不是问题，但是否真的要引入还是由作者决定吧

另外avdevice-60.dll还引入了SDL2？这个依赖就有点莫名其妙了，建议去除
![image](https://github.com/Richasy/Bili.Copilot/assets/22699485/f0f1e0c1-a505-4ba7-86aa-db8c0b721dd8)

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩助理中

**Comment by driver1998** [comment]
如果能告知哔哩助理的ffmpeg是怎么编译的话，我可以帮忙协助精简一下依赖，我这里也有机器测试。

**Comment by driver1998** [comment]
刚刚下载了最新的ARM64 msix，ffmpeg只有一个dll文件？看着不太正常
![image](https://github.com/Richasy/Bili.Copilot/assets/22699485/74b778fa-fa13-4b72-bf7f-fa605a0c998c)

**Comment by Richasy** [comment]
@driver1998 Good catch! 刚刚已经重新上传了一次 ARM64 的包，这次应该好了
