### ISSUE TITLE
[Bug]直播不能正常观看

### ISSUE THREAD

**Issue by wubingcong** [Richasy/Bili.Copilot#15]
### Bug 描述

打开直播就卡退

### 复现问题的步骤

```plain text
进入直播
直接整个应用卡退
```

### 预期行为

正常观看直播内容

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
请提供日志文件以供分析

**Comment by wubingcong** [comment]
[applog.2023-08-06.log](https://github.com/Richasy/Bili.Copilot/files/12269760/applog.2023-08-06.log)
删除之前日志后重新打开直播闪退后的日志文件

**Comment by Richasy** [comment]
日志中虽然有错误，但是该错误不足以造成闪退。
推测可能是视频解析问题。
你可以在设置页面的 `播放器控制` 区块切换一下解码类型（软解）和解码器偏好再试试
