### ISSUE TITLE
[Bug] 评论区点赞的ToggleButton状态错乱

### ISSUE THREAD

**Issue by MSEDGE-CORE** [Richasy/Bili.Copilot#152]
### Bug 描述

评论区点赞的ToggleButton状态错乱

### 复现问题的步骤

```plain text
1.打开应用
2.进入一个视频的评论区
3.给任意一个评论点赞
4.将排序方式从最热切换到最新
5.发现最新的评论点赞ToggleButton亮起
6.点击这个评论对应的点赞ToggleButton
7.发现点赞ToggleButton未亮起，而是灭掉
8.将排序方式从最新切换到最热
7.发现3中评论的点赞ToggleButton未亮起
```

### 预期行为

在切换排序方式时重置并刷新点赞状态

### 截图

![屏幕截图 2023-10-15 100914](https://github.com/Richasy/Bili.Copilot/assets/74437699/9b0ccdb2-9f27-4b01-938e-20b1ea8d1c14)

### 应用来源

- [X] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [X] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2023-10-14.log](https://github.com/Richasy/Bili.Copilot/files/12908412/applog.2023-10-14.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by hez2010** [comment]
不仅 toggle button 的状态是错乱的，用一段时间后评论的详情展开列表也是错乱的
