### ISSUE TITLE
[Bug] 拖动窗口时黏糊糊的

### ISSUE THREAD

**Issue by Firedoge1** [Richasy/Bili.Copilot#155]
### Bug 描述

如题，窗口拖动时不是跟随鼠标，而是有一定加速度，还会黏着鼠标一起漂移

### 复现问题的步骤

```plain text
/
```

### 预期行为

正常拖动

### 应用来源

- [ ] Github
- [ ] AppCenter
- [x] 其它

### 其它来源

Microsoft Store

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 其它系统版本

Microsoft Windows 版本22H2(OS内部版本22621.2428)

### 运行设备

桌面/台式机, 桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这个不是应用本身的问题，跟设备渲染能力有关
