### ISSUE TITLE
[Bug] 地址栏弹出的预选项列表挡住了搜狗输入法的词语列表。。。

### ISSUE THREAD

**Issue by kulkatt** [Richasy/Bili.Copilot#157]
### Bug 描述

只要用搜狗输入法打一个字母，就会弹出个列表挡住输入法界面，很难继续打字了
![image](https://github.com/Richasy/Bili.Copilot/assets/24421888/ece92162-0ffa-422e-907a-9576a2947fb6)
由于搜狗输入法的出现位置就是鼠标下方，所以这样的话就基本没法用拼音输入法打字了，因为看不见词语的候选项

> 

### 复现问题的步骤

```plain text
1.打开应用
2.点搜索栏
3.试着用键盘输入拼音
```

### 预期行为

1.在搜狗拼音输入时不要弹出拼音字母对应的预选项
或者
2.地址栏弹出的列表跟搜狗列表的位置错开

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/24421888/f76c69a6-dca9-4713-a58b-699a3b822942)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 其它系统版本

win10 22H2

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
老毛病了，UWP, WinAppSDK 等类型的应用都有这个问题。
这个问题无法在应用侧修复，可以使用 Windows 自带的输入法，没这个问题
