### ISSUE TITLE
[Bug] 哔哩助理扫码登失效

### ISSUE THREAD

**Issue by 7887887** [Richasy/Bili.Copilot#158]
### Bug 描述

哔哩助理登录使用国内哔哩哔哩app、国际版哔哩哔哩app扫码登录时，手机提示成功，但是哔哩助理提示登录失败
![image](https://github.com/Richasy/Bili.Copilot/assets/66059365/8bd76ceb-823a-4b43-bd4a-6ba03d9e2fff)

### 复现问题的步骤

```plain text
1.打开哔哩助理
2.手机打开哔哩哔哩app
3.扫码登录
```

### 预期行为

希望大佬可以查看是否接口出现问题

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/66059365/c4c74ccb-a763-4b89-9891-76b4b4475a5c)

### 应用来源

- [ ] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Suheisdead** [comment]
同

**Comment by PurBlu** [comment]
+1

**Comment by ggyylxz1** [comment]
win10 +1

**Comment by chenxiaoangle** [comment]
win11 23H2 25982预览版同样出现此问题

**Comment by LJLlw** [comment]
+1

**Comment by zhfunc** [comment]
+1

**Comment by Pluto-Pro** [comment]
+1

**Comment by Fenger1228** [comment]
+1 22h2 电信网络 登陆失败 情况同题主描述一样

**Comment by zhblmy** [comment]
+1

**Comment by xinyunaha** [comment]
https://passport.bilibili.com/login/app/third?api=http://link.acg.tv/forum.php这个接口的返回值为{"code":20000,"message":"该版本已不支持当前功能，请升级新版本！"}，可能b站客户端调整了这个接口。。。。。。

**Comment by Liuyiyang888888** [comment]
https://passport.bilibili.com/ajax/miniLogin/minilogin
是这个接口

**Comment by hhhawa** [comment]
+1
