### ISSUE TITLE
[Bug] 无法修改BBdown配置文件

### ISSUE THREAD

**Issue by lilyblessing** [Richasy/Bili.Copilot#16]
### Bug 描述

无法修改BBdown配置文件，提示权限不足

### 复现问题的步骤

```plain text
此前使用过BBdown，配置了vsc作为`.config`文件的默认打开方式。

在哔哩助理的视频页中修改BBdown配置时
自动打开了vsc，修改后无法保存，提示权限不足。

查看文件所有者为system，用户没有写权限。
```

### 预期行为

允许保存，或直接调用外部配置文件。

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 其它系统版本

windows10 21H2 19044.1288

### 运行设备

桌面/台式机

### 备注

本身是有安装BBdown的，希望能直接读取原配置。
因为本身做的操作也就是把原配置复制一遍过来，可以考虑加一个开关

〔是否需要生成一个配置文件〕
若用户此前没有使用过BBdown，则选〔是〕；在安装完后提供一份包含少量参数的默认配置文件。
若是BBdown老用户则认为用户已经有一份自己的配置文件，直接调用BBdown下载即可。

### 人人为我，我为人人

None

**Comment by JupiterOdyssey** [comment]
遇到相同问题
