### ISSUE TITLE
[Feature] 快捷键全屏

### ISSUE THREAD

**Issue by IlysvlVEizbr** [Richasy/Bili.Copilot#161]
### 问题描述

在播放器界面，希望能使用Enter快捷键触发全屏模式，或者增加全屏快捷键设置，允许用户自定义按键触发全屏

### 描述解决方案

x86桌面端，非全屏播放时按Enter进入全屏，全屏状态下按ESC退出全屏

### 备选方案

有其他的全屏快捷键，并且在鼠标悬停于“全屏”按钮时，提示该快捷键

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
全屏快捷键是 F11
