### ISSUE TITLE
[Bug] 无法启动应用

### ISSUE THREAD

**Issue by Yur1et** [Richasy/Bili.Copilot#166]
### Bug 描述

依赖正常安装，msix也成功安装未报错。启动后不显示窗口，也没有相关进程。

### 复现问题的步骤

```plain text
双击图标启动，尝试过低版本兼容性和管理员权限启动，都没有用
```

### 预期行为

希望能正常启动应用

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
无法复现该问题，请尝试从应用商店下载安装
