### ISSUE TITLE
[Feature] 增加字号修改功能

### ISSUE THREAD

**Issue by LJLlw** [Richasy/Bili.Copilot#167]
### 问题描述

目前浏览视频流的时候感觉还是有点费劲，是否可以添加字号修改选项呢?😍
是否可以将视频标题加粗加大，增加视频封面大小，增加简介显示，甚至自定义字体！😊🥰

### 描述解决方案

是否可以将视频标题加粗加大，增加视频封面大小，增加简介显示，甚至自定义字体！😊🥰

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
暂无计划支持这个
