### ISSUE TITLE
[Bug]再次无法登录

### ISSUE THREAD

**Issue by XuHamsterKing** [Richasy/Bili.Copilot#172]
### Bug 描述

使用哔哩哔哩手机客户端（包括安卓和IOS）扫描二维码后提示登录成功，但哔哩助理中显示“登录失败，请稍后再试，尝试多次、更换其他软件扫码后均出现此问题。**哔哩助理版本1.2310.3.0，安卓客户端最新版**

### 复现问题的步骤

```plain text
1.在笔记本电脑上打开“哔哩助理”
2.在手机上打开“哔哩哔哩”
3.用手机上的”哔哩哔哩“扫描”哔哩助理“显示的二维码
4.在手机上授权登录
```

### 预期行为

修复该问题

### 截图

![屏幕截图 2023-11-29 153702](https://github.com/Richasy/Bili.Copilot/assets/152246586/d043dc74-317d-431d-8517-b5fddabd7c25)
手机提示登录成功后这样

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2(Build 22631.2715)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
无法复现该问题

**Comment by 1PercentSync** [comment]
我也出现了同样的问题
