### ISSUE TITLE
[Feature] 新窗口建议在原窗口的原位置之上或者旁边打开

### ISSUE THREAD

**Issue by windmaple233** [Richasy/Bili.Copilot#175]
### 问题描述

多显示器，点击产生一个新视频窗口，都会在主显示器打开，但是实际上一般都是在副屏看视频，这窗口拖来拖去就很难受。而且距离还很远，有时候一不留神还以为窗口没打开。

### 描述解决方案

建议在原窗口的原位置之上或者旁边打开，或者记录下上一个窗口的打开位置，下次打开新窗口就在之前位置打开。

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
下次更新
