### ISSUE TITLE
[Bug]  收藏夹分类获取不完整

### ISSUE THREAD

**Issue by zansbang** [Richasy/Bili.Copilot#179]
### Bug 描述

看了下代码默认只获取20条
![PixPin_2023-12-23_18-55-40](https://github.com/Richasy/Bili.Copilot/assets/1173895/d8d508f3-a2d8-4332-b7a1-93463872b4e9)

### 复现问题的步骤

```plain text
收藏 - 下拉收藏分类
```

### 预期行为

下拉收藏分类滚动到底部能继续加载下一页分类数据或者点下拉加载全部的收藏分类

### 截图

![PixPin_2023-12-23_18-58-57](https://github.com/Richasy/Bili.Copilot/assets/1173895/f26805d8-1a09-40cf-8a08-2566bfd70549)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 (Build 22631.2861)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩助理中

**Comment by Richasy** [comment]
你看的这个API是获取 PGC 内容的，比如追番/追剧。获取收藏夹列表的API看了下没有提供pagesize，默认应该是获取全部列表

**Comment by zansbang** [comment]
![PixPin_2024-01-14_17-26-08](https://github.com/Richasy/Bili.Copilot/assets/1173895/3d2193cc-c248-4ea0-8d6f-b73f88b5bf21)

我看了下这两个获取收藏夹的接口，一个是list-all，一个是list。
在视频播放页面点添加到收藏夹按钮的时候用的是list-all接口，在我的收藏页面上是list接口所以获取不全吧？
