### ISSUE TITLE
BBDown无法正常使用

### ISSUE THREAD

**Issue by Cody-Travers** [Richasy/Bili.Copilot#188]
### Bug 描述

BBDown无法下载视频

### 复现问题的步骤

```plain text
1.点击助理中下载按钮
2.没有任何反应，视频也未开始下载
```

### 预期行为

希望大佬说明下怎么使bbdown在您的助理上正常使用，包括安装方法和配置文件

### 截图

https://github.com/Richasy/Bili.Copilot/assets/139093182/9f916f24-42f6-4900-a54a-b11fca63c82e

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Meowjay1110** [comment]
[](https://github.com/nilaoda/BBDown/issues/305)
这里有比较详细的说明

**Comment by Cody-Travers** [comment]
> [nilaoda/BBDown#305](https://github.com/nilaoda/BBDown/issues/305) 这里有比较详细的说明

试过了，点击助理内下载按钮还是没任何反应

**Comment by Meowjay1110** [comment]
你看看是不是把bbdown.exe填进环境变量里去了
要填文件夹的路径，像这样：C:\Users\ZHOUS\Documents\BBDown
![屏幕截图 2023-12-31 100131](https://github.com/Richasy/Bili.Copilot/assets/109258169/72d26fd6-84c9-4ef7-ad3e-8d05bf138a83)

**Comment by Cody-Travers** [comment]
仔细检查了，这个确实填进去了，但是路径字母填错了两个，改过来就正常了，感谢老哥！
