### ISSUE TITLE
[Bug] 部分直播403

### ISSUE THREAD

**Issue by fxzxmicah** [Richasy/Bili.Copilot#189]
### Bug 描述

部分直播403。
另外在错误日志中还有一些其它错误。

### 复现问题的步骤

```plain text
似乎只是竖屏直播存在403问题。
还有偶尔发生的视频还未加载完毕但是已经开始播放声音的情况，如果此时关闭播放窗口，会导致整个界面卡死，此时似乎存在死循环之类的情况，会导致CPU占用一直在10%左右。
另外当主播下播后，我关闭当前播放窗口，就像截图中的那样，直播界面的刷新按钮全部失效。
```

### 预期行为

无报错，一切正常。

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/48860358/66efc605-2657-4846-9131-8626bdbe6f10)

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

应用商店

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2023-12-30.log](https://github.com/Richasy/Bili.Copilot/files/13797211/applog.2023-12-30.log)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
升级后应该能修复，今天更新发布后你可以再试下
