### ISSUE TITLE
[Bug] 应用程序图标没有设置

### ISSUE THREAD

**Issue by Gaoyifei1011** [Richasy/Bili.Copilot#191]
### Bug 描述

应用程序图标没有设置

### 复现问题的步骤

```plain text
None
```

### 预期行为

应用程序图标已设置

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/49179966/bca762d3-8dc8-4bb5-9c5b-44243a62f01a)

### 应用来源

- [X] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

Microsoft Store

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机, 桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
为什么需要设置这个exe的图标？

**Comment by Gaoyifei1011** [comment]
> 为什么需要设置这个exe的图标？

情况是这样的，今天遇到一个程序卡死了，需要在任务管理器结束运行，突然发现一个名称为Bili.Copilot.App的应用，发现才是哔哩助理，应用的图标没有显示出来，窗口的图标显示出来了，才发现没有应用图标。😂

![image](https://github.com/Richasy/Bili.Copilot/assets/49179966/1a98d10f-5121-4366-bcd6-e05db89f0fce)
