### ISSUE TITLE
[Bug] 看上几个视频之后程序会假死

### ISSUE THREAD

**Issue by wekerSnail** [Richasy/Bili.Copilot#193]
### Bug 描述

看上几个视频之后程序会假死，此时打开的视频会正常播放，但是主页已经无法操作，程序点击关闭也无法关闭，或者关闭之后，进程还在，到时无法重启，只能杀掉进程才行。

### 复现问题的步骤

```plain text
目前我这台电脑只要看上一段时间的视频就基本会必现，跟新了几次版本，都存在一样的问题， 不知道是不是硬件或者系统的兼容问题
```

### 预期行为

正常使用，长时间使用不要出现程序假死

### 应用来源

- [X] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

版本	Windows 11 专业工作站版 版本	23H2 安装日期	‎2022/‎11/‎9 操作系统版本	22631.2861 体验	Windows Feature Experience Pack 1000.22681.1000.0

### 运行设备

桌面/台式机

### 日志记录

[applog.2023-12-31.log](https://github.com/Richasy/Bili.Copilot/files/13800391/applog.2023-12-31.log)

### 人人为我，我为人人

None

**Comment by Sanlorng** [comment]
@Richasy 我也遇到了，查看日志，看起来像是弹幕层的问题。
[applog.2024-01-01.log](https://github.com/Richasy/Bili.Copilot/files/13804886/applog.2024-01-01.log)

**Comment by wekerSnail** [comment]
更新了最新的版本，问题依然存在，甚至发生的频率更高了，更新完使用了三次，都出现了卡死，并且卡死之后没有产生日志，关闭应用之后，视频仍然在后台播放，只能杀掉进程。
