### ISSUE TITLE
无法安装最新版本

### ISSUE THREAD

**Issue by jjkhl** [Richasy/Bili.Copilot#195]
### Bug 描述

将证书安装到受信任的根证书颁发机构后，还是出现以下错误。希望能有大佬指导下如何解决。
![ApplicationFrameHost_oYa7eilIBn](https://github.com/Richasy/Bili.Copilot/assets/75430067/83c21687-9d48-4217-8c35-210bf4d54a3b)

### 复现问题的步骤

```plain text
安装证书后还是显示无法安装最新版本1.2401.1.0
```

### 预期行为

问题解决，能够安装新版本

### 应用来源

- [ ] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
请使用install.ps1脚本安装，右键单击ps1文件，然后选择通过PowerShell运行

**Comment by jjkhl** [comment]
> 请使用install.ps1脚本安装，右键单击ps1文件，然后选择通过PowerShell运行

好的谢谢大佬，问题解决了。
