### ISSUE TITLE
是否考虑发行ARM64编译的软件包

### ISSUE THREAD

**Issue by 2103894869** [Richasy/Bili.Copilot#196]
### 问题描述

目前WIN11上AMD64的ARM转译运行基本成熟，但转译效率依然堪忧
根据使用上一代哔哩对比来看，
在SDM845上运行ADM64软件时，功耗往往会高出2W，并且处理缓慢的情况相较原生ARM明显增多

### 描述解决方案

鉴于您在前两代的哔哩客户端都发行了ARM编译的版本
希望能考虑发行哔哩助理的ARM64版本

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
发布了
