### ISSUE TITLE
[Bug] （UI）个人主页窗口没有限制窗口缩放

### ISSUE THREAD

**Issue by MSEDGE-CORE** [Richasy/Bili.Copilot#20]
### Bug 描述

个人主页窗口没有限制窗口缩放

### 复现问题的步骤

```plain text
1.打开应用
2.点击“动态数”
3.将光标移动到弹出的窗口边缘
4.点击并拖动
```

### 预期行为

不做出反应
或
右上角最大化按钮可用

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/74437699/f2f3865e-78d6-4099-8185-865b9d754797)
![image](https://github.com/Richasy/Bili.Copilot/assets/74437699/a4539cc2-49e0-4ebd-aefa-4663e6fc0999)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 Canary Build 25921

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2023-08-06.log](https://github.com/Richasy/Bili.Copilot/files/12269743/applog.2023-08-06.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这个是 by design，这里没有限制窗口大小的必要，所以允许调整大小

**Comment by MSEDGE-CORE** [comment]
此处最大化按钮处于disabled状态，与可调整大小冲突
