### ISSUE TITLE
github下载太慢

### ISSUE THREAD

**Issue by Cody-Travers** [Richasy/Bili.Copilot#206]
### 问题描述

如题，下载速度只有60k出头，用steam++或者其他的都加速不了，下个更新包得一个小时

### 描述解决方案

可不可以搞一个国内网盘更新的链接，GitHub这个网速太折磨人了

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
这个不是应用的问题。
哔哩助理提供了两个下载渠道，一个是 Github，另一个是 Microsoft Store。
Github 更新最快，因为无需审核，但是下载等方面对于国内用户不太友好。
不会架梯子的同学可以等商店更新，那个更稳定且速度更快，也是推荐的方式。

其它的下载渠道不做考虑

**Comment by Cody-Travers** [comment]
那我用的精简版win11没有Microsoft Store咋办，GitHub打开都费劲别说下载了
