### ISSUE TITLE
[Bug] 无法登录

### ISSUE THREAD

**Issue by 1PercentSync** [Richasy/Bili.Copilot#217]
### Bug 描述

扫二维码登录后显示登录失败，请稍后重试

### 复现问题的步骤

```plain text
1.打开应用
2.用移动端扫码
```

### 预期行为

正常登录

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/127626920/3cee3de9-8f87-4645-815f-27bf29d809bb)

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

Microsoft Store

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 22631.2861

### 运行设备

桌面/台式机

### 日志记录

还进不去设置

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
你的移动客户端版本是什么？

**Comment by 1PercentSync** [comment]
> 你的移动客户端版本是什么？

最新的美区app store版bilibili 3.18.0和ipad版3.65.2

**Comment by Richasy** [comment]
感觉可能是你的账户被风控了

**Comment by 1PercentSync** [comment]
> 感觉可能是你的账户被风控了

那太惨了

**Comment by LxnChan** [comment]
我也遇到了无法登录的问题，按登录时的提示来看是从tv版的api登录的，试了一下官方的tv版是可以登录的

手机端是Android官方版7.51.0

**Comment by AronnaxM** [comment]
我也遇到了 安卓 9 Bilibili 官方客户端扫码提示登陆失败的问题，已确认账户未被风控，不知此问题能否通过更换登录api为网页版或者增加通过账号密码密码登录选项解决。
