### ISSUE TITLE
[Bug] 个人动态加载问题

### ISSUE THREAD

**Issue by Meowjay1110** [Richasy/Bili.Copilot#224]
### Bug 描述

打开动态页面后无法加载个人动态

### 复现问题的步骤

```plain text
1. 打开应用
2. 点击“动态”
3. 任意点击用户的卡片，点击若干次
4. 动态无法加载

```

### 预期行为

动态正常加载

### 截图

https://github.com/Richasy/Bili.Copilot/assets/109258169/086be482-567e-4fe8-879c-21142ee62bee

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 (Build 22635.2921)

### 运行设备

桌面/台式机

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
麻烦进设置页面，找到应用日志，然后把当天的日志发上来，我这边没有复现这个问题

**Comment by Meowjay1110** [comment]
应用没有记录日志
![image](https://github.com/Richasy/Bili.Copilot/assets/109258169/c300dd50-c1f9-4f44-bc08-469e76fcce35)
我重装试下

**Comment by Meowjay1110** [comment]
重装完毕，仍然出现问题

**Comment by Richasy** [comment]
如果说点的慢一点，或者切换页面再回来点击出问题的UP主，是否能显示出动态？

**Comment by Meowjay1110** [comment]
点击的慢一点一样会出现问题
切换页面后能够恢复正常，但点击几个其他UP主后会再次出现问题

**Comment by Meowjay1110** [comment]
大佬你好
修Bug辛苦了

更新到最新版本后我这边仍然存在点击若干次后就无法加载UP主个人动态的问题
如果可能的话也请修复一下
谢谢啦(≧∀≦)ゞ

**Comment by Meowjay1110** [comment]
因为这个 issue 里包括了**两个 bug**而其中一个似乎还没有得到修复
所以还请您看看要不要 reopen 一下
给您带来麻烦什么的抱歉啦(。・ω・。)

**Comment by Richasy** [comment]
OK，今天发个版本你再看下，要是修了就麻烦你关掉这个issue了
