### ISSUE TITLE
[Bug] 播放完视频后关闭视频窗口整个应用闪退

### ISSUE THREAD

**Issue by FFFaaaayyy** [Richasy/Bili.Copilot#225]
### Bug 描述

rt，更新到最新版本1.2401.3.0后，只要点击某个视频再关闭这个视频窗口，整个应用就会直接闪退。

### 复现问题的步骤

```plain text
1. 打开应用
2. 点击视频
3. 视频播放中
4. 关闭视频窗口
5. 主界面及应用自动关闭
```

### 预期行为

不闪退。。

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-01-11.log](https://github.com/Richasy/Bili.Copilot/files/13897672/applog.2024-01-11.log)

### 人人为我，我为人人

None

**Comment by Oukaka** [comment]
同样多次遇到该问题，原生/ffmpeg均会崩溃
看了下助理的log日志，无相关内容

windows日志如下(几次日志内容几乎相同)：
>错误应用程序名称: Bili.Copilot.App.exe，版本: 1.0.0.0，时间戳: 0x65410000
错误模块名称: CoreMessagingXP.dll，版本: 10.0.22624.1058，时间戳: 0xbc9f21de
异常代码: 0xc000027b
错误偏移量: 0x000000000008f52c
错误进程 ID: 0x0x57E8
错误应用程序启动时间: 0x0x1DA4499701E1521
错误应用程序路径: C:\Program Files\WindowsApps\Richasy.Bili.Copilot_1.2401.3.0_x64__g7ew4fxhv1f46\Bili.Copilot.App.exe
错误模块路径: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1082.2259.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll
报告 ID: 929f2997-616f-413d-bbba-ba74794a9f1d
错误程序包全名: Richasy.Bili.Copilot_1.2401.3.0_x64__g7ew4fxhv1f46
错误程序包相对应用程序 ID: App

**Comment by tjqj** [comment]
问题一样，而且本次更新出的单窗口播放仍然会在返回主页面后闪退

**Comment by ManyullynSword** [comment]
按照最新版的介绍那里切换后，问题依然没有得到解决，反而更加容易闪退了

**Comment by zqymoe** [comment]
同上，每次关闭视频窗口都会闪退

**Comment by TaivasJumala** [comment]
1.2401.4.0
