### ISSUE TITLE
[Bug] 收藏夹超过20个后似乎将无法加载

### ISSUE THREAD

**Issue by LOGYT-Eberk** [Richasy/Bili.Copilot#228]
### Bug 描述

当用户收藏夹超过20个后，超出的收藏夹似乎无法显示。我没有在应用中找到类似“加载更多”的按钮。

### 复现问题的步骤

```plain text
1.打开应用
2.点击右上角用户头像，进入“我的收藏”界面
3.左侧边栏似乎只会加载前20个收藏夹。当用户创建了超过20个收藏夹后，之后的部分将不会显示
```

### 预期行为

左侧边栏能显示所有的收藏夹，或提供类似“加载更多“的按钮。

### 截图

在下面这张截图中，另一个哔哩哔哩第三方客户端成功加载了”摄影“之后的收藏夹，但bili copilot则不能。

<img width="563" alt="屏幕截图 2024-01-11 221328" src="https://github.com/Richasy/Bili.Copilot/assets/117907349/39ecbcf1-57e5-4ca5-aafa-d5f68c3006ef">

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 22635.2921

### 运行设备

ARM64 设备

### 人人为我，我为人人

我更擅长发现问题

**Comment by zcq15** [comment]
版本1.2402.2.0，此bug依然存在
