### ISSUE TITLE
点赞

### ISSUE THREAD

**Issue by ManyullynSword** [Richasy/Bili.Copilot#229]
### 问题描述

无法点赞、投币、关注与收藏，更不能三连。

### 描述解决方案

像原版客户端那样在触屏或移动鼠标后有些小按钮

### 备选方案

像网页版那样的视频交互方式

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
点击播放控制器左侧的包含视频名称和用户头像的那个按钮，弹出侧边详情信息进行点赞等操作
