### ISSUE TITLE
[Bug] （UI、不重要）视频窗口详细信息界面无法点击

### ISSUE THREAD

**Issue by MSEDGE-CORE** [Richasy/Bili.Copilot#23]
### Bug 描述

视频窗口详细信息界面顶部被标题栏遮挡，无法点击“信息”、“关联视频”、“评论”按钮的顶部

### 复现问题的步骤

```plain text
1.打开应用
2.点击底部“推荐视频”
3.点击一个视频
4.点击播放控制栏中的视频标题
5.点击顶部“评论”字的顶部向下几像素
6.发现有几个像素无法点击
```

### 预期行为

有反应

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/74437699/172f2c58-5bd6-4d43-aca8-134696aa71f1)
![image](https://github.com/Richasy/Bili.Copilot/assets/74437699/550084f1-130e-41c6-b5d6-69d6aa46ab01)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 Canary Build 25921

### 日志记录

[applog.2023-08-06.log](https://github.com/Richasy/Bili.Copilot/files/12269756/applog.2023-08-06.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
感谢反馈，这是已知问题。顶部不可点击的几个像素属于标题栏拖拽区域，我也不好让控件离顶部太远，这样比较别扭。目前导航条目的大部分都是可以点击的，不会阻止操作。
我暂时标记为 `未计划`，如果这个问题你比较在意，可以重新打开，后续根据反馈我再进行调整

**Comment by MSEDGE-CORE** [comment]
我有几个方案，不知道是否符合逻辑以及设计规范：
1.在显示信息板时，信息板顶部标题栏区域添加“哔哩助理”图标以及文本
2.信息板改成窗口内的“悬浮窗”，顶部空出标题栏，同时左边缘和下边缘与上面等宽（感觉不合适）

同时，我希望信息板能加入实时亚克力模糊，并将顶部NavigationView的“关联视频”移至“评论”右侧（不知道大佬怎么看）。
