### ISSUE TITLE
[Bug] 使用闪退

### ISSUE THREAD

**Issue by yyz0313** [Richasy/Bili.Copilot#230]
### Bug 描述

应用闪退。。

### 复现问题的步骤

```plain text
1打开应用
2我手动调整了清晰度 打开了4k
3关闭视频 
4闪退
```

### 预期行为

希望解决闪退

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

微软应用商店

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-01-14.log](https://github.com/Richasy/Bili.Copilot/files/13930888/applog.2024-01-14.log)

### 备注

谢谢博主

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
重复问题，暂时关闭
