### ISSUE TITLE
[Bug] 程序闪退

### ISSUE THREAD

**Issue by nbcongmingdan** [Richasy/Bili.Copilot#233]
### Bug 描述

关闭视频播放窗口后整个app闪退。

### 复现问题的步骤

```plain text
1. 打开应用
2. 打开视频播放
3. 关闭视频播放器窗口
4. 程序出现闪退问题
```

### 预期行为

关闭视频播放器后可以继续选择视频观看

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

WIN10

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
重复问题，暂时关闭
