### ISSUE TITLE
[Feature] 能改成鼠标滚轮调整音量吗？

### ISSUE THREAD

**Issue by kulkatt** [Richasy/Bili.Copilot#236]
### 问题描述

按住播放器上下拉鼠标这个调音量的方式操作太繁琐了，绝大多数人应该都没有windows触摸屏吧。

### 描述解决方案

希望能像绝大多数PC和Mac上的视频播放器一样，用鼠标滚轮调节音量

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
暂无此计划
