### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by ManyullynSword** [Richasy/Bili.Copilot#240]
### Bug 描述

用着用着就会是不是闪退

### 复现问题的步骤

```plain text
1.打开应用
2.随便刷着视频
3.闪退，应用直接关闭
```

### 预期行为

不再闪退

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 10 22H2 19045.3803

### 运行设备

桌面/台式机

### 日志记录

没有？

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
重复问题，暂时关闭
