### ISSUE TITLE
[Bug] 触控模式下长按触发右击，二倍速和右键菜单同时出现。

### ISSUE THREAD

**Issue by KyoSakuyo** [Richasy/Bili.Copilot#245]
### Bug 描述

在触控设备下，长按会触发右击，使得二倍速和右键菜单同时出现。

### 复现问题的步骤

```plain text
在触控设备下，长按会触发右击，使得二倍速和右键菜单同时出现。
```

### 预期行为

希望长按时只会有倍速播放的效果，无右键菜单出现。

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by KyoSakuyo** [comment]
![telegram-cloud-photo-size-5-6143191423000885592-y](https://github.com/Richasy/Bili.Copilot/assets/59904064/bb1fe048-b4a7-4f9c-8622-1887bd26cf39)
补充实拍照片

**Comment by Richasy** [comment]
下次更新
