### ISSUE TITLE
[Bug] 触控模式下，操控悬浮窗出现的时间太短了

### ISSUE THREAD

**Issue by KyoSakuyo** [Richasy/Bili.Copilot#246]
### Bug 描述

在触控模式下，操控悬浮窗出现的时间太短了

### 复现问题的步骤

```plain text
请参考录制的视频，

每次单击后，触控悬浮窗都只能显现0.1秒左右，难以操控，拖动进度条也无法实现。
```

### 预期行为

希望对触控的适配能更好一些。

### 截图

https://github.com/Richasy/Bili.Copilot/assets/59904064/6604fc95-1bf8-4f40-8fcb-b73e2fdf8bdc

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
我倒是没有复现这种快速消失的情况……触屏下你可以尝试手势操作：
1. 双击播放/暂停
2. 左右滑动调整进度
3. 上下滑动调整音量

点击视频空白处弹出的播放控制器可能存留时间久一点？
