### ISSUE TITLE
[Feature] 希望加入动态磁贴功能

### ISSUE THREAD

**Issue by Firedoge1** [Richasy/Bili.Copilot#248]
### 问题描述

我用[ExplorerPatcher](https://github.com/valinet/ExplorerPatcher)在Windows 11上还原了全屏开始菜单，希望[哔哩UWP](https://github.com/Richasy/Bili.Uwp)或者[哔哩助理](https://github.com/Richasy/Bili.Copilot)加入动态磁贴。

### 描述解决方案

[酷安UWP和LIte](https://github.com/Coolapk-UWP/Coolapk-UWP)（[自动编译版](https://dev.azure.com/wherewhere/Coolapk-UWP/_build)）已经支持了。

### 人人为我，我为人人

None

**Comment by Firedoge1** [comment]
在此问候Windows 11广告小组件团队全家，祝全家爆炸灵车飘飘

**Comment by Richasy** [comment]
哔哩助理主要面向win11，磁贴的交互方式虽然挺好，但终究已经过去，它不会是当前开发的优先事项。

P.S. 请不要在issue里输出情绪哦😏

**Comment by Firedoge1** [comment]
> 哔哩助理主要面向win11，磁贴的交互方式虽然挺好，但终究已经过去，它不会是当前开发的优先事项。
> 
> P.S. 请不要在issue里输出情绪哦😏

已经删除人身攻击言论

**Comment by Firedoge1** [comment]
> 哔哩助理主要面向win11，磁贴的交互方式虽然挺好，但终究已经过去，它不会是当前开发的优先事项。
> 
> P.S. 请不要在issue里输出情绪哦😏

不优先开发≠不开发![滑稽](https://github.com/Richasy/Bili.Copilot/assets/131285299/fecfd066-ae46-4605-be7b-bcce54a5b508)
