### ISSUE TITLE
[Bug] 视频播放途中失去音频

### ISSUE THREAD

**Issue by yimo0908** [Richasy/Bili.Copilot#25]
### Bug 描述

视频观看中突然无声

### 复现问题的步骤

```plain text
1.打开应用
2.点击动态视频播放
3.观看几分钟后突然失去音频
4.切换解码器偏好H.264→ H.265，bug复现
5.再次切换解码器偏好 → AVI，bug复现
```

### 预期行为

能够正常的播放视频

### 应用来源

- [ ] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 22H2 (Build 22631)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2023-08-06.log](https://github.com/Richasy/Bili.Copilot/files/12269893/applog.2023-08-06.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by wxz6079** [comment]
没有声音后，暂停再播放就会有声音，但是有几率又会丢失声音

**Comment by Richasy** [comment]
可以通过使用本机播放器解决这个问题，稍后会更新
