### ISSUE TITLE
[Bug] 视频播放失败无法返回

### ISSUE THREAD

**Issue by gwj0323** [Richasy/Bili.Copilot#252]
### Bug 描述

遇到视频播放失败时，没有返回按钮

### 复现问题的步骤

```plain text
打开哔哩哔哩电影
因为我在国外，地区限制
显示视频播放失败播放信息请求失败
无法返回，只能强行点击右上角关闭按钮返回上一级
```

### 预期行为

增加一个返回按钮

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/42038896/30596fc2-1643-4118-98a6-e89f47d4bda9)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
下次更新会修复这个问题。作为临时解决方案，你可以在设置->播放模式->播放器窗口新建行为，调整为单窗口，这样如果再出现错误，可以直接关闭播放窗口
