### ISSUE TITLE
接管网页

### ISSUE THREAD

**Issue by ManyullynSword** [Richasy/Bili.Copilot#256]
### 问题描述

在其它程序中打开bilibili.com等B站的链接，依然是使用浏览器打开，且在助理里打开消息，明明也是B站的网页，却会使用浏览器打开。

### 描述解决方案

使用其它程序打开bilibili.com等B站的链接，和在助理里打开消息，打开的是助理的新页面。

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
你这对于一个第三方应用来说，要求过高了……

**Comment by ManyullynSword** [comment]
> 你这对于一个第三方应用来说，要求过高了……

或许确实过高了，使用第三方应用不就是为了获得比官方更好的体验吗？我这并不是强硬的要求，这只是一个小小的请求。

**Comment by ManyullynSword** [comment]
你可以参考Edge将网页添加为的应用，那种应用是可以接管除了在浏览器地址栏内输入的网站的 。

**Comment by Richasy** [comment]
1. 我对第三方应用的理解和你有些许的不同，第三方应用并不是为了更好的体验（一个人很难与整个公司的体量相抗），而是为了差异化的体验，或者说，是为了满足部分人特殊的需求，这部分需求暂时不能由官方应用满足。
2. 你说的 Edge 应用什么的应该是 PWA，这样建议还是直接使用网页版。

你可能不了解所谓接管的含义，这意味着应用必须实现网页的所有（是所有）功能，且必须得到数据后端的支持，在需要的时候跳转到指定的页面。这对于第三方应用来说是不可能实现的

**Comment by ManyullynSword** [comment]
> 1. 我对第三方应用的理解和你有些许的不同，第三方应用并不是为了更好的体验（一个人很难与整个公司的体量相抗），而是为了差异化的体验，或者说，是为了满足部分人特殊的需求，这部分需求暂时不能由官方应用满足。
> 2. 你说的 Edge 应用什么的应该是 PWA，这样建议还是直接使用网页版。
> 
> 你可能不了解所谓接管的含义，这意味着应用必须实现网页的所有（是所有）功能，且必须得到数据后端的支持，在需要的时候跳转到指定的页面。这对于第三方应用来说是不可能实现的

那么为什么官方应用可以实现呢？网页是无法闭源的，随手一下就能获取到HTML源文件，为什么官方的可以，而第三方的不行呢？

**Comment by Richasy** [comment]
建议了解一下网页是如何运作的，你忽略了服务器
