### ISSUE TITLE
附件

### ISSUE THREAD

**Issue by ManyullynSword** [Richasy/Bili.Copilot#264]
### 问题描述

由于该应用目前还是Bug繁多，所以希望开通附件下载

### 描述解决方案

开通GitHub自动构建的附件下载（GitHub Actions）。

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by ManyullynSword** [comment]
> 自动构建和修bug间的关系是什么呢？

自动构建的版本可以让用户尽快使用到修了Bug的版本，我看你应该也有构建，不过没有开放附件下载

**Comment by Richasy** [comment]
这个不太符合目前哔哩的一个开发流程，我也就这段时间勤快点，等后面稳定了基本上就不怎么管了。我一般会在群里发布内测版本，但也就测几天。自动构建有点麻烦，不想搞了（仓库里的是旧的配置，我也不清楚还能不能用）
