### ISSUE TITLE
[Feature] 未来会支持xbox吗

### ISSUE THREAD

**Issue by lithiumleeow** [Richasy/Bili.Copilot#266]
### 问题描述

xbox已经是一个吃灰的盒子了
想让它变成一个电视盒子，目前xbox上的几款bili客户端都不是很好用
容易出现卡顿和闪退的问题，有没有可能会支持到xbox端呢

### 描述解决方案

像哔哩那样支持xbox，xbox手柄友好操作

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
目前所使用的开发框架 Windows App SDK 不提供对 xbox 的支持，所以哔哩助理也无法支持 xbox，后续如果 WinAppSDK 能够支持 xbox，那么这边会考虑跟进

**Comment by durjgdjajqsbdbfj** [comment]
> 续

那能继续维护之前的blli uwp吗？Bili bili客户端已经停止更新了，找不到其他更好的替代品了
