### ISSUE TITLE
[Bug] 1.2402.1.0版本，直播无法更换清晰度

### ISSUE THREAD

**Issue by Marriagekill** [Richasy/Bili.Copilot#279]
### Bug 描述

无论您如何调整直播画面的画质和清晰度，以下视频统计信息始终保持不变：

- 视频尺寸：854x480
- 帧率：30

### 复现问题的步骤

```plain text
省略
```

### 预期行为

省略

### 截图

![_20240201165801](https://github.com/Richasy/Bili.Copilot/assets/157476979/326c294d-8e2d-49dc-9d2d-aaf1cae5b396)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 10 22H2 （内部版号 19045.3208）

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
该问题会在下个版本中修复，如果你偏好看直播，可以在设置里先切换成网页播放器
