### ISSUE TITLE
关闭视频后仍然在播放，后台有声音。

### ISSUE THREAD

**Issue by weixieyou** [Richasy/Bili.Copilot#283]
### Bug 描述

关闭视频后仍然在播放，后台有声音。

### 复现问题的步骤

```plain text
1
```

### 预期行为

1

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
用的是哪种播放器类型？切换播放器类型是否可以解决？

**Comment by wekerSnail** [comment]
> 用的是哪种播放器类型？切换播放器类型是否可以解决？

这个问题应该还是那个播放器卡死导致的，程序其实已经假死，在后台为播完的视频会继续播放，但是程序只能直接杀进程才能关闭，目前最新的版本不使用web播放器时，这个问题比老版本更容易出现，ffmeg的播放器直接就是黑屏

**Comment by weixieyou** [comment]
> 使用哪种播放器类型？切换播放器类型是否可以解决？

2种播放器都有这个问题，

**Comment by weixieyou** [comment]
希望能添加杜比的支持，

**Comment by M-Hun** [comment]
假死关闭应用后，要重启电脑才能再次打开应用。不重启电脑就打不开。
