### ISSUE TITLE
连接 BBdown 后无法下载高画质

### ISSUE THREAD

**Issue by SubaruamanE** [Richasy/Bili.Copilot#284]
### Bug 描述

配置好BBDown，设置完环境变量后，在 BB down 中登录了大会员账号，并且哔哩助理中也登录了，但实测哔哩助理中的 BBdown无法下载1080P高清以上的画质（会员画质），然而直接打开BBdown  在命令行中可以下载

### 复现问题的步骤

```plain text
1、打开客户端（前提已经配置好BBDown）
2、任意选择一条视频
3、选择下载
4、发现下载的视频不是最高画质
```

### 预期行为

希望能在哔哩助理客户端中的BBDown 中下载最高的画质

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
检查一下哔哩助理生成的命令和你直接使用 BBDown 的命令有什么不同？或者你把你的 BBDown 命令发出来

**Comment by Richasy** [comment]
在最新 1.6.1 版本中无法复现

**Comment by SubaruamanE** [comment]
<img width="1231" alt="clipboard-image-1706884007" src="https://github.com/Richasy/Bili.Copilot/assets/158047159/a45817cf-74a7-4857-9d6e-2de207751f7c">
<img width="1109" alt="clipboard-image-1706884215" src="https://github.com/Richasy/Bili.Copilot/assets/158047159/64d69e5f-18ea-4e51-bc5c-2fed2a15c9f5">

**Comment by SubaruamanE** [comment]
我想我可能明白了，应该是我配置文件写的有问题，它1080p 60帧以上不支持无水印，所以自动向下了，应该是这个问题

**Comment by SubaruamanE** [comment]
问题已解决，也给以后遇到这个问题的人提供一下帮助：若要下载1080p 60帧以上的画质视频（1080p 高清无所谓），配置文件中不要输入-tv，因为高画质视频不支持去水印！
最后还是要感谢作者大大做的这么好的应用，支持正义原生应用，哔哩哔哩官方盗版滚开（
