### ISSUE TITLE
[Bug] 全部动态加载时偶发应用卡死

### ISSUE THREAD

**Issue by Meowjay1110** [Richasy/Bili.Copilot#289]
### Bug 描述

浏览全部动态时应用卡死

### 复现问题的步骤

```plain text
1. 打开应用
2. 点击 “动态”
3. 向下滑动
4. 应用卡死
```

### 预期行为

动态正常加载

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 (Build 22635.3130)

### 运行设备

桌面/台式机

### 日志记录

[applog.2024-02-02.log](https://github.com/Richasy/Bili.Copilot/files/14139911/applog.2024-02-02.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Tncent** [comment]
不仅是动态，若先点击动态再打开视频，那么返回键将偶发性失效
