### ISSUE TITLE
[Bug] 播放音频时出现卡顿

### ISSUE THREAD

**Issue by Moujie2022** [Richasy/Bili.Copilot#29]
### Bug 描述

播放视频或单独播放音频时进行任意其它操作音频便会出现卡顿. 使用哔哩或官方网页版均无此问题. 音质偏好选择 "标准" 时仍然有此问题.

### 复现问题的步骤

```plain text
1. 播放任意一个视频
2. 进行任意操作
3. 音频出现卡顿
```

### 预期行为

音频流畅播放

### 截图

![屏幕截图 2023-08-07 104254](https://github.com/Richasy/Bili.Copilot/assets/109258169/68702be4-a537-4e67-a58c-79227fe2f144)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 22631.2129

### 运行设备

桌面/台式机

### 日志记录

[applog.2023-08-07.log](https://github.com/Richasy/Bili.Copilot/files/12271719/applog.2023-08-07.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
我后来发现这个问题和帧率有关，视频帧率大于等于帧时就会出现这个问题（网络不好的时候也会），所以作为临时方案，可以选择普通的1080P视频进行观看。
我会继续查找解决方案
