### ISSUE TITLE
[Bug] UP主页面中粉丝数和关注数的返回标无效

### ISSUE THREAD

**Issue by ssxzi** [Richasy/Bili.Copilot#292]
### Bug 描述

UP主页面中粉丝数和关注数的返回标无效

### 复现问题的步骤

```plain text
1. 打开应用
2. 打开视频
3. 点击左侧“展开详情”
4. 点击UP主头像
5. 点击“粉丝数”
```

### 预期行为

返回标可以返回到UP主页面

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/42813459/79d43b82-8f1c-4e61-8b46-27994ca85b3f)

### 应用来源

- [ ] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 10 22H2

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这边应该是客户区没设置好，你可以尝试把光标移到按钮的下半区域，应该就可以点击了

**Comment by M-Hun** [comment]
> 这边应该是客户区没设置好，你可以尝试把光标移到按钮的下半区域，应该就可以点击了

把光标移到按钮的下半区域，可以点击。
