### ISSUE TITLE
[Bug] 某些控件存在重复获取鼠标单击导致双击

### ISSUE THREAD

**Issue by Tncent** [Richasy/Bili.Copilot#293]
### Bug 描述

如SpinBox，若鼠标单击时焦点正好处于SpinBox内和关闭SpinBox的X上时，SpinBox会先获取到焦点再失去焦点，推测是由于同一控件重复获取了两次鼠标单击指令，一次单击SpinBox获取焦点，一次单击X退出SpinBox的单击模式

### 复现问题的步骤

```plain text
例子：
[位置]   设置->播放器控制->单次快进/快退时长
单击下图所示位置

理论上界面上任何地区的SpinBox都存在如此问题
```

### 预期行为

SpinBox出现获取焦点并马上退出编辑模式

### 截图

![BugFix20240203133027](https://github.com/Richasy/Bili.Copilot/assets/77388348/6140d895-2b11-43c2-968a-a2d13f885e64)

### 应用来源

- [x] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 (Build 22631)

### 运行设备

桌面/台式机

### 日志记录

不属于程序崩溃，问题存在于正常运行中

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这个应该是 WinUI 控件的问题……我这边暂时不会去修，不过有时间我可以给他们报个bug
