### ISSUE TITLE
无法观看直播

### ISSUE THREAD

**Issue by HiHeeko** [Richasy/Bili.Copilot#294]
### Bug 描述

无法查看任何直播，即使更改[播放器类型]。总是会显示Unknown: Specified method is not
supported.

### 复现问题的步骤

```plain text
1.打开应用
2.左侧栏点击[直播]
3.点击任意直播
4.加载一段时间后显示[Unknown: Specified method is not
supported.]
```

### 预期行为

直播界面正常显示（？）

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/152047023/aa0905ad-5c0a-4463-9a38-548e7f4ca6df)

### 应用来源

- [ ] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 arm64

### 运行设备

桌面/平板或笔记本, ARM64 设备

### 日志记录

[applog.2024-02-03.log](https://github.com/Richasy/Bili.Copilot/files/14151671/applog.2024-02-03.log)

### 备注

![image](https://github.com/Richasy/Bili.Copilot/assets/152047023/ff140520-21c4-4431-880f-fa2033e15ba1)
![image](https://github.com/Richasy/Bili.Copilot/assets/152047023/4f8f93c9-2574-450d-9010-73368aaeeb96)

### 人人为我，我为人人

我更擅长发现问题

**Comment by theblueandblackcrow** [comment]
+1
同样发现这种情况
甚至比你的还严重
直接闪退了

**Comment by Richasy** [comment]
@HiHeeko  从日志记录来看，是没有获取到直播间的播放信息，你查看的直播间ID是多少？其它的直播间（特别是观看人数多的直播间）是否有这个问题？

**Comment by Richasy** [comment]
@theblueandblackcrow 直播间观看闪退的话，不要犹豫，直接在设置里切到网页播放器吧

**Comment by theblueandblackcrow** [comment]
> @theblueandblackcrow 直播间观看闪退的话，不要犹豫，直接在设置里切到网页播放器吧

不是观看时就闪退，是一点开就卡住了，然后就闪退了

**Comment by HiHeeko** [comment]
> @HiHeeko 从日志记录来看，是没有获取到直播间的播放信息，你查看的直播间ID是多少？其它的直播间（特别是观看人数多的直播间）是否有这个问题？

应该不是某个直播间的问题，而是所有直播都看不了（出现以上的错误）。我有两台电脑，目前看来只有在arm架构的那台上才有这个问题，x86的这台看直播没有问题。
闪退我这边也有，而且比较频繁（至少在arm那台上是这样的）。只要做出一些“让应用来不及反应”的行为就导致应用会卡死并闪退，比如打断过渡动画、刚打开独立视频播放页就立即关闭等。
另外，有的时候会出现“无限滑动”的问题，也就是使用鼠标滚轮/触摸手势翻动如视频推荐、动态等页面时，刚往下翻了一些的页面会立即反弹回来（此时内容并未翻到底）

**Comment by HiHeeko** [comment]
卡死后应用有概率无法再次启动，或者是启动后几秒内立即闪退。启动应用后有时虽然没有界面出现，但是任务管理器里有哔哩助理的进程，结束掉后再打开有一定几率恢复正常（如果这样还不行似乎只能重启Windows才能解决）

**Comment by theblueandblackcrow** [comment]
> > > @theblueandblackcrow 直播间观看闪退的话，不要犹豫，直接在设置里切到网页播放器吧
> > 
> > 
> > 不是观看时就闪退，是一点开就卡住了，然后就闪退了 但是在默认模式的情况下是可以用的，可能是bug
> > 以下是问题发现步骤： 1设置里选全屏的播放器观看 2任意点开直播间
> 
> 只要关闭**全屏模式**就可以正常观看直播了

在新版本（x.3.0）中，这个问题疑似有所好解了
我全屏能看直播了（但是没有长时间观看）

**Comment by HiHeeko** [comment]
@Richasy 我更新到了最新版本1.2402.3.0，直播无法观看的问题已经解决。：）
