### ISSUE TITLE
[Bug] BBDown 配置文件，权限不足无法保存

### ISSUE THREAD

**Issue by imgradeone** [Richasy/Bili.Copilot#30]
### Bug 描述

我尝试修改应用的 BBDown 配置文件，但由于配置文件被存放到 `WindowsApps` 目录下，我无法正常保存配置文件。

### 复现问题的步骤

```plain text
1. 打开应用
2. 随便选择一个视频播放
3. 展开信息栏
4. 展开“下载”，点击“打开配置”
5. 在 VS Code 修改配置文件
6. 保存
7. 报错，提权重试保存
8. 依旧报错
```

### 预期行为

在 VS Code 修改配置文件后应正常保存

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/30969327/b44d69c1-8851-4ee0-8809-187a5657deb7)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
已修复
