### ISSUE TITLE
[Bug] 在点击任务栏图标缩小窗口后切换到其他窗口后单击空格键还是会继续/暂停播放视频

### ISSUE THREAD

**Issue by sekurodesu** [Richasy/Bili.Copilot#302]
### Bug 描述

如题，此BUG仍旧存在

### 复现问题的步骤

```plain text
1、打开应用
2、打开视频
3、点击任务栏的图标最小化窗口
4、此时在其他窗口按空格键，会暂停/继续视频，导致在当前窗口的空格键失效
```

### 预期行为

希望修复此BUG

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

微软商店

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

windows10 21H2（Build 19044）

### 运行设备

桌面/台式机

### 备注

之前已经提交过此问题，但是被关闭

### 人人为我，我为人人

None

**Comment by lengran** [comment]
此 bug 仍然存在。

**Comment by Richasy** [comment]
已修复
