### ISSUE TITLE
[Bug] 打开视频会闪退

### ISSUE THREAD

**Issue by PrimedCube** [Richasy/Bili.Copilot#303]
### Bug 描述

<img width="1280" alt="Snipaste_2024-02-07_17-21-14" src="https://github.com/Richasy/Bili.Copilot/assets/52302600/125dd323-fbd1-4aaf-aba2-668dd572a067">
打开视频就闪退

### 复现问题的步骤

```plain text
打开视频
```

### 预期行为

打开视频正常播放

### 截图

事件查看器的报错，不知是否有用
![image](https://github.com/Richasy/Bili.Copilot/assets/52302600/a6d88962-035d-4647-9186-d3c1dd060f5e)
![image](https://github.com/Richasy/Bili.Copilot/assets/52302600/b27113c8-92e0-40c5-9161-b464906c1218)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [X] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2024-02-07.log](https://github.com/Richasy/Bili.Copilot/files/14192070/applog.2024-02-07.log)

### 人人为我，我为人人

None

**Comment by Ptilopsis01** [comment]
我也碰到了类似的情况，打开视频直接卡死，然后过一会闪退

**Comment by Richasy** [comment]
请在应用设置中尝试切换其他的播放器类型，实在不行就先用网页播放器

**Comment by Richasy** [comment]
已修复
