### ISSUE TITLE
动态无法加载

### ISSUE THREAD

**Issue by WcZaHr** [Richasy/Bili.Copilot#305]
### Bug 描述

点击动态，多切换几个新的动态就会出现这个bug

### 复现问题的步骤

```plain text
1、打开app
2、点击动态
3、多切换几个新的动态就会出现这个bug
```

### 预期行为

动态正常显示

### 截图

<img width="960" alt="bug" src="https://github.com/Richasy/Bili.Copilot/assets/119170543/4a092e9b-c4a7-4f4e-91d3-c3f4170d3c3d">

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

微软商店

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
与 #304 重复
