### ISSUE TITLE
[Feature] 高分屏哔哩助理支持

### ISSUE THREAD

**Issue by rayrenxiang** [Richasy/Bili.Copilot#307]
### 问题描述

视频窗口过于小了![屏幕截图 2024-02-09 134506](https://github.com/Richasy/Bili.Copilot/assets/95950587/2c23fd55-3725-43cf-944c-cbfefe6c4fb8)

### 描述解决方案

希望可以在设置选项中调整每页显示数量

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
哔哩助理本身自适应高分屏，如果觉得小，你可以考虑在系统设置中调整缩放哔哩
