### ISSUE TITLE
[Bug] 直播的画面颜色偏色

### ISSUE THREAD

**Issue by 1lin-lcs** [Richasy/Bili.Copilot#308]
### Bug 描述

看拜年祭的直播的画面颜色出现偏色，原生或FFmpeg都出现

### 复现问题的步骤

```plain text
选择一个直播进入就会发现，人的脸是蓝色的
```

### 预期行为

颜色应该是正确的（不知道怎么写这个）

### 截图

![屏幕截图 2024-02-09 203725](https://github.com/Richasy/Bili.Copilot/assets/82688117/b3421e1f-b6c8-40ce-b1d3-247c5ed8047b)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

windows 11 23H2(22631.3085)

### 备注

CPU是R5-6600H

### 人人为我，我为人人

None

**Comment by 1lin-lcs** [comment]
截图上面是浏览器中直播的正常画面，下面是应用的颜色不正常的画面

**Comment by 1lin-lcs** [comment]
我发现我用独显颜色就正常(RTX 3050)，用集显就会出现问题
![屏幕截图 2024-02-09 205534](https://github.com/Richasy/Bili.Copilot/assets/82688117/2cbc0029-ce4a-4d9a-aaa1-bfc4d308f4bf)
![屏幕截图 2024-02-09 205604](https://github.com/Richasy/Bili.Copilot/assets/82688117/7b3b4c13-c7f2-4905-a42d-cdb5190c63bd)

**Comment by 1lin-lcs** [comment]
AMD驱动是UWP的那个版本
![AMD](https://github.com/Richasy/Bili.Copilot/assets/82688117/1efdf448-6ae5-4b5d-b809-4ff34ee420b6)

**Comment by Richasy** [comment]
这个可能是硬件问题，暂时搁置

**Comment by 1lin-lcs** [comment]
好的
