### ISSUE TITLE
[Feature] 预启动功能

### ISSUE THREAD

**Issue by Tirehar** [Richasy/Bili.Copilot#312]
### 问题描述

希望添加类似哔哩的预启动功能，我个人习惯导致哔哩助理需要经常打开和关闭，但哔哩助理相比于哔哩不论是打开还是关闭的动画都不太流畅

### 描述解决方案

与哔哩相同

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
目前 WinAppSDK 尚不支持预启动
