### ISSUE TITLE
[Feature] 希望可以复制视频简介中的内容和更方便地跳转到网页端

### ISSUE THREAD

**Issue by TigerBest** [Richasy/Bili.Copilot#32]
### 问题描述

非常好的App，已给星星！
无法复制视频简介中的内容，且视频等内容不能方便快速地跳转到网页端（目前似乎只能从推荐、搜索结果列表中右键选择浏览器打开，播放器和详情页没有对应功能）。

### 描述解决方案

希望增加如下2个功能：
1. 能复制视频简介中的文字
2. 能更方便地跳转到视频、专栏、UP主页的网页端，如在播放器或详情页增加跳转按钮

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
右键点击视频卡片，可以选择在网页中打开
