### ISSUE TITLE
[Feature] 调整弹幕样式以及排版

### ISSUE THREAD

**Issue by AlbertQin2007** [Richasy/Bili.Copilot#320]
### 问题描述

现在哔哩助理的弹幕色彩个人感觉有点偏亮，且遇到亮色视频背景会不易看见，影响观感。
同时有出现弹幕重叠的情况，影响观感。

### 描述解决方案

调整弹幕饱和度以及包细黑边贴近网页端弹幕样式。
（图1为B站网页端某视频弹幕截图；图2为哔哩助理同视频弹幕截图，可以看出差别以及弹幕重叠）

<img width="414" alt="b" src="https://github.com/Richasy/Bili.Copilot/assets/70245766/97cdccb6-7b5a-4634-afd9-9627ca899a52">
<img width="480" alt="k" src="https://github.com/Richasy/Bili.Copilot/assets/70245766/a65e4b85-abc9-488a-b18e-2c045f14554b">

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你可以在弹幕设置中调整透明度

![image](https://github.com/Richasy/Bili.Copilot/assets/27713596/a7ad2fff-7f94-46d9-a50f-56256ccc0bfb)
