### ISSUE TITLE
[Bug] 直播弹幕bug

### ISSUE THREAD

**Issue by kofirelion** [Richasy/Bili.Copilot#327]
### Bug 描述

看直播时只有最开始进去页面有弹幕，随后就没有任何弹幕

### 复现问题的步骤

```plain text
打开直播就没弹幕
```

### 预期行为

有弹幕就行

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [X] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 日志记录

[applog.2024-02-23.log](https://github.com/Richasy/Bili.Copilot/files/14382822/applog.2024-02-23.log)

### 备注

无

### 人人为我，我为人人

None

**Comment by theblueandblackcrow** [comment]
这个遇到过，目前暂时的方法是，重新登陆可以解决
