### ISSUE TITLE
[Feature] 使首页能个性化修改排版

### ISSUE THREAD

**Issue by NalCol** [Richasy/Bili.Copilot#33]
### 问题描述

我不喜欢看B站热搜，然而每次打开应用都只能看热搜😂

### 描述解决方案

建议增加更多模块（复兴 Windows 10 磁贴？）
可以个性化增删显示的模块。
我用截图软件做了一个大致构型出来，在下方。
模块背景最好是Mica材质

### 备选方案

将主页热搜一整块设置成可以修改成其他信息流（如动态，热榜...）

### 附加信息

![image](https://github.com/Richasy/Bili.Copilot/assets/58576200/f60afd99-7c19-4c8c-b81b-c7d575afb43d)

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by KIITTID** [comment]
动态磁贴还是很吊的

**Comment by NalCol** [comment]
> 动态磁贴还是很吊的

作者把我的两个issue都关了，这个实际上不应该关的😂

**Comment by KIITTID** [comment]
开发者不会做这个功能了，我也给开发者建议过，比较动态磁贴被微软都砍了
