### ISSUE TITLE
[Feature] app内视频补帧实现可能性？

### ISSUE THREAD

**Issue by ibin7777** [Richasy/Bili.Copilot#342]
### 问题描述

之前经人推荐用了potplayer+svp的组合，为windows下的本地或直链视频播放自动插帧，效果非常好。但是b站视频如果用词办法，一是太麻烦，二是用外部播放器就没有弹幕了，一直想找一个合适的方案。

### 描述解决方案

请问类似svp这种的，将视频实时处理成两倍于原本帧数，或者同步到显示器帧数的功能，有无可能在助手app内实现呢？

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
助手内部暂时无此计划
