### ISSUE TITLE
[Feature] 播放器可以调整透明状态

### ISSUE THREAD

**Issue by TTvTT** [Richasy/Bili.Copilot#345]
### 问题描述

1）播放器控件不透明会挡住很多画面，在截图的时候尤为明显，
1）建议在暂停时候也可以像网页一样自动隐藏控件，
1）展开详情设计的也稍微大了点，希望改进。

### 描述解决方案

1）播放器控件不透明会挡住很多画面，在截图的时候尤为明显，
1）建议在暂停时候也可以像网页一样自动隐藏控件，
1）展开详情设计的也稍微大了点，希望改进。

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
与 #346 重复
