### ISSUE TITLE
[Feature] 关于播放器的一些小意见

### ISSUE THREAD

**Issue by TTvTT** [Richasy/Bili.Copilot#346]
### 问题描述

1）播放器控件不透明会挡住很多画面，在截图的时候尤为明显，
1）建议在暂停时候也可以像网页一样自动隐藏控件，
1）展开详情设计的也稍微大了点，希望改进。

### 描述解决方案

1）播放器控件不透明会挡住很多画面，在截图的时候尤为明显，
1）建议在暂停时候也可以像网页一样自动隐藏控件，
1）展开详情设计的也稍微大了点，希望改进。

### 人人为我，我为人人

None

**Comment by pheotry** [comment]
可以像potplayer学习一下，鼠标只有在底部和顶部控制栏信息栏那里移动控件才会出来，中间部分鼠标移动控件隐藏状态不变
