### ISSUE TITLE
[Bug] 播放视频过程中经常会整个应用卡死

### ISSUE THREAD

**Issue by ZaiDAP** [Richasy/Bili.Copilot#348]
### Bug 描述

播放视频过程中经常会整个应用卡死，无论是播放界面还是应用本身点击均无响应。此时如果点击播放界面的关闭也无法正常结束，后台还会接着播放视频。只有右键点击任务栏-退出才能正常结束应用。
这个问题碰到很长时间了，从很早的版本就一直有。

### 复现问题的步骤

```plain text
1、打开应用
2、点击播放视频
3、关闭播放界面
基本上看3~7个视频就会卡死

如录屏，前15s关闭的两个视频都是正常的，第16s打开的视频关闭后视频播放并未正常结束（还能听到声音），此时整个应用卡死无法操作。

应用已经是最新版本。
不知道为什么上传的视频github看是白屏，下载下来是正常的
```

### 预期行为

不要卡死

### 截图

https://github.com/Richasy/Bili.Copilot/assets/41657393/ab41a000-fc41-42fb-88fe-1b28bfb1d850

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

微软商店

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

应用卡死无日志记录

### 人人为我，我为人人

None

**Comment by pheotry** [comment]
有时候只是界面卡死了，视频照样播放，关闭界面，后台照样播放着声音

**Comment by ZaiDAP** [comment]
这是一封自动回复邮件。
已经收到您的来信，我会尽快回复。
                                                   ZaiDAP

**Comment by JalorPan** [comment]
> 有时候只是界面卡死了，视频照样播放，关闭界面，后台照样播放着声音

我也常遇到此类问题

**Comment by ForsakenDelusion** [comment]
我也经常这样

**Comment by Clorasun** [comment]
一样

**Comment by jerryc127** [comment]
一样

**Comment by lbyisme** [comment]
+1

**Comment by Richasy** [comment]
如果是使用将播放器窗口新建模式从单窗口调整至主窗口播放是否还有此类问题？

P.S. 顺便还想知道你是否开了网络代理？

**Comment by pheotry** [comment]
> 如果是使用将播放器窗口新建模式从单窗口调整至主窗口播放是否还有此类问题？
> 
> P.S. 顺便还想知道你是否开了网络代理？

我的是主窗口，未开代理。
有时候会出现这个问题，出现问题频率没他高

**Comment by Richasy** [comment]
尚不确定该问题的具体原因，只是初步判断可能和内存泄漏/网络有关，目前的回退方案是在设置中打开网页播放器，使用内建的 WebView2 播放视频

**Comment by JalorPan** [comment]
> 尚不确定该问题的具体原因，只是初步判断可能和内存泄漏/网络有关，目前的回退方案是在设置中打开网页播放器，使用内建的 WebView2 播放视频

已按此方法回退，1天使用目前尚未出现问题

**Comment by JalorPan** [comment]
> 尚不确定该问题的具体原因，只是初步判断可能和内存泄漏/网络有关，目前的回退方案是在设置中打开网页播放器，使用内建的 WebView2 播放视频

请问能否实现在未打开视频的情况下右键视频封面调用BBdown？因为WebView2播放窗口是没有BBdown下载支持的，这是否需要单独开一个Issue？

**Comment by ZaiDAP** [comment]
这是一封自动回复邮件。
已经收到您的来信，我会尽快回复。
                                                   ZaiDAP

**Comment by ZaiDAP** [comment]
这是一封自动回复邮件。
已经收到您的来信，我会尽快回复。
                                                   ZaiDAP

**Comment by NJYZ-96** [comment]
目前的最新版仍然在我的设备上频繁出现此问题，需要手动强制结束应用重新打开应用；

P.S. 顺便还想知道你是否开了网络代理？
（路由器透明代理，代理规则应该不会命中B站相关）

使用设备为Surface Pro（第五代）8G内存

**Comment by ZaiDAP** [comment]
这是一封自动回复邮件。
已经收到您的来信，我会尽快回复。
                                                   ZaiDAP
