### ISSUE TITLE
[Bug] 获取到的视频可能与选择的编码不同

### ISSUE THREAD

**Issue by NalCol** [Richasy/Bili.Copilot#35]
### Bug 描述

选择 H.264，但是获取的视频是 HEVC 编码
正好HEVC不能用（见 #26）

### 复现问题的步骤

```plain text
测试视频：BV1hF411o7HK
网页版有 H.264 编码的视频
但客户端获取不到
```

### 预期行为

获取到用户选择的编码的视频流

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/58576200/f8a7ca39-ccef-4a94-9d7e-71325090b801)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

Beta 22631.2129

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
设置项指的是优先选择，如果当前视频没有h264的流，那就会选择符合当前清晰度选择的第一个流

**Comment by NalCol** [comment]
> 设置项指的是优先选择，如果当前视频没有h264的流，那就会选择符合当前清晰度选择的第一个流

哈哈，但是HEVC用不了，这直接让视频看不了了🤣
