### ISSUE TITLE
[Bug] 直播有问题，转圈，无法播放

### ISSUE THREAD

**Issue by yzx4036** [Richasy/Bili.Copilot#351]
### Bug 描述

[Bug] 直播有问题转圈无法播放，或者只加载一帧和弹幕正常加载，但是画面就定格在这一帧无法播放。尝试过重新登录、清除缓存、切换原生和ffmpg、硬解软解，关闭弹幕都都无法解决，检查过没有开启翻墙和其他代理
版本1.2402.4.0

### 复现问题的步骤

```plain text
点击任何直播都一样的问题
```

### 预期行为

直播正常播放

### 应用来源

- [x] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

win11 23H2

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
回退方案是在设置中打开网页播放器来替代本机播放，在没有找到根本原因前，可以用此方法缓解问题
