### ISSUE TITLE
[Bug] 点开视频后立即暂停，APP闪退

### ISSUE THREAD

**Issue by richardfsw** [Richasy/Bili.Copilot#352]
### Bug 描述

如题。
当点开视频后，在视频的封面尚未完全消失时立即单击鼠标，暂停视频的播放，整个APP会闪退。

### 复现问题的步骤

```plain text
1、开启一个视频的播放；
2、立即单击鼠标，暂停播放。
```

### 预期行为

正常暂停，不闪退和卡顿。

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Win10 LTSC 2021 x64

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by ZhangYMGanix** [comment]
+1，在设置里勾选mpv播放（虽然效果不太理想）

**Comment by Richasy** [comment]
已修复
