### ISSUE TITLE
BBDown的下载接口消失

### ISSUE THREAD

**Issue by mxxyxy** [Richasy/Bili.Copilot#353]
# 截图
![image](https://github.com/Richasy/Bili.Copilot/assets/51052000/d39dea52-a416-4be4-9817-81cc44d2cef9)
# 说明
以前版本的哔哩助理看得到使用BBDown的下载接口，现在看不到了，是要将BBDown相关的exe文件放在指定地方么。

**Comment by mxxyxy** [comment]
![Uploading 批注 2024-03-21 224613.png…]()

**Comment by Richasy** [comment]
新版本提供了引导，暂时关闭此问题
