### ISSUE TITLE
[Feature] 哔哩助理和哔哩UWP的差距还是不小

### ISSUE THREAD

**Issue by PandaFiredoge** [Richasy/Bili.Copilot#356]
### 问题描述

哔哩助理冷启动至少三秒，哔哩UWP一秒都不到；哔哩UWP最小化自动挂起，完全不占用CPU和物理内存，只占用少量的页面文件，哔哩助理最小化之后仍然占用资源；哔哩助理点开一个消息通知还会跳转网页，哔哩UWP不用；哔哩UWP下架之前还能在Xbox上用。除了没磁贴，哔哩UWP完胜哔哩助理

### 描述解决方案

给哔哩UWP加入动态磁贴，并提供自定义磁贴内容的选项（类似iOS、Android的小组件）。给哔哩UWP的消息通知增加一个跳转到原视频的按钮。

### 备选方案

大幅优化哔哩助理的性能，并且减少需要跳转网页的模块

### 附加信息

无

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by o7451** [comment]
win10

**Comment by PandaFiredoge** [comment]
> win10

？

**Comment by Richasy** [comment]
创建哔哩项目的初衷是为了学习更新的开发框架，以此反哺我的工作，所以提供更好的体验或者更好的性能并不是首要追求的事情。你所说的冷启动时间以及后台占用的问题，这些属于开发框架层级的问题，目前应用无法修复。

**Comment by PandaFiredoge** [comment]
> ### 问题描述
> 
> 哔哩助理冷启动至少三秒，哔哩UWP一秒都不到；哔哩UWP最小化自动挂起，完全不占用CPU和物理内存，只占用少量的页面文件，哔哩助理最小化之后仍然占用资源；哔哩助理点开一个消息通知还会跳转网页，哔哩UWP不用；哔哩UWP下架之前还能在Xbox上用。除了没磁贴，哔哩UWP完胜哔哩助理
> ### 描述解决方案
> 
> 给哔哩UWP加入动态磁贴，并提供自定义磁贴内容的选项（类似iOS、Android的小组件）。给哔哩UWP的消息通知增加一个跳转到原视频的按钮。
> ### 备选方案
> 
> 大幅优化哔哩助理的性能，并且减少需要跳转网页的模块
> ### 附加信息
> 
> 无
> ### 人人为我，我为人人
> 
> 提出问题就是我对哔哩的期许

这只是一条无关紧要的评价，并不是急需改进的建议
