### ISSUE TITLE
[Bug] 另一种假死的方式

### ISSUE THREAD

**Issue by phoetry** [Richasy/Bili.Copilot#364]
### Bug 描述

点入一个视频，单击长按左上角的返回箭头，整个程序直接假死。

### 复现问题的步骤

```plain text
点入一个视频，单击长按左上角的返回箭头，整个程序直接假死。
```

### 预期行为

交互有不少问题，需改进

### 应用来源

- [ ] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

WIN10 22H2

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
暂时无法复现这个问题
