### ISSUE TITLE
[Bug] 进入软件无反应

### ISSUE THREAD

**Issue by Keima-Katsuragi** [Richasy/Bili.Copilot#365]
### Bug 描述

更新后进不去软件
![image](https://github.com/Richasy/Bili.Copilot/assets/89819632/fd808d77-dfed-4406-99b5-133927f37f77)

### 复现问题的步骤

```plain text
更新软件，进入软件
```

### 预期行为

修复bug

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Win11 23H2 22631.3374

### 运行设备

ARM64 设备

### 日志记录

进不去软件

### 人人为我，我为人人

我更擅长发现问题

**Comment by Keima-Katsuragi** [comment]
已关闭所有代理，尝试过流量和wifi

**Comment by Richasy** [comment]
1. 上个版本是否有此问题？
2. x64版本是否可以使用？

**Comment by Keima-Katsuragi** [comment]
上版本正常，x64版本未尝试

**Comment by zhblmy** [comment]
同样的问题

**Comment by Keima-Katsuragi** [comment]
2024/04/04 15:14:13.360|Error|An exception occurred while the application was running|Microsoft.UI.Xaml.LayoutCycleException: 无法找到与此错误代码关联的文本。

Layout cycle detected.  Layout could not complete.
2024/04/04 15:15:08.653|Error|An exception occurred while the application was running|Microsoft.UI.Xaml.LayoutCycleException: 无法找到与此错误代码关联的文本。

Layout cycle detected.  Layout could not complete.
2024/04/04 15:15:08.836|Error|An exception occurred while the application was running|System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Bili.Copilot.Libs.Provider.UpdateProvider.GetGitHubLatestReleaseAsync()
   at Bili.Copilot.ViewModels.AppViewModel.CheckUpdateAsync()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Comment by Keima-Katsuragi** [comment]
可能是这个
