### ISSUE TITLE
APP打不开

### ISSUE THREAD

**Issue by llhdxnq** [Richasy/Bili.Copilot#367]
从微软应用商店里面下载的，打不开

**Comment by Richasy** [comment]
请给出更详细的说明。是第一次就打不开还是其他的情况？

**Comment by llhdxnq** [comment]
> 请给出更详细的说明。是第一次就打不开还是其他的情况？

从微软商店第一次下载打开

**Comment by Richasy** [comment]
你的系统版本是什么？

**Comment by llhdxnq** [comment]
> 你的系统版本是什么？

版本	Windows 11 家庭中文版
版本	23H2
操作系统版本	22631.3374

**Comment by ZaiDAP** [comment]
同。应用商店版本，更新到 2404.1 之后就打不开了，一直是如下界面。
系统版本 22631.3296 (23H2)
![image](https://github.com/Richasy/Bili.Copilot/assets/41657393/b4fee443-201a-4548-9046-a5f5994ee5f1)

**Comment by Richasy** [comment]
新的版本应该修复了这个问题

**Comment by tangqiu0205** [comment]
依然打不开
![image](https://github.com/user-attachments/assets/7fbfe358-76c9-448a-8afc-2d8e6e6ad775)
![image](https://github.com/user-attachments/assets/cd8cd158-c414-486b-8948-6e32db9facac)

**Comment by ZaiDAP** [comment]
这是一封自动回复邮件。
已经收到您的来信，我会尽快回复。
                                                   ZaiDAP
