### ISSUE TITLE
[Bug] 性能问题

### ISSUE THREAD

**Issue by huoyan1231** [Richasy/Bili.Copilot#37]
### Bug 描述

使用中经常出现卡顿，延迟
目前还包括程序完全冻结问题

### 复现问题的步骤

```plain text
打开程序
播放视频片刻后退出
重复上一步骤数次
```

### 预期行为

程序性能保持稳定

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 25921.1000

### 运行设备

桌面/台式机

### 日志记录

[applog.2023-08-07.log](https://github.com/Richasy/Bili.Copilot/files/12274439/applog.2023-08-07.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
无法复现，不处理此类问题
