### ISSUE TITLE
[Bug] 不能自动切换成杜比视界HDR播放

### ISSUE THREAD

**Issue by nicebear1999** [Richasy/Bili.Copilot#370]
### Bug 描述

不是什么大问题。用（已经停止更新的）哔哩全屏播放杜比视界视频时，是会自动把我的笔记本显示器换成HDR模式，并且显示Dolby vision的标的。这个哔哔助理反倒不行了，可以正常打开杜比视界画质，但没有出现Dolby vision标，屏幕也没自动切换成HDR模式。不过我手动把Windows的HDR打开后，目测和用哔哩观看的效果差不多，可能实际上是正确解码了的哈哈哈。感谢大佬做的App。

### 复现问题的步骤

```plain text
设置全部默认。打开杜比视界的视频，并将画质调成杜比视界，然后全屏播放。
```

### 预期行为

像哔哩一样，自动把我的笔记本显示器换成HDR模式，并且显示Dolby Vision标。

### 截图

![IMG_1164](https://github.com/Richasy/Bili.Copilot/assets/49865965/4e12a80c-b594-4d6a-857e-ac5d95c94670)
第一张图是用哔哩。
![IMG_1166](https://github.com/Richasy/Bili.Copilot/assets/49865965/2720dc16-0260-43f4-82df-afce152e50ad)
第二张图是用哔哔助手。

### 应用来源

- [ ] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 (Build 22631)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by zk00790** [comment]
应该是WinUI3的问题，WinUI2就可直接显示杜比标志，换成WinUI3就不行

**Comment by Richasy** [comment]
由于播放器原因，暂时先移除杜比
