### ISSUE TITLE
直播

### ISSUE THREAD

**Issue by cnetion** [Richasy/Bili.Copilot#371]
### Bug 描述

直播无法观看

### 复现问题的步骤

```plain text
1.打开应用
2.点击直播频道
3.点击直播栏目
4.出现黑色界面。
```

### 预期行为

直播功能可以正常运行

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
如果直播不能正常播放，请在设置中调整播放器类型：设置->播放器控制 ->播放器类型
