### ISSUE TITLE
[Bug] 部分视频点击倍速播放不出现调节倍速选择的可选项

### ISSUE THREAD

**Issue by axy555** [Richasy/Bili.Copilot#372]
### Bug 描述

[Bug] 部分视频点击倍速播放不出现调节倍速选择的可选项（如1.5，2.0倍速），目测为多P视频会出现此问题

### 复现问题的步骤

```plain text
1.打开UWP应用
2.进入众合教育刑法视频（BV1NH4y127mt)
3.点击倍速选项
4.未出现调节倍速所应有的可选项如1.5,2.0倍速
```

### 预期行为

多P视频的调节倍速选项能正常显示并调节

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

win11应用商店

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by axy555** [comment]
<img width="728" alt="屏幕截图 2024-04-09 001529" src="https://github.com/Richasy/Bili.Copilot/assets/61405031/4bba6828-dd95-4482-9f27-fa1e42cde88e">

**Comment by axy555** [comment]
就图片中效果，只显示点击1x选项只显示播放速率不显示可选项

**Comment by pheotry** [comment]
同样遇到这个问题了

**Comment by fterremmunner** [comment]
我也遇到了，目前可行的解决办法是在设置-播放器控制中打开启用倍速滑动控件
