### ISSUE TITLE
[Bug] 聊天列表无法加载

### ISSUE THREAD

**Issue by clover-yan** [Richasy/Bili.Copilot#376]
### Bug 描述

聊天列表为空，并显示
```
Object reference not set to an instance of an object.
```

### 复现问题的步骤

```plain text
1. 打开应用
2. 打开消息界面
3. 等待聊天列表圈圈转完
```

### 预期行为

应当看到聊天列表。

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/56215525/ad5753aa-9084-4443-a61c-518c8a037113)

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

Microsoft Store

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2024-04-15.log](https://github.com/Richasy/Bili.Copilot/files/14973805/applog.2024-04-15.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
重新登录一下，或者在设置内展开”使用网页播放器“，验证一下网页登陆
