### ISSUE TITLE
[Bug] 更新后无法启动app

### ISSUE THREAD

**Issue by Ptilopsis01** [Richasy/Bili.Copilot#378]
### Bug 描述

如题，从github下载并更新至1.2404.3.0版本后，无法启动应用

### 复现问题的步骤

```plain text
如上所述
```

### 预期行为

应用正常启动

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

win11 23h2 22631.3520

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
卸载后重新安装试试？

**Comment by Ptilopsis01** [comment]
可以了，不过这样设置项得重设了

**Comment by Richasy** [comment]
1.2404.3.0 已被设置为预览版，后续更新会修复
