### ISSUE TITLE
[Bug] 程序假死

### ISSUE THREAD

**Issue by huoyan1231** [Richasy/Bili.Copilot#379]
### Bug 描述

程序假死，无法操作，只能使用任务管理器关闭

### 复现问题的步骤

```plain text
好像还不能稳定复现，我再用用（
```

### 预期行为

程序正常运行

### 应用来源

- [ ] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [X] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2024-04-17.log](https://github.com/Richasy/Bili.Copilot/files/15007938/applog.2024-04-17.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by lithiumleeow** [comment]
同样问题

**Comment by kirafreedom** [comment]
从很早的版本就经常假死，每次都只能在托盘右键关闭重新打开

**Comment by PandaFiredoge** [comment]
WindowsAppSDK实在太烂了，傻叉阿三不解释

**Comment by Richasy** [comment]
已修复
