### ISSUE TITLE
[Bug] 播放视频的时候，选择相关视频，卡死

### ISSUE THREAD

**Issue by pdxrlj** [Richasy/Bili.Copilot#381]
### Bug 描述

 播放视频的时候，选择相关视频，卡死

### 复现问题的步骤

```plain text
1. 打开一个视频
2. 选择相关联的视频
3. 直接卡死
```

### 预期行为

不卡死

### 应用来源

- [ ] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 人人为我，我为人人

我更擅长发现问题

**Comment by pan-Z2l0aHVi** [comment]
+1
