### ISSUE TITLE
[Bug] 软件无法登录

### ISSUE THREAD

**Issue by JayJiang511** [Richasy/Bili.Copilot#385]
### Bug 描述

但扫完码后，显示“登陆失败，请稍后重试”，网页登陆也没有效果，当我用密码或者扫码的登陆网页成功后，软件没有下一步进程。

### 复现问题的步骤

```plain text
1.打开应用
2.扫码
3.发现问题“登录失败，请稍后重试”（网页可以登录，但软件没有进一步进程）
```

### 预期行为

修复？！

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/104381501/acc18b34-574f-4a59-9d42-684867bec2cc)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by a254476321** [comment]
我好像遇到过类似，通过覆盖安装会这样，卸载重装就好了

**Comment by JayJiang511** [comment]
先前我在**Microsoft Store**上进行的安装，无论通过那种方式进行的登陆都无法奏效；我刚才卸载掉，尝试了**侧加载**的方式，但还是_登录失败,请稍后重试_...

**Comment by JayJiang511** [comment]
先前我在**Microsoft Store**上进行的安装，无论通过那种方式进行的登陆都无法奏效；我刚才卸载掉，尝试了**侧加载**的方式，但还是_登录失败,请稍后重试_...
