### ISSUE TITLE
[Bug] 集显使用原生播放器视频发白，打开很慢

### ISSUE THREAD

**Issue by mwnu** [Richasy/Bili.Copilot#397]
### Bug 描述

CPU：I7-1065G7，带1G集显
使用原生播放器模式，视频发白，NVIDIA独显则正常，换成FFmpeg播放器也正常。
如果换到FFmpeg，则视频打开的速度会慢很多，平均大概需要四五秒，感觉也更耗电。

### 复现问题的步骤

```plain text
用集显笔记本原生播放模式试一下
```

### 预期行为

正常颜色

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

Windows store

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
我这边不能保证所有的播放模式都能够在各种设备上正常工作，所以才提供了这么多的播放方式，请选择一种能正常观看的模式使用
