### ISSUE TITLE
[Bug] 扫码登录无法登录，网页登录也无法进入客户端

### ISSUE THREAD

**Issue by gsvuo** [Richasy/Bili.Copilot#404]
### Bug 描述

如题，打开客户端扫码登录会提示：登录失败，请稍后重试。
![PixPin_2024-05-30_18-31-42](https://github.com/Richasy/Bili.Copilot/assets/138410655/d28b4ab1-ba04-4846-81c6-da8a19fb02b6)

 然后尝试使用网页登录，会进入如下图界面，只能很小窗口看正常网页版的B站，点左上角返回会重新回到登录界面，点右上角的X会直接关闭客户端
![PixPin_2024-05-30_18-32-06](https://github.com/Richasy/Bili.Copilot/assets/138410655/949a1178-a1b6-431f-af7f-3e0c2690230d)

已经尝试很多天了，始终无法正常登录进入主界面使用。

### 复现问题的步骤

```plain text
新安装，打开应用，扫码，必然是登录失败的，起初以为号有问题，尝试过几个B站账号之后发现都是登录不了。
```

### 预期行为

希望能解决登录问题，或者说可以不用登录也能进主界面看视频就好。

### 应用来源

- [ ] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

win10 22H2

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by AronnaxM** [comment]
参考一下 Issue 306 : https://github.com/Richasy/Bili.Copilot/issues/306

**Comment by Richasy** [comment]
已修复
