### ISSUE TITLE
[Bug] 鼠标滚轮失效

### ISSUE THREAD

**Issue by zxrone** [Richasy/Bili.Copilot#41]
### Bug 描述

鼠标滚轮失效，滚动不了页面，但是通过在全屏播放视频的时候打开的视频详情页和个人空间可以

### 复现问题的步骤

```plain text
一安装就有了
```

### 预期行为

请修复它

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 10 2004

### 运行设备

桌面/台式机

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
在 Windows 10 19041 中进行了测试，无法复现该问题。
如果问题始终存在，请使用哔哩哔哩官方应用或者网页版，未来哔哩会逐步停止对win10的支持
