### ISSUE TITLE
[Bug] 1.2406.3.0 版本因证书问题无法安装

### ISSUE THREAD

**Issue by Haoyi-Han** [Richasy/Bili.Copilot#414]
### Bug 描述

在本机已安装旧版本应用的情况下，直接运行 `.msix` 安装程序，遇到如下问题：
<img width="488" alt="ApplicationFrameHost_rfCGyhxsjY" src="https://github.com/Richasy/Bili.Copilot/assets/54799247/d5f7c7bb-2d5f-4663-86e1-49851a942776">

上述问题在手动将证书安装到受信任的根证书颁发机构后依然存在。

尝试以管理员身份直接运行 `install.ps1`，依然无法实现安装，遇到如下问题：
<img width="735" alt="pwsh_qrt20gxfN3" src="https://github.com/Richasy/Bili.Copilot/assets/54799247/e33ccc99-adf3-405f-8898-deab429776b9">

上述问题在卸载旧版本应用后复现依然存在。

### 复现问题的步骤

```plain text
参见 Bug 描述。
```

### 预期行为

实现正常安装过程的解决办法或可能的漏洞修复。

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 (Build 22631)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
1.2406.3.0 版本更新了开发证书（原证书即将过期），所以需要重新安装证书。

请使用 `Windows PowerShell` 来运行 install.ps1，而不是 PowerShell 7

**Comment by Haoyi-Han** [comment]
感谢您的回复，但是改用 Windows Powershell 运行 `install.ps1` 后问题未能解决，详细运行截图和日志截图如下：
<img width="880" alt="ConEmu64_loG79c4wha" src="https://github.com/Richasy/Bili.Copilot/assets/54799247/08674301-4815-485f-988e-1cec43a5fcb8">

经切换使用或不用管理员模式复现得到的结果相同。

**Comment by Richasy** [comment]
我试了3台设备，均无法复现这个问题。我不确定是不是下载的包有损坏，请重新下载后，右键 install.ps1，然后选择使用 PowerShell 运行。

如果依然不行，请等待微软商店版本审核通过（预计下周一）
