### ISSUE TITLE
[Bug] 视频加载异常 多屏幕行为异常

### ISSUE THREAD

**Issue by saigyouji-chief** [Richasy/Bili.Copilot#419]
### Bug 描述

1.打开程序随意点击一个视频程序便进入未响应状态持续一段时间后结束未响应并正常显示所点击的视频内容，随后点击其他的新视频则能立刻显示，点击X关闭程序重新启动则又会卡死，该问题已在我多个硬件及系统环境下实现100%复现，未响应时间随硬件性能的下降而增加且没有日志内容
2.多屏幕环境下使用单窗口模式将窗口置于副屏后关闭，断开副屏连接后重新打开窗口仍旧显示在已经不存在的副屏中且没有任何办法将其移回主屏

### 复现问题的步骤

```plain text
1.打开应用
2.点击视频
3.应用未响应
```

### 预期行为

1.打开应用
2.点击视频
3.立刻显示视频内容

### 截图

https://github.com/Richasy/Bili.Copilot/assets/39905675/7dd11e88-59ef-48fa-93da-1e996dd60717

### 应用来源

- [ ] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 (Build 22635.3858)

### 运行设备

桌面/台式机, 桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
已修复
