### ISSUE TITLE
[Feature]动态页面显示专栏

### ISSUE THREAD

**Issue by MC-Nirvana** [Richasy/Bili.Copilot#421]
### 问题描述

希望能增加在动态页面显示专栏的功能。现在的动态只能显示普通动态和视频。没有专栏内容

### 描述解决方案

动态页面显示关注UP更新的专栏

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
正在使用 TV 生成的令牌访问B站，无法从动态 API 中获取专栏动态
