### ISSUE TITLE
[Feature] 在网页播放器模式中增加油猴脚本功能

### ISSUE THREAD

**Issue by Zpcola** [Richasy/Bili.Copilot#426]
### 问题描述

是否可以通过对油猴脚本的支持来进一步增加网页模式播放体验,使用户能添加额外的油猴脚本来增强功能和美化bilibili

### 描述解决方案

往里面塞个暴力猴?

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
新版本已关闭网页播放器功能
