### ISSUE TITLE
[Bug] 有一部分直播间打不开，一直黑屏加载

### ISSUE THREAD

**Issue by JosephAU** [Richasy/Bili.Copilot#429]
### Bug 描述

弹幕可以显示，但是没有画面。有些直播间up主的头像也加载不出来，ip在海外

### 复现问题的步骤

```plain text
打开直播tab，点进直播间，一直在黑屏加载，弹幕可以显示
```

### 预期行为

能够看到直播画面

### 截图

![屏幕截图 2024-08-04 083444](https://github.com/user-attachments/assets/6c42bfba-5daa-4b50-b317-f7e83546396b)

### 应用来源

- [ ] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

微软商店

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 (Build 22631)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
已修复
