### ISSUE TITLE
[Bug] HEVC/H.265时播放视频显示杂乱和绿屏

### ISSUE THREAD

**Issue by ZhaoShanGeng** [Richasy/Bili.Copilot#43]
### Bug 描述

播放器设置选择HEVC/H.265时无法播放，显示杂乱和绿屏，重启应用和设备后无改变。已经安装HEVC插件，原哔哩选择HEVC/H.265时可正常播放，网页版b站选择HEVC时可正常播放。

### 复现问题的步骤

```plain text
1.在设置中将播放器控制选择解码器编号为选择HEVC/H.265
2.播放任意视频
```

### 预期行为

正常播放，没有卡顿、绿屏等现象

### 截图

HEVC/H.265
![{F79FEBA4-C7A1-4dce-AF66-C8CFF20EF492}](https://github.com/Richasy/Bili.Copilot/assets/121561568/5dedf9d0-bb92-46c4-99f9-00a68206ae4e)
AVC/H.264
![{ED4B46A6-355A-441c-A3B1-395AA01B7C83}](https://github.com/Richasy/Bili.Copilot/assets/121561568/394f0031-61c4-413e-9daf-5fe1a821e14f)

### 应用来源

- [ ] Github
- [X] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2023-08-07.log](https://github.com/Richasy/Bili.Copilot/files/12279701/applog.2023-08-07.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by ZhaoShanGeng** [comment]
补充：可能与默认使用FFmoeg播放器，取消原生的播放器类型有关。
发现在哔哩中选择FFmpeg播放，硬解时会出现画面不动，进度条到终点，声音正常播放的问题，即只有声音正常播放，画面卡住，进度条一下跳至结尾不动的问题。选择原生播放器没有问题。
在哔哩助理中则是声音正常，进度条正常，画面错误。

**Comment by NalCol** [comment]
这与我的 #26 是相同的issue
