### ISSUE TITLE
[Bug] 请求推荐视频失败

### ISSUE THREAD

**Issue by HMwancheng** [Richasy/Bili.Copilot#437]
### Bug 描述

![image](https://github.com/user-attachments/assets/3ff33b8b-05c2-4734-b0ba-78be5e909207)

### 复现问题的步骤

```plain text
打开即可
```

### 预期行为

正常使用

### 截图

![image](https://github.com/user-attachments/assets/f5a82d53-6840-49d6-9383-d9352b2a5bf9)
![image](https://github.com/user-attachments/assets/8a44c201-84ed-41b5-a384-d6d45a1fe39c)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 其它系统版本

win 11 23H2

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-08-22.log](https://github.com/user-attachments/files/16703587/applog.2024-08-22.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
已修复

**Comment by HMwancheng** [comment]
![image](https://github.com/user-attachments/assets/30de6ed0-b2e9-46fc-9961-9abf00e98502)
貌似还是不行

**Comment by Richasy** [comment]
在商店更新下版本

**Comment by HMwancheng** [comment]
![image](https://github.com/user-attachments/assets/0e73bdec-ec70-4ade-a73a-381efccfd72d)
yi'shi已是最新版本（GitHub）

现在
尝试一下商店的试试

**Comment by HMwancheng** [comment]
![image](https://github.com/user-attachments/assets/12cdb161-b123-4c6a-ab2d-19dfca63b1e0)
原来能同时存在多个版本QAQ
