### ISSUE TITLE
[Feature] 需要Arm 32支持

### ISSUE THREAD

**Issue by zuichen123** [Richasy/Bili.Copilot#438]
### 问题描述

我想使用我的Windows10Mobile手机(lumia830)看bilibili,官方UWP已经失效,这个机子使用的soc是晓龙400,arm32位,因此无法使用哔哩助理

### 描述解决方案

可否构建arm32版本发行版

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
哔哩助理基于 WindowsAppSDK 开发，目前仅支持桌面操作系统
