### ISSUE TITLE
[Bug] 全屏时内容一直在左上角

### ISSUE THREAD

**Issue by MangMax** [Richasy/Bili.Copilot#445]
### Bug 描述

全屏无法正常使用，内容会在左上角

### 复现问题的步骤

```plain text
1.打开应用
2.随便点击一个视频
3.全屏视频
```

### 预期行为

视频全屏

### 截图

![image](https://github.com/user-attachments/assets/3108fcfe-8fe6-44cb-8415-d77c4a8f776a)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

不知道为啥，没有生成日志文件，也是bug？

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这个情况多发生于AMD GPU，
请在应用设置/播放行为中切换为原生播放器

**Comment by MangMax** [comment]
好像确实，改用独显打开就行了
