### ISSUE TITLE
[Feature] 建议增加BBDown的更多功能支持

### ISSUE THREAD

**Issue by xiaolan610** [Richasy/Bili.Copilot#446]
### 问题描述

想要下载收藏夹却发现无法一键下载；
想要下载视频的音频却发现无法下载;
想要下载视频的字幕却发现无法下载;

### 描述解决方案

在收藏夹页面加一个含有BBDown系列功能的按钮；
在BBDown功能列表增加“下载音频”功能；
在BBDown功能列表增加“下载字幕”功能；

### 备选方案

没有，况且我说的很难吗？

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
应用内置的BBDown只提供基础的视频下载功能，暂不考虑添加额外的支持。
如果你需要自定义下载，可以在设置的下载设置区块中打开调用外部BBDown，并将下载改为仅复制命令，然后自行下载需要的内容
