### ISSUE TITLE
[Feature] （再提一次）更多倍数

### ISSUE THREAD

**Issue by xiaolan610** [Richasy/Bili.Copilot#448]
### 问题描述

想更快/更慢地放视频

### 描述解决方案

增加更多倍数

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
过快或者过慢的速率会引发比较严重的丢帧，造成播放的卡顿。目前以0.5为间隔，0.5-3的速率区间有着相对比较稳定的播放效果。
目前不考虑提供更多的倍数选项
