### ISSUE TITLE
[Bug] 最新版本使用内置的下载器下载无效。

### ISSUE THREAD

**Issue by sjrmdtjws2233** [Richasy/Bili.Copilot#449]
### Bug 描述

再点击下载后（账号是大会员，下载1080p60的视频和480p的视频都无效），命令行界面闪了一下然后快速消失。进入文件管理器查看下载目录，目录中无想要下载的视频文件。

### 复现问题的步骤

```plain text
1. 打开应用
2.任意选择一个视频
3.选择任意清晰度进行下载
4.在下载文件夹中查看
```

### 预期行为

下载成功。

### 截图

![屏幕录制 2024-08-30 125933](https://github.com/user-attachments/assets/44c2f25f-7883-426e-b895-b2487e49e3ad)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 日志记录

2024/08/30 13:10:35.650|Error|core: libdav1d: Unknown Metadata OBU type 6

### 备注

附带一个小建议，希望将投币图标改动成官方样式。

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
目前信息有限，不足以判断问题原因，但感觉跟系统环境有关。
你可以尝试先根据 [BBDown](https://github.com/nilaoda/BBDown?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B) 说明，在本机安装 BBDown，然后运行看看能否顺利使用。
如果外部安装的 BBDown 可以使用，而内部不行，可以在设置的下载设置中打开调用外部 BBDown 的选项

**Comment by sjrmdtjws2233** [comment]
> 目前信息有限，不足以判断问题原因，但感觉跟系统环境有关。 你可以尝试先根据 [BBDown](https://github.com/nilaoda/BBDown?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B) 说明，在本机安装 BBDown，然后运行看看能否顺利使用。 如果外部安装的 BBDown 可以使用，而内部不行，可以在设置的下载设置中打开调用外部 BBDown 的选项

单独安装bbdown还是闪退，看来不是软件问题，我电脑的问题。
