### ISSUE TITLE
[Bug] 无法搜索到部分视频和UP主

### ISSUE THREAD

**Issue by St-Cai** [Richasy/Bili.Copilot#45]
### Bug 描述

搜索《拍摄日常｜三分钟沉浸式体验音乐区up主拍cover的一天》或者BV号BV1qV4y1e7Z2均无法找到相应视频；搜索用户名“一周一会”无法找到该UP主，且搜索结果共有19位用户，而手机端和网页端均为36位。

### 复现问题的步骤

```plain text
应用首页搜索框搜索视频BV1qV4y1e7Z2或用户名“一周一会”。
```

### 预期行为

修复BUG。

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/55645331/5b572ab8-b9af-4ffe-976a-dcc697e0502f)
![image](https://github.com/Richasy/Bili.Copilot/assets/55645331/acb24f7c-22a2-4645-85cf-916b77179438)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 备注

1.2308.2.0版本仍可复现。

### 人人为我，我为人人

我更擅长发现问题

**Comment by Aurora-Simba** [comment]
是否为十六位uid用户

**Comment by St-Cai** [comment]
> 是否为十六位uid用户

是

**Comment by PandaFiredoge** [comment]
> > 是否为十六位uid用户
> 
> 是

无解。
