### ISSUE TITLE
应用闪退报告

### ISSUE THREAD

**Issue by Colin-Y0470** [Richasy/Bili.Copilot#450]
### Bug 描述

在性能部分限制下，当以“直播”一栏进入应用时，应用极易发生闪退。

### 复现问题的步骤

```plain text
1.在电源管理中打开某一计划（通常是平衡）的高级电源设置
2.将最大处理器状态设置在100%以下的的任意一值（通常99%即可复现问题）
3.保存修改并退出
4.打开应用
5.点击左侧“直播”一栏
6.退出应用
7.再次打开应用
8.应用出现闪退，发生概率极高，x64和arm64下均可复现
```

### 预期行为

希望可以修复这个问题，因为以其他栏目进入似乎不会出现这个问题。（我只试过“流行”和“动态”不会，其他除“直播”外没有试过）

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你是从商店下载的？目前新版本应该还没有发布，你可以进入设置看下你安装的版本是不是 1.2406.3.0？最新的版本应该是 2.2409.1.0，可以在下午两三点左右再更新一下

**Comment by Colin-Y0470** [comment]
嗯，事实上我的版本是1.2406.4.0。我试着更新一下。


来自 MEIZU 21

-------- 原始邮件 --------
发件人：Richasy ***@***.***>
时间：2024年8月30日 13:20
收件人："Richasy/Bili.Copilot" ***@***.***>
抄送：Colin-Y0470 ***@***.***>,Author ***@***.***>
主题：Re: [Richasy/Bili.Copilot] 应用闪退报告 (Issue #450)

**Comment by Richasy** [comment]
新版本是否还有这个问题？

**Comment by Richasy** [comment]
无响应，暂时关闭该问题，如果问题依然存在，请再打开
