### ISSUE TITLE
[Feature] 提供更改右侧栏默认打开选项。

### ISSUE THREAD

**Issue by sjrmdtjws2233** [Richasy/Bili.Copilot#451]
### 问题描述

<img width="1327" alt="屏幕截图 2024-08-30 132137" src="https://github.com/user-attachments/assets/58b9975c-eb04-46f2-8320-4995995aee23">
圈出的部分默认打开视频列表，且无法更改。

### 描述解决方案

在设置中，增加可更改选项。

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
侧边栏的内容不是固定的，会根据视频信息进行调整（有时是合集，有时是分P，有时是播放列表），目前暂无计划对此进行自定义支持，会引入额外的复杂度，增加维护成本。
