### ISSUE TITLE
[Feature] 以前版本与小幻助理联动的功能大佬有没有计划补回？

### ISSUE THREAD

**Issue by sjrmdtjws2233** [Richasy/Bili.Copilot#458]
### 问题描述

https://www.bilibili.com/video/av359469727，这期视频里哔哩助理和小幻助理联动的功能【9：58~15：46】有没有计划添加回v2版本的小幻助理。

### 描述解决方案

添加回来

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
有计划，这次重构的主要目的之一就是实现应用联动。但是关于AI的部分会直接内置在app里，这个会在以后更新
