### ISSUE TITLE
[Bug] 我的标题 无法下载视频

### ISSUE THREAD

**Issue by gwx90** [Richasy/Bili.Copilot#460]
### Bug 描述

点击下载视频后，出现了一个窗口，然后该窗口马上就自己关闭了，之后的下载无反应

### 复现问题的步骤

```plain text
1.进入应用
2.随便打开一个视频
3.点击下载视频
4.出现问题
```

### 预期行为

正常下载视频

### 截图

https://github.com/user-attachments/assets/4ce0adc5-11bb-4492-ab58-54a2527df5c6

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-08-31.log](https://github.com/user-attachments/files/16820213/applog.2024-08-31.log)

### 备注

版本	Windows 11 家庭中文版 版本号	23H2 安装日期	‎2022/‎9/‎28 操作系统版本	22631.4112 体验	Windows Feature Experience Pack 1000.22700.1034.0

### 人人为我，我为人人

None

**Comment by Colin-Y0470** [comment]
是的，我也在升级后遇到了同样的问题。哔哩助理无法正常调用BBdown下载视频，这个问题在我的Windows 10 21H2 x64和Windows 11 23H2/24H2 arm64上都出现了。希望能尽快修复。

**Comment by 73410** [comment]
实测，如果你电脑上有bbdown的话，在设置里打开下载时外部的bbdown就能正常用了

**Comment by Colin-Y0470** [comment]
@73410 感谢你的回复帮助，这下确实可以了。
