### ISSUE TITLE
[Bug] 播放视频切换全屏时卡死

### ISSUE THREAD

**Issue by KayStud10** [Richasy/Bili.Copilot#461]
### Bug 描述

播放视频时短时间内反复切换全屏会卡死

### 复现问题的步骤

```plain text
程序在播放视频时如果短时间内切换到全屏再切回来，然后再切换到全屏的话会卡死，一会后程序就会强制关闭
```

### 预期行为

希望能修复

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你正在用的是原生播放器还是 MPV 播放器？

**Comment by KayStud10** [comment]
使用原生播放器，h265编码
硬件：ryzen2700/5600xt/16g内存

________________________________

**Comment by Richasy** [comment]
暂时不能复现这个问题，你可以切换到 h264 看看
