### ISSUE TITLE
[Bug] 键盘快捷键调节音量不显示具体音量值

### ISSUE THREAD

**Issue by RickyZhu-420** [Richasy/Bili.Copilot#465]
### Bug 描述

视频播放时使用上下方向键调节音量不会像先前版本显示具体音量值。不过音量的确按预期改变

### 复现问题的步骤

```plain text
1. 打开应用
2. 点进任意视频并开始播放
3. 按上下键调节音量
```

### 预期行为

此时应在视频画面适当处显示当前的音量百分比（先前是左下角来着？）

### 截图

截不到键盘表现，就没图了

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这是预期行为，新版本不再进行数值提示，音量应该由听觉决定是否合适
