### ISSUE TITLE
[Bug] 视频进度条在调节设置时消失

### ISSUE THREAD

**Issue by RickyZhu-420** [Richasy/Bili.Copilot#466]
### Bug 描述

视频进度条上有许多带下拉菜单的设置按钮，比如音量和字幕设置。在点击这些按钮后，进度条会在一秒内消失。

### 复现问题的步骤

```plain text
1. 打开应用
2. 打开任意视频
3. 鼠标点击进度条上的带有二级菜单的按钮，比如音量
```

### 预期行为

进度条不应消失，而是持续显示。这样可以保证当需要依次调节一个以上的设置时不用额外点击空白处重新显示进度条界面。
并且也可以做到在此时单次点击控件外的内容即可切换暂停状态
![image](https://github.com/user-attachments/assets/a9093818-9e6b-4ae2-9413-b0a4f471ecd0)

### 截图

![image](https://github.com/user-attachments/assets/9be7f040-5ffb-440c-aed4-ffc9d54bd8eb)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这是预期行为，目的是保持专注
