### ISSUE TITLE
[Bug] 不定期弹窗报错

### ISSUE THREAD

**Issue by admandt** [Richasy/Bili.Copilot#468]
### Bug 描述

播放视频到一半有大概率弹窗报错，只能点击退出应用。
![1](https://github.com/user-attachments/assets/e72a1b22-d739-4994-b1f3-ad750791065d)
播放器类型设置为原生，画质设置为 高清1080P优先。解码偏好为AVC/H.264
设备型号为CPU i7 3632qm 核显。
app版本为2.2409.1.0

### 复现问题的步骤

```plain text
1.打开应用，随便点个视频播放
2.播放时随机弹窗退出。
```

### 预期行为

解决报错就好啦。

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

2024/08/30 21:50:42.950|Error|core: after creating texture: OpenGL error INVALID_VALUE.
|
2024/08/30 21:50:43.462|Error|core: after creating texture: OpenGL error INVALID_VALUE.
|

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
尝试更新下显卡驱动？

**Comment by admandt** [comment]
> 尝试更新下显卡驱动？

三代处理器的核显，，，早已没有新驱动了。在哔哩助手上一个版本的时候是没有这个问题的。

**Comment by Richasy** [comment]
你随附的日志显示的 OpenGL 是属于 mpv 的报错信息，原生播放器如果没有日志记录，那可能是 media foundation 发生了内部异常，这个我很难处理。
如果崩溃频繁发生，那么并不建议在当前设备上使用哔哩助理

**Comment by admandt** [comment]
> 你随附的日志显示的 OpenGL 是属于 mpv 的报错信息，原生播放器如果没有日志记录，那可能是 media foundation 发生了内部异常，这个我很难处理。 如果崩溃频繁发生，那么并不建议在当前设备上使用哔哩助理

日志文件内只有这两条OpenGL的信息，您默认了使用MPV，我是在出现使用MPV下黑屏的情况下才转为原生。
既然如此，我先选择安装上一个版本试试，期待您的下一个版本。
