### ISSUE TITLE
能否在软件内的设置界面增加夜间模式？

### ISSUE THREAD

**Issue by sekurodesu** [Richasy/Bili.Copilot#47]
### 问题描述

如题，能否在软件内的设置界面增加夜间模式？

### 描述解决方案

就和介绍视频里的那种一样，现在默认是白色模式。

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
这个是跟着系统主题走的，暂时没有添加应用主题的打算这个在WinUI3下面还有一点bug
