### ISSUE TITLE
[Feature] 應用窗口播放器全屏

### ISSUE THREAD

**Issue by AkazaRenn** [Richasy/Bili.Copilot#470]
### 问题描述

最近的更新之後發現應用窗口播放器全屏功能被刪除了，現在只能選擇懸浮小窗口或全屏，對豎屏不太友好。

### 描述解决方案

希望可以將之前的應用窗口播放器全屏功能添加回來。

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
下个版本更新
