### ISSUE TITLE
[Bug] 触控进全屏播放界面下有白色空缺

### ISSUE THREAD

**Issue by wen-wen520** [Richasy/Bili.Copilot#471]
### Bug 描述

在视频详情界面。触屏点击全屏按钮。屏幕下方会出现白色空缺。

### 复现问题的步骤

```plain text
1. 打开应用
2. 随机选择一个视频
3. 点击视频，进入视频详情页
4. 触摸点击全屏按钮
5. 下方出现白色空缺
```

### 预期行为

进入后，下方无白色空缺。如附件正常情况。

### 截图

触摸点击：
![Screenshot 2024-08-31 133757](https://github.com/user-attachments/assets/58bc8fa0-7380-4145-8e11-7bc48335aec6)

正常情况：
![Screenshot 2024-08-31 133808](https://github.com/user-attachments/assets/cf387f08-77ea-4830-b003-bc18d3788c35)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-08-31.log](https://github.com/user-attachments/files/16825706/applog.2024-08-31.log)

### 备注

经过测试，其白色空缺位置与为触控优化的任务栏的位置相当。

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
看下新版本（2.2409.2.0） 是否还有这个问题？

**Comment by FFDVDGD** [comment]
> 看下新版本（2.2409.2.0） 是否还有这个问题？

即使非触控也有此问题，版本为2.2409.2.0，系统Windows 11 24H2 (Build 26120.1542)，显卡AMD RX580

**Comment by Richasy** [comment]
你用的是原生的播放器还是 mpv？

**Comment by Richasy** [comment]
我试了几个设备，并没有复现这个问题。这个可能和系统有关

**Comment by Srythm** [comment]
surface go2 Windows 10 19044.4780 App版本2.2409.2.0 遇到同样问题

**Comment by Starfallan** [comment]
Surface Pro7 win11 22631.4112 App版本2.2409.3.0未复现

**Comment by Walkar66** [comment]
> 看下新版本（2.2409.2.0） 是否还有这个问题？

我提的issues为什么被删掉了，我和他的不是一个错误啊，而且我感觉我这个错误应该是比较广泛的

**Comment by Richasy** [comment]
最新版本 2.2409.5.0 应该已经修复了这个问题
