### ISSUE TITLE
[Bug] 清晰度列表无杜比视界选项

### ISSUE THREAD

**Issue by wen-wen520** [Richasy/Bili.Copilot#472]
### Bug 描述

在受杜比视界支持的设备上。
清晰度列表无杜比视界选项。

### 复现问题的步骤

```plain text
1. 打开应用
2. 点击杜比视界视频进入视频详情页
3. 点击 清晰度列表
4. （BUG）无杜比视界选项
```

### 预期行为

有杜比视界选项

### 截图

![Screenshot 2024-08-31 135049](https://github.com/user-attachments/assets/a39894bf-5e05-4359-82d9-8702e1bde9a4)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-08-31.log](https://github.com/user-attachments/files/16825723/applog.2024-08-31.log)

### 备注

设备：
Dolby Vision IQ™ support

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
目前对杜比的支持存在难以解决的问题，所以移除了，你可以在下载列表中下载观看，或者在浏览器中打开，目前暂时没有添加的计划
