### ISSUE TITLE
[Bug] 闪退

### ISSUE THREAD

**Issue by lwq86918059** [Richasy/Bili.Copilot#474]
### Bug 描述

就打开视频无端端闪退崩溃，版本是2.2409.1.0，电脑是i3

### 复现问题的步骤

```plain text
就随便点开视频
```

### 预期行为

希望可以不要闪退

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
试着在设置/播放行为里切换一下播放器类型

**Comment by lwq86918059** [comment]
可以了谢谢
