### ISSUE TITLE
[Bug] 不定时闪退 mpv解码声音大小异常

### ISSUE THREAD

**Issue by WOJIAOSHIYI** [Richasy/Bili.Copilot#479]
### Bug 描述

使用原生解码声音正常10几分钟就闪退
使用MPV解码新开视频声音有时默认最大 有时默认最小 动下音量就好了  不定时闪退

### 复现问题的步骤

```plain text
MPV解码
1打开应用
2随便点击视频
3视频正常播放但声音最大
4手动调节音量 声音正常
5不定时闪退
```

### 预期行为

声音正常 不闪退

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
MPV 的声音问题新版(2.2409.2.0)已经修复了，你可以在 github 最新的 release 里下载体验，商店版本要在明天才能发布。
至于闪退问题，在设置里打开日志文件夹看看是否有日志，如果没有的话可能是渲染错误，尝试更新一下显卡驱动

**Comment by WOJIAOSHIYI** [comment]
> MPV 的声音问题新版（2.2409.2.0）已经修复了，你可以在 github 最新的 release 里下载体验，商店版本要在明天才能发布。 至于闪退问题，在设置里打开日志文件夹看看是否有日志，如果没有的话可能是渲染错误，尝试更新一下显卡驱动

好的好的 蟹蟹大佬 正在直播界面界面可以优化下吗 现在只显示头像还比较小 可以放大头像或者加上名字吗

**Comment by Richasy** [comment]
光标移到头像上可以显示用户名称和直播间名称。
如果这个不满足需求，请提个新的issue
