### ISSUE TITLE
[Bug] 视频显示错误：视频未按预期填充播放区且视频内容显示不完整

### ISSUE THREAD

**Issue by SymmFz** [Richasy/Bili.Copilot#480]
### Bug 描述

1. 首次打开任意视频时，视频内容不完整，仅显示视频画面的左上角部分，其他部分被裁剪掉。并且无法正常填充播放区域，仅显示在播放区的左上角，右侧和下侧留有大量空白区域。  

2. 在扩大窗口后，原先播放的视频区域（即播放区左上角）占屏幕的比例未发生变化，实际播放区未能按预期随播放区的扩大而扩大。此时视频画面被放大，而播放区域不变，导致实际显示的画面占完整视频画面的比例减小，仅显示视频内容的左上角部分，其他部分被裁剪掉。

### 复现问题的步骤

```plain text
1. 打开应用
2. 打开任意视频
3. 出现问题：视频内容显示不完整，同时无法正常填充播放区域，仅显示在播放区的左上角
4. 扩大窗口
5. 出现问题：视频画面被放大，而播放区域不变，导致实际显示的画面占完整视频画面的比例减小。同时无法正常填充播放区域
```

### 预期行为

1. 打开视频时，视频不被裁剪并能正常填充整个播放区，而不是在左上角
2. 调整窗口大小时，视频不被裁剪并能正常填充整个播放区

### 截图

首次打开
![Clip_2024-09-01_18-51-56](https://github.com/user-attachments/assets/65e9359a-fb70-481b-b5da-62cabb792248)

![Clip_2024-09-01_18-52-18](https://github.com/user-attachments/assets/e902939f-fb95-4780-995b-739c1f726373)

扩大窗口
![Clip_2024-09-01_18-52-38](https://github.com/user-attachments/assets/b6b923e2-52c5-4e4d-b3db-20fef37b3df8)

![Clip_2024-09-01_18-52-52](https://github.com/user-attachments/assets/a1fd0308-6557-40e9-aea6-3835ccedb3e7)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 日志记录

[applog.2024-09-01.log](https://github.com/user-attachments/files/16828671/applog.2024-09-01.log)

注:日志最后一条是在电脑黑屏死机（应该是哔哩助理导致的）时出现的，可能与这个问题无关

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
请在设置/播放行为中将播放器调整为原生播放器

**Comment by SymmFz** [comment]
> 请在设置/播放行为中将播放器调整为原生播放器

原生黑屏无法播放

![Clip_2024-09-01_19-13-29](https://github.com/user-attachments/assets/e862d416-9948-4205-a25a-07408bfe8311)

**Comment by Richasy** [comment]
试着降低画质到 1080P，然后右键黑屏区域，点击重载。
目前 AMD 显卡在使用 mpv 时或多或少有点问题，我正在找 AMD 设备进行调试

**Comment by SymmFz** [comment]
> 试着降低画质到 1080P，然后右键黑屏区域，点击重载。 目前 AMD 显卡在使用 mpv 时或多或少有点问题，我正在找 AMD 设备进行调试

应该本来就是可以播放的，只是加载时间太长，重复试了几次发现了下面的现象：

打开软件后首次播放的视频的加载时间显著长于之后打开的视频，前者在15s左右，后者不超过2s。如果在首次播放视频时，重载或者调整画质，哔哩助理会卡住或者无响应一段时间，然后可以正常播放，卡住的时间也是15s左右。因此，等黑屏加载和重载、调整画质好像效果差不多。

这台笔记本是 AMD 的 CPU 和核显，型号是：AMD Ryzen 7 7840H with Radeon 780M Graphics       3.80 GHz

**Comment by Waximell** [comment]
同AMD核显，遇到同样的问题，但在我这里如果在屏幕有缩放时才会出现，把窗口托到另一块无缩放的屏幕则正常，我据此猜测是屏幕缩放所导致的，希望可以提供修复思路。
我的是win11 24100，播放选择H265，MPV，来源为MS商店，核显为Vega（5900HS的），在原生模式下可以正常播放，MPV下同样不会出现等待（只是画面显示不全）

> 试着降低画质到 1080P，然后右键黑屏区域，点击重载。 目前 AMD 显卡在使用 mpv 时或多或少有点问题，我正在找 AMD 设备进行调试

**Comment by Richasy** [comment]
可以试一下从商店下载新版本（2.2409.2.0），得到一份报告，新版本似乎可以正常工作（目前还在收集验证）

**Comment by Richasy** [comment]
AMD 显卡目前仅支持原生播放器，mpv 存在难以解决的问题，目前正在寻求解决方法中
