### ISSUE TITLE
[Bug] 播放视频会黑屏

### ISSUE THREAD

**Issue by foxlesbiao** [Richasy/Bili.Copilot#484]
### Bug 描述

播放视频会黑屏

### 复现问题的步骤

```plain text
随便一个视频，在播放一段时间后，就会黑屏，需要重启才可以正常。
```

### 预期行为

播放正常

### 截图

https://github.com/user-attachments/assets/474176d4-766c-4a3f-bc07-9ec229999e01

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2024-09-02.log](https://github.com/user-attachments/files/16832302/applog.2024-09-02.log)

### 备注

配置：
![图片](https://github.com/user-attachments/assets/4ba9144b-7e79-41ee-848d-7546771357f3)
![图片](https://github.com/user-attachments/assets/231f23e3-ca22-45ed-940e-bc05f540e266)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
从日志上看，你正在使用mpv播放器，是否尝试过在设置/播放行为 中将默认播放器调整为原生？

**Comment by foxlesbiao** [comment]
> 从日志上看，你正在使用mpv播放器，是否尝试过在设置/播放行为 中将默认播放器调整为原生？

你好，我修改了设置，现在不会播放黑屏了。
![图片](https://github.com/user-attachments/assets/c2833ce4-da49-4e22-8494-abb325c0c227)
![图片](https://github.com/user-attachments/assets/510c33b4-e091-40ef-bdbf-b0eca56d8ef6)

avc+mpv或原生，还是会黑屏。

**Comment by Richasy** [comment]
目前的播放逻辑在 AMD 显卡上存在一些难以解决的问题，可以先使用原生播放器播放
