### ISSUE TITLE
[Feature] 希望小窗模式的窗口大小能够支持调节

### ISSUE THREAD

**Issue by Cywair** [Richasy/Bili.Copilot#485]
### 问题描述

希望能够像 Chrome 的 PIP 模式一样，用户能够根据需求等比例地调节窗口的大小。

### 描述解决方案

鼠标指针移动到窗口边缘时，光标会变成修改窗口大小的图标；按住鼠标左键并移动，窗口便会跟随着改变大小。

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
WinAppSDK并不支持这一点，目前暂无计划
