### ISSUE TITLE
三个功能请求：弹幕屏蔽，触屏优化和倍速无级调节

### ISSUE THREAD

**Issue by FFDVDGD** [Richasy/Bili.Copilot#486]
### 问题描述
触屏优化就不用说了吧
倍速无级调节就是像旧版一样而不是现在只能1.5倍2.0倍这样

### 描述解决方案
支持哔站网页端的分级弹幕屏蔽以及pakku（pakku）的相同弹幕合并功能
触屏逻辑和B站手机端一样，倍速调节感觉旧版更好

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Starfallan** [comment]
触摸确实需要优化，新版本触摸控制很抽象，应该是还完全没有相应设计适配的。

**Comment by Richasy** [comment]
弹幕屏蔽暂时没有计划，有需要请单独开一个issue，而不是合并多个请求到一个issue里

**Comment by FFDVDGD** [comment]
> 弹幕屏蔽暂时没有计划，有需要请单独开一个issue，而不是合并多个请求到一个issue里

明白了
