### ISSUE TITLE
[Bug] 视频评论区不见了

### ISSUE THREAD

**Issue by PYUDNG** [Richasy/Bili.Copilot#487]
### Bug 描述

安装源：微软商店
最近大概两三天前自动更新后，视频评论区就不见了
原先是视频播放器左侧上下居中的位置有个方形按钮，点击打开后可以查看视频详情和评论区，现在没有了，在其他位置也没有找到评论区

### 复现问题的步骤

```plain text
1. 打开任意视频
2. 找不到评论区
```

### 预期行为

有评论区
- 或像旧版本一样评论区在侧边展开查看
- 或是在视频下方展示

### 截图

![image](https://github.com/user-attachments/assets/4a3f0137-f5be-4978-832b-ce3ee0aa9c28)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

打开日志文件夹没看到有今天的日志文件，已有的日志文件都是更新前的（最近日志文件8月30日）

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
把你的鼠标移到右侧中间区域就能看到一个按钮，点一下就出来了

**Comment by PYUDNG** [comment]
> 右侧中间区域就能看到一个按钮，点一下侧边栏就出

好的，辛苦回答
