### ISSUE TITLE
[Feature] 关于直播体验的优化

### ISSUE THREAD

**Issue by St-Cai** [Richasy/Bili.Copilot#489]
### 问题描述

①目前直播遵循“加载完成后自动播放”的选项，与官方网页端、客户端的体验不一样，建议直播不适用该选项，打开后直接播放②建议在直播的控制栏加入手动重载的按钮，与官方网页端、客户端的体验一致。

### 描述解决方案

如上。

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
1. 第三方客户端不是为了实现和官方一致的体验而做的。自动播放的逻辑在哔哩助理内部适用所有播放类型，直播也不例外。
2. 所有重载选项都放在了右键菜单中，你可以在播放区域右键单击即可看到
