### ISSUE TITLE
[Bug] 稍后再看视频重复

### ISSUE THREAD

**Issue by KaiHuaDou** [Richasy/Bili.Copilot#497]
### Bug 描述

稍后再看中视频重复出现多次，疑似重复加载

### 复现问题的步骤

```plain text
1. 打开应用
2. 点击头像，打开稍后再看
3. 上下滚动多次
5. 稍后再看当中视频重复出现
```

### 预期行为

稍后再看只显示一遍

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
该问题应该已经在 2.2409.2.0 中修复了，你看下商店是否有更新
