### ISSUE TITLE
[Feature] 跟浏览器一样的多任务标签功能

### ISSUE THREAD

**Issue by Galaxyyou** [Richasy/Bili.Copilot#504]
### 问题描述

在浏览器查找视频的时候，我会先选好几个视频打开放到一边，等我选好之后我在进行观看。但是在哔哩助手上我做不了这一点。

### 描述解决方案

能否跟浏览器一样，打开视频的时候把它放在到类似浏览器标签页的后台，且可以打开多个视频共同存放，等我想播放的时候再进行播放。

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
你可能需要 `在新窗口播放` + `关闭自动播放`，我个人并不喜欢多标签设计，所以暂时不考虑
