### ISSUE TITLE
[Bug] 直播弹幕无法显示

### ISSUE THREAD

**Issue by Colin-Y0470** [Richasy/Bili.Copilot#507]
### Bug 描述

直播间弹幕已打开，但是没有显示任何弹幕。从官方客户端打开同一直播间有弹幕更新，但哔哩助理没有显示任何内容。

### 复现问题的步骤

```plain text
1.打开应用并进入直播间
2.打开弹幕
3.发现没有弹幕更新
```

### 预期行为

修复弹幕无法显示的问题

### 截图

https://github.com/user-attachments/assets/60285209-1d47-4ff1-b3eb-e61b494c724e

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

ARM64 设备

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
下个版本发布修复
