### ISSUE TITLE
[Bug] 刷新键无法刷新视频

### ISSUE THREAD

**Issue by gtnndgit** [Richasy/Bili.Copilot#508]
### Bug 描述

点击刷新键无法刷新视频，如录屏所示

### 复现问题的步骤

```plain text
1.打开应用
2.点击刷新键，bug复现
```

### 预期行为

点击刷新键刷新视频

### 截图

https://github.com/user-attachments/assets/51cfe2e0-ad0f-4ec9-8976-5b9f7452e084

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
热门不是推荐，不是每次刷新都会有新的内容，热门对应的网页类似 https://www.bilibili.com/v/popular/all/
