### ISSUE TITLE
[Feature] 希望可以优化一下用户界面

### ISSUE THREAD

**Issue by ssmengyan** [Richasy/Bili.Copilot#51]
### 问题描述

底部界面以小图标为子菜单的访问我认为还是比较清新的，但是界面不能切换为全屏。

### 描述解决方案

希望可以推出一个大窗口模式，能够还原出网页版bilibili的界面和操作逻辑，以现在这样一个类似于手机界面的图形窗口而言，在电脑上还是不够好用，对于我个人而言。或者可以直接按照现在的界面逻辑，等比例放大，然后ui旁边有子菜单的名称，在推荐视频流中可以有切换单列表和多列表的按键。

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你指的是 [哔哩](https://github.com/Richasy/Bili.Uwp)？我暂时没有更改现有 UI 的计划
