### ISSUE TITLE
[Feature] 音频流选择

### ISSUE THREAD

**Issue by zk00790** [Richasy/Bili.Copilot#512]
### 问题描述

哔哩哔哩目前支持更多丰富高级音频格式和类型
希望添加音频流选择，或显示目前播放音频流类型

### 描述解决方案

在视频画质流图标边添加频频流选择图标

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
目前默认选择最清晰的音频流，暂时没有提供这个配置的计划
