### ISSUE TITLE
[Bug] 播放器全屏以后屏幕底部有白色横条

### ISSUE THREAD

**Issue by Walkar66** [Richasy/Bili.Copilot#524]
### Bug 描述

在视频界面全屏以后，屏幕底部一个非常明显的白色横条，无论是使用原生播放器还是切换成MPV播放器结果都是一样的，都会出现这个白色横条

### 复现问题的步骤

```plain text
1.打开应用
2.随便点开一个视频
3.点击视频的全屏按钮
4.全屏后屏幕最底部出现了一个白色横条
```

### 预期行为

我希望全屏之后只有视频内容，不应该出现别的东西

### 截图

![屏幕截图 2024-09-13 101648](https://github.com/user-attachments/assets/703660a1-fbc1-4d76-806c-400b70784f11)

请使用黑色背景查看图片，不然不容易发现

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-09-08.log](https://github.com/user-attachments/files/16987679/applog.2024-09-08.log)
[applog.2024-09-09.log](https://github.com/user-attachments/files/16987680/applog.2024-09-09.log)
[applog.2024-09-10.log](https://github.com/user-attachments/files/16987681/applog.2024-09-10.log)
[applog.2024-09-11.log](https://github.com/user-attachments/files/16987682/applog.2024-09-11.log)
[applog.2024-09-12.log](https://github.com/user-attachments/files/16987683/applog.2024-09-12.log)
[applog.2024-09-13.log](https://github.com/user-attachments/files/16987684/applog.2024-09-13.log)

事实上问题一直存在

### 备注

我不清楚这个问题的根源是否源自于设置中的底部进度条，但我关闭它之后这个问题仍然没有得以解决

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
问题已修复
