### ISSUE TITLE
[Feature] 希望恢复重构之前的视频单独窗口播放的UI

### ISSUE THREAD

**Issue by mwnu** [Richasy/Bili.Copilot#528]
### 问题描述

之所以用一个APP而不是浏览器是因为APP更适合分屏，在surface等触控设备上更容易操作。
重构之前的版本，视频播放一个窗口，其他栏目一个窗口，非常适合在竖屏时分屏使用，屏幕一部分用来观看正在播放的视频，另一部分用来浏览推荐或关注的更新，点击则正在播放的窗口无缝切换到新的视频

### 描述解决方案

单独窗口播放视频

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
你可以右键单击视频，在弹出菜单中选择 `在新窗口播放`

**Comment by mwnu** [comment]
> 你可以右键单击视频，在弹出菜单中选择 `在新窗口播放`

右键打开新窗口无法固定位置，不是独占(新视频右键打开会再开一个窗口)

**Comment by mwnu** [comment]
算了，已卸载所有该作者APP，非常不成熟的开发者，折腾玩具，浪费时间
