### ISSUE TITLE
希望在流行页面，添加个搜索框，这样可以搜索相关的视频！

### ISSUE THREAD

**Issue by 2duat** [Richasy/Bili.Copilot#53]
### 问题描述

希望在流行页面，添加个搜索框，这样可以搜索相关的视频！

### 描述解决方案

希望在流行页面，添加个搜索框，这样可以搜索相关的视频！

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
搜索框在首页
