### ISSUE TITLE
[Feature] 希望能提供鼠标中键滚轮按下后的滑动页面功能

### ISSUE THREAD

**Issue by sekurodesu** [Richasy/Bili.Copilot#530]
### 问题描述

如题，现在在各类页面无法像bilibili自带PC版客户端那样使用鼠标滚轮按下后来进行页面滑动，使用不方便。

### 描述解决方案

希望适配该功能

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
B站客户端能这么用是因为它外面是个浏览器，底层支持这种操作。哔哩助理并不一样，目前也没有计划对鼠标中键点按做额外的处理
