### ISSUE TITLE
[Bug] 无法播放视频

### ISSUE THREAD

**Issue by w516500** [Richasy/Bili.Copilot#532]
### Bug 描述

单纯的无法播放视频，但是直播和文章没有问题

### 复现问题的步骤

```plain text
点击视频有动画无反应，点击无痕播放无动画反馈
```

### 预期行为

点击进入播放页

### 应用来源

- [X] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-09-14.log](https://github.com/user-attachments/files/17001166/applog.2024-09-14.log)

### 备注

根据日志发现是'C:\Windows\system32\Bili Downloads‘无法访问，进入C:\Windows\system32创建Bili Downloads文件夹后，现已能正常播放视频

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
看上去是由于一些奇怪的权限问题导致的。一般来说，应用默认会在视频文件夹下创建下载文件夹，看上去这一步失败了，APP 没有获取到你的视频文件夹，请检查视频文件夹是否存在。`C:\Windows\system32` 是系统文件夹，一般不要在里面存储视频

**Comment by w516500** [comment]
> 考虑是由于一些奇怪的权限问题导致的。一般来说，应用默认会在视频文件夹下创建下载文件夹，看看这一步失败了，APP没有获取到你的视频文件夹，请检查视频文件夹是否存在。`C:\Windows\system32`是系统文件夹，一般不要在存储视频里面

原来如此，我之前将windows的视频文件夹指向到了一个现在已经被移除的硬盘，这可能是问题发生的原因。
