### ISSUE TITLE
[Bug] 左右方向键无法调整视频进度

### ISSUE THREAD

**Issue by huoyan1231** [Richasy/Bili.Copilot#537]
### Bug 描述

如标题，在视频播放时左右方向键无法调整视频进度

### 复现问题的步骤

```plain text
打开任意视频
尝试使用方向键调整视频进度
```

### 预期行为

左右方向键可以正常调整视频进度

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2024-09-14.log](https://github.com/user-attachments/files/17001650/applog.2024-09-14.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
从日志来看，你正在使用外部播放器，外部播放器有自己的快捷键，跟应用无关。

如果你指的是应用内播放器，我这边没有复现这个问题，方向键可以正常调整进度。

你可以试着点击一下视频以获取焦点，再使用方向键切换

**Comment by huoyan1231** [comment]
> 从日志来看，你正在使用外部播放器，外部播放器有自己的快捷键，跟应用无关。
> 
> 如果你指的是应用内播放器，我这边没有复现这个问题，方向键可以正常调整进度。
> 
> 你可以试着点击一下视频以获取焦点，再使用方向键切换

在设置中更改为原生播放器并重启哔哩助理后仍然存在此问题

**Comment by huoyan1231** [comment]
测试了一下，问题仅在设置中“单次快退/快进时长”设置为2的时候才会有

**Comment by Richasy** [comment]
哦，那就是 by design，应用有一个限制器，单次进度改动小于3秒都会被过滤掉，用来避免一些细小操作

**Comment by huoyan1231** [comment]
> 哦，那就是 by design，应用有一个限制器，单次进度改动小于3秒都会被过滤掉，用来避免一些细小操作

那程序本身是否有设计上下方向键调整音量的功能？我这边上下音量键和鼠标滚轮是一样的行为

**Comment by Richasy** [comment]
那应该是你的焦点跑到别的地方去了，点一下播放器，然后再按上下键就可以调整音量了

**Comment by huoyan1231** [comment]
> 那应该是你的焦点跑到别的地方去了，点一下播放器，然后再按上下键就可以调整音量了

哦 还真是 感谢回复
