### ISSUE TITLE
[Bug] 我的标题

### ISSUE THREAD

**Issue by haodedog** [Richasy/Bili.Copilot#538]
### Bug 描述

安装的时候提示证书问题，power shell脚本运行报错

### 复现问题的步骤

```plain text
点击安装包就提示错误
```

### 预期行为

我希望可以安装并使用

### 截图

![PixPin_2024-09-14_17-58-52](https://github.com/user-attachments/assets/8ad33ad8-13fe-4223-b9dc-2809305183b3)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩助理中

**Comment by Richasy** [comment]
请仔细阅读自述文件中关于侧载的步骤，不要直接运行 msixbundle。装不好的话请使用 Microsoft Store 安装

**Comment by haodedog** [comment]
哦，好的，知道了，刚刚其实我已经按照你在叙述文件里面的要求做了，但是还是莫名报错，重启一下电脑又莫名其妙的没问题安装成功了，就很玄学（
