### ISSUE TITLE
[Bug] 使用AI服务时报错

### ISSUE THREAD

**Issue by Ptilopsis01** [Richasy/Bili.Copilot#539]
### Bug 描述

如题，提示该模型返回空响应

### 复现问题的步骤

```plain text
1. 在设置填入ai相关信息
2. 点开视频，使用ai功能
3. 出现错误
```

### 预期行为

AI增强可正常使用

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 日志记录

[applog.2024-09-14.log](https://github.com/user-attachments/files/17001846/applog.2024-09-14.log)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
从日志内容来看，你是用了一些非 Open AI 的模型，却在调用 OpenAI 的解析器。

如果这是故意为之，我推测你正在使用的 AI 服务兼容 Open AI 的接口规范，所以你才这么做。

但看上去你的服务返回的内容并不是标准的 Open AI Streaming 预期的返回内容，所以解析失败。请你再次确认你所使用的服务是否支持 Open AI Chat Streaming 的返回格式
