### ISSUE TITLE
[Bug] 我的标题

### ISSUE THREAD

**Issue by haodedog** [Richasy/Bili.Copilot#541]
### Bug 描述

看视频无法查看评论

### 复现问题的步骤

```plain text
点击一个视频，发现无法查看评论
```

### 预期行为

我希望可以查看评论

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你是把右侧边栏折叠了吗？

把鼠标移到应用右侧的中间位置，你会看到一个折叠按钮，点击即可

**Comment by haodedog** [comment]
谢谢
