### ISSUE TITLE
[Bug] 视频播放结束后,底部出现黄线

### ISSUE THREAD

**Issue by ZbinH2O** [Richasy/Bili.Copilot#543]
### Bug 描述

2.2409.4.0版本,使用默认的播放器显示模式下,开启显示底部进度条选项,视频结束的时候,播放器底部会出现一条黄色的色条,鼠标移到底部触发控制组件的时候色条消失,移开又会出现..

### 复现问题的步骤

```plain text
1.打开应用
2.设置开启"显示底部进度条"选项
3.点开随便一个视频
4.等待视频播放结束
```

### 预期行为

视频播放结束后,不会出现黄色的色条

### 截图

![微信截图_20240914205945](https://github.com/user-attachments/assets/8115e693-b71e-4317-83c5-b343a61c6676)
![微信截图_20240914210003](https://github.com/user-attachments/assets/70b8ea0e-c13c-4f2f-a168-225f3c306e6f)
![微信截图_20240914210509](https://github.com/user-attachments/assets/0b447efc-c85f-425b-956e-9463229e2ab7)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-09-14.log](https://github.com/user-attachments/files/17002531/applog.2024-09-14.log)

### 备注

在最新的2.2409.4.0版本之前,也会出现这个情况,只是之前触发底部控制组件出现之后,移开鼠标后色条就不会出现了,2.2409.4.0变成了会重复出现了

### 人人为我，我为人人

我更擅长发现问题

**Comment by ZbinH2O** [comment]
再试了一下,好像是因为视频结束之后,底部进度条的颜色,没有像播放过程中一样拿系统的主题色,变成了黄色的原因吗?

**Comment by Richasy** [comment]
黄色表示播放暂停，这个是by design
