### ISSUE TITLE
[Bug] 直播无法正常加载（非中国IP）

### ISSUE THREAD

**Issue by Ryanrrt** [Richasy/Bili.Copilot#544]
### Bug 描述

在非中国IP下，尝试多个直播间均无音视频，仅弹幕工作正常。在Bilibili网页端可以正常加载。

### 复现问题的步骤

```plain text
点击直播间，无音视频
```

### 预期行为

正常观看直播

### 截图

![PixPin_20240914_163352](https://github.com/user-attachments/assets/698bcdbd-7c5a-4ccf-a807-3b2be1114522)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2024-09-14.log](https://github.com/user-attachments/files/17002625/applog.2024-09-14.log)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
可能是请求失败了，如果失败的话，你可以在设置里的日志中找到。

长时间没有加载，可以右键播放区域，然后选择重载。

P.S. 下个版本会推出网页播放器，内嵌B站网站，作为无法播放视频/直播的回退方案
