### ISSUE TITLE
调用bbdown时支持自定义参数

### ISSUE THREAD

**Issue by FFDVDGD** [Richasy/Bili.Copilot#546]
### 问题描述

有时有下载AI字幕的需求，而现在的内置bbdown并不支持自定义参数

### 描述解决方案

可以自定义是否下载ai字幕等参数

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
我希望哔哩助理的下载尽量简单。如果你对自定义配置有比较强烈的需求，可以在设置里打开 `下载时调用外部 BBDown` 的选项，然后自行配置 BBDown
