### ISSUE TITLE
[Feature] 对于过于混乱且缺失功能的下载下拉菜单的更改建议

### ISSUE THREAD

**Issue by jichuan254** [Richasy/Bili.Copilot#551]
### 问题描述

这个新版的BBDOWN下载菜单，非常的混乱，点击清晰度对应的是单集，点击全部P又不能预设清晰度，想要下全部P的单独弹幕吧，点击杂项发现是只能下载单个的。

### 描述解决方案

基于现在的菜单成型，我建议这么更改，这个区域分为这么几区几行：1区清晰度预设：清晰度，并且点击清晰度后不会直接下载而是根据2区的选择生效最终结果；2区视频区：下载单P视频/下载全P视频/下载指定P视频；3区杂项区：下载单P弹幕/下载全P弹幕/下载指定P弹幕（有的动漫分P过多，不好单独挑选）/下载封面（一般来说，很多P的视频不会经常更改封面，所以无需区分）；
这样就能完成一般情况下的下载功能的完善。
然而，这个下载菜单不能拉的过长，我也觉得太长了不好看，所以，我非常建议把清晰度预设放在软件的总设置里，这也是大多数视频软件的做法，一般人也很少经常更改下载视频的习惯，90%的观众下载肯定是画质优先，需要下载低分辨率的小部分用户，在设置里更改也不会觉得过于麻烦，这样1区那个突兀的清晰度预设就会消失。

### 附加信息

如果能实现功能，作者有更巧妙的实现方法也是可以的。

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
哔哩助理内置的下载功能只求满足最基本的需求（下载当前视频），我不会在下载功能上投入更多的精力。

如果你追求更强大的自定义能力，请在设置/下载设置中开启 `下载时调用外部 BBDown`，如果你需要更复杂的命令，可以打开 `下载时仅复制命令`，然后在基础配置外自行修改符合你需要的配置项。

如果你更喜欢图形化界面，这个应用可能更符合你的要求：[BiliDown](https://zhouql.vip/bilibili/pc/)
