### ISSUE TITLE
[Feature] 增加画质偏好选项

### ISSUE THREAD

**Issue by agsdxcze** [Richasy/Bili.Copilot#552]
### 问题描述

画质偏好选项中的选择较少，只有1080高清和4K。

![image](https://github.com/user-attachments/assets/c3d51bd5-2ae8-47b3-a935-ffd3dae4c7d9)
![image](https://github.com/user-attachments/assets/b195dc68-c7f6-4165-90de-63aba690103e)
![image](https://github.com/user-attachments/assets/ff8579e6-de7d-4a7e-b0e8-a2bdd2722f59)

### 描述解决方案

希望在画质选项中增加 1080P 60帧 和 1080P 高码率

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
画质偏好选项最根本的目的是让使用者根据自己的网络状况选择比较合适的画质，绝大多数情况下，自动已经可以满足需求。

我不认为有必要在 1080P 分出多个挡位，你完全可以在自动档播放视频时选择 1080 60 帧，下次播放视频时自然优先选择这个清晰度
