### ISSUE TITLE
[Feature] 在其他页面时小窗播放

### ISSUE THREAD

**Issue by XHZMC** [Richasy/Bili.Copilot#553]
### 问题描述

缺少该功能

### 描述解决方案

切到APP内其他页面时，可选择将该视频以小窗形式继续播放。

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
这个并不在计划内，你可以尝试下面的操作：

点击视频顶部的溢出菜单，选择在新窗口打开
    ![image](https://github.com/user-attachments/assets/5228aa51-1955-4ece-9c4c-9e7dffe36258)

然后你就可以退出主窗口的播放页面，去浏览其他内容了
