### ISSUE TITLE
[Feature] 增加播放本地带弹幕的视频

### ISSUE THREAD

**Issue by auqhjjqdo** [Richasy/Bili.Copilot#554]
### 问题描述

缓存了B站视频和弹幕到本地后，使用其他播放器不识别xml格式的弹幕，只能使用类似弹弹play这种专门的弹幕播放软件，哔哩助理自身已实现流媒体的带弹幕播放，希望能支持本地视频和弹幕的播放

### 描述解决方案

添加选择本地视频和xml弹幕的文件并调用视频播放组件进行播放

### 人人为我，我为人人

None

**Comment by ibella911** [comment]
博主你好，我安装配置完之后运行了liverecorder之后直播检测错误，提示ConnectError('All connection attempts failed')。我是一个大学学计算机但是python小白，下面提示了好多代码的错误，我不知道这个如何修正，可以添加您的联系方式请教一下嘛，可以有偿，感谢您的回复

**Comment by auqhjjqdo** [comment]
> 博主你好，我安装配置完之后运行了liverecorder之后直播检测错误，提示ConnectError('All connection attempts failed')。我是一个大学学计算机但是python小白，下面提示了好多代码的错误，我不知道这个如何修正，可以添加您的联系方式请教一下嘛，可以有偿，感谢您的回复

该错误为网络丢包导致不影响正常运行
请不要在不相关的issue提及其他repo

**Comment by ibella911** [comment]
非常抱歉打扰您，我第一次使用github，给您带来不便向您道歉，感谢解答，我先运行软件等待主播开播之后看有没有自动录制下来，非常感谢您的回复

**Comment by Richasy** [comment]
@auqhjjqdo 就我所知，VLC/MPV/PotPlayer都可以播放本地带弹幕的视频，只要视频和字幕xml文件名一致即可。

再者，你提到的功能的确是更进一步的想法，但我不会在哔哩里做。

哔哩中的 webdav 只会维持现状，不会添加更多的功能，因为这些功能会放到我计划中的下一个 APP（海报墙） 里

**Comment by auqhjjqdo** [comment]
> @auqhjjqdo 就我所知，VLC/MPV/PotPlayer都可以播放本地带弹幕的视频，只要视频和字幕xml文件名一致即可。
> 
> 再者，你提到的功能的确是更进一步的想法，但我不会在哔哩里做。
> 
> 哔哩中的 webdav 只会维持现状，不会添加更多的功能，因为这些功能会放到我计划中的下一个 APP（海报墙） 里

我现在正在使用PotPlayer，实测只支持ass格式的弹幕，xml弹幕并不显示，而且ass格式弹幕播放出来有明显掉帧影响观感
目前我只看到弹弹play支持xml弹幕，期待作者的新app

**Comment by Richasy** [comment]
> 我现在正在使用PotPlayer，实测只支持ass格式的弹幕，xml弹幕并不显示，而且ass格式弹幕播放出来有明显掉帧影响观感 目前我只看到弹弹play支持xml弹幕，期待作者的新app

我这边的 PotPlayer 是可以播放的，但就像你说的，有掉帧的感觉。我这里效果最好的是 mpv，如果你感兴趣，可以在 [mpv-lazy](https://github.com/hooke007/MPV_lazy/releases) 处下载 Windows 包
