### ISSUE TITLE
建议将倍速改为0.25一格

### ISSUE THREAD

**Issue by jiagejiagejiage** [Richasy/Bili.Copilot#562]
### 问题描述

播放器的倍速0.5的一格，看视频有的时候需要加快速度，感觉1.5倍速偏快；有的时候需要降低速度，感觉0.5倍速偏慢，非常需要0.75和1.25倍速的支持

### 描述解决方案

建议将倍速改为0.25的倍数，最好可以像global speed一样自己输入倍速

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
进入应用设置，在播放器控制里打开 `播放速率增强`

**Comment by jiagejiagejiage** [comment]
确实可以，大佬辛苦了，祝大佬中秋快乐！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Richasy ***@***.***>
发送时间: Monday, September 16, 2024 7:53:02 PM
收件人: Richasy/Bili.Copilot ***@***.***>
抄送: jiagejiagejiage ***@***.***>; Author ***@***.***>
主题: Re: [Richasy/Bili.Copilot] 建议将倍速改为0.25一格 (Issue #562)


进入应用设置，在播放器控制里打开 播放速率增强

―

**Comment by Richasy** [comment]
同乐同乐
