### ISSUE TITLE
[Feature] 添加多窗口打开

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Copilot#565]
### 问题描述

支持在新窗口中打开
![image](https://github.com/user-attachments/assets/872cfad4-efd3-4f1d-8595-3b8664250214)
但希望可以和之前版本一样有个可以直接把视频默认单独打开的设置

### 描述解决方案

设置中添加一个多窗口打开选项（就像之前的版本）

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
已实现，下个版本发
