### ISSUE TITLE
[Feature] 增加关闭Gemini 安全选项功能

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Copilot#567]
### 问题描述

有些视频设计一些词汇会莫名其妙出发Gemini的安全限制

### 描述解决方案

有一个开源项目设计过这个问题，或许可以参考一下
https://github.com/flyun/chatAir
https://github.com/flyun/chatAir/commit/0f2fb41a441ae8e8ec5108b37f9e4f06a05b0e78

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
应用暂时不会开放各模型的自定义配置，对于 Gemini，我暂时上调了它的安全阈值，但出于RAI的考虑，不会关闭它。

**Comment by blibilijojo** [comment]
> 应用暂时不会开放各模型的自定义配置，对于 Gemini，我暂时上调了它的安全阈值，但出于RAI的考虑，不会关闭它。

即使出于RAI的考虑，也可以选择直接关闭模型的安全阈值。因为即使关闭了安全阈值，模型本身的安全底线仍然存在，例如对于敏感问题的处理方式不会改变，该不回答的仍然不会回答。既然开发者提供了用户调整配置的选项，说明这些配置的调整本身就是被允许的，用户可以根据自己的需求进行选择。
