### ISSUE TITLE
[Bug] 播放器问题

### ISSUE THREAD

**Issue by Minessential** [Richasy/Bili.Copilot#574]
### Bug 描述

网络状态不好的时候，点击视频后退出，视频可能在后台播放声音，点击其他视频也不会停止播放

### 复现问题的步骤

```plain text
1.打开应用
2.点击任意视频，等待视频加载
3.在视频即将加载成功时点击软件左上角的返回按钮
4.此时软件回到视频列表页面，但是会有刚刚点击的视频在播放，无法停止
5.此时打开其他视频会同时播放
```

### 预期行为

最好的方式当然是确保点击返回按钮后视频不会播放。
或者点击其他视频时暂停可能由于网络问题然后在后台播放的视频？

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 Build 27695 arm

### 运行设备

ARM64 设备

### 日志记录

[applog.2024-09-17.log](https://github.com/user-attachments/files/17018064/applog.2024-09-17.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
已经修了，下个版本更新
