### ISSUE TITLE
[Bug] 视频播放全窗口模式和全屏模式bug

### ISSUE THREAD

**Issue by 73410** [Richasy/Bili.Copilot#577]
### bug1
先点击全窗口模式，然后点击全屏模式会出现视频以外的部分
![image](https://github.com/user-attachments/assets/b5fc0400-e5db-45af-9c11-288106c64a83)

## bug2
先点击全屏模式，然后点击全窗口模式会出现一个可滑动的全窗口
![image](https://github.com/user-attachments/assets/1beb0e19-e745-4833-bfc2-42ea97b2e8fd)

### 复现问题的步骤

```plain text
bug1:
1. 打开任意视频
2. 点击全窗口模式
3. 点击全屏模式
4. 出现视频以外的部分
bug2:
1. 打开任意视频
2. 点击全屏模式
3. 点击全窗口模式
4. 出现一个可滑动的全窗口界面
```

### 预期行为

1. 在打开全窗口的情况下，点击全屏模式，应该进入到正常的全屏状态
2. 在全屏模式下点击全窗口模式，进入正常的全窗口

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你是什么显卡？

**Comment by 73410** [comment]
AMD核显



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月18日(周三) 上午7:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Richasy/Bili.Copilot] [Bug] 视频播放全窗口模式和全屏模式bug (Issue #577)




 
你是什么显卡？

**Comment by 73410** [comment]
> 你是什么显卡？如果使用原生播放器是否还会出现这个问题

用的就是原生的

**Comment by 73410** [comment]
这个问题应该是全屏模式和全窗口模式冲突了吧，两个功能直接单独使用是可以的
