### ISSUE TITLE
[Bug] 使用右键在新窗口中打开的话默认是全屏窗口显示

### ISSUE THREAD

**Issue by cytusllll** [Richasy/Bili.Copilot#578]
### Bug 描述

使用右键在新窗口中打开的话默认是全屏窗口显示，在左下角-设置-默认播放器显示模式四个选项设置不生效，怎么选都是全屏窗口模式。

### 复现问题的步骤

```plain text
1.打开应用
2.鼠标右键-在新窗口中打开-默认就是全屏窗口
3.左下角设置
4.播放行为
5.默认播放器显示模式-怎么选都是全面窗口
```

### 预期行为

1.希望能增加在新窗口打开视频不是全屏窗口的选项

2.希望能在设置中也增加一个选项-点击视频是 选择新窗口中打开 还是 默认

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by blibilijojo** [comment]
补充一个我自己的发现，在播放合集视频貌似不是新窗口全屏，而是默认
