### ISSUE TITLE
[Feature] 弹幕随屏幕缩放

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Copilot#581]
### 问题描述

在全屏、网页全屏、标准的屏幕上观看视频时，弹幕的大小不变
![image](https://github.com/user-attachments/assets/97cf3591-ac15-4ec2-9036-5eed7efe4f7c)

### 描述解决方案

弹幕随屏幕缩放

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
默认就是会根据当前播放视区的大小来缩放的，只不过不会影响之前已经渲染出来的弹幕，只有后渲染的弹幕才会应用新的大小
