### ISSUE TITLE
[Feature] 希望增加视频屏蔽功能

### ISSUE THREAD

**Issue by zuiaiyutu** [Richasy/Bili.Copilot#582]
### 问题描述

由于b站的推荐机制，老是推荐一些不喜欢的视频，希望增加一个视频屏蔽功能

### 描述解决方案

视频标题屏蔽，视频标签屏蔽，UP主UID屏蔽，视频分区屏蔽，置顶评论屏蔽，屏蔽点赞率低于x的视频，屏蔽视频时长低于x的视频
比如同时出现A标签和B标签就屏蔽这个视频，

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
我对这个持审慎态度，极端情况下，可能会在短时间内发起十多个请求，被风控了就不好玩了
