### ISSUE TITLE
[Bug] 使用内置mpv播放画面无法全屏

### ISSUE THREAD

**Issue by Leiserx** [Richasy/Bili.Copilot#583]
### Bug 描述

当使用内置的Mpv作为播放器时，点击视频全屏画面只展示出部分。

### 复现问题的步骤

```plain text
1.设置里播放行为-播放器类型-mpv
2.点击视频全屏
```

### 预期行为

正确展示全屏内容

### 截图

![image](https://github.com/user-attachments/assets/d6c88dde-2dac-400b-be3c-5ff953b018f5)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Leiserx** [comment]
显示器的分辨率 2560x1440
目前还有当我以小窗打开视频时，视频无法占满全部画面
![image](https://github.com/user-attachments/assets/7bd78743-ab6d-4e01-a4cb-6ac61543ed90)
当我以最大化哔哩助手打开画面时也存在如上图问题，但是这时缩放为正常
![image](https://github.com/user-attachments/assets/6c6e7ddf-7616-400c-b7cf-f468e4989e67)

**Comment by Richasy** [comment]
AMD 不要用 mpv，尽量使用原生或者外部mpv播放器，目前内置的mpv仅在nvdia和intel上工作，后续会检测显卡并给出提示
