### ISSUE TITLE
[Bug] 使用MPV播放器，内存爆了

### ISSUE THREAD

**Issue by enlch** [Richasy/Bili.Copilot#585]
### Bug 描述

使用MPV播放器播放视频，内存持续增长，直至100，然后卡死。原生播放器没问题

### 复现问题的步骤

```plain text
打开应用，播放器改为MPV，然后随便打开一个视频，几分钟之后内存爆炸
```

### 预期行为

正常使用

### 截图

![PixPin_2024-09-17_21-55-35](https://github.com/user-attachments/assets/df4ee389-9661-464d-8c4b-e9103b9170d8)
![PixPin_2024-09-17_21-56-21](https://github.com/user-attachments/assets/5c892d9d-533d-41ba-97ae-462978318093)
![PixPin_2024-09-17_21-58-51](https://github.com/user-attachments/assets/4e25dd7e-0457-4f94-b007-43f90d97b4f0)
![PixPin_2024-09-17_21-59-06](https://github.com/user-attachments/assets/77673e1b-934d-4d72-b688-3619359eb32c)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
AMD 不要用 mpv，尽量使用原生或者外部mpv播放器，目前内置的mpv仅在nvdia和intel上工作，后续会检测显卡并给出提示

**Comment by enlch** [comment]
> AMD 不要用 mpv，尽量使用原生或者外部mpv播放器，目前内置的mpv仅在nvdia和intel上工作，后续会检测显卡并给出提示

看到注意事项了，但笔记本不是amd，CPU：i5 8300H    GPU：1050TI

**Comment by enlch** [comment]
> > AMD 不要用 mpv，尽量使用原生或者外部mpv播放器，目前内置的mpv仅在nvdia和intel上工作，后续会检测显卡并给出提示
> 
> 看到注意事项了，但笔记本不是amd，CPU：i5 8300H GPU：1050TI

笔记本型号是小米游戏本8代
