### ISSUE TITLE
希望添加哔哩哔哩电脑版“精选”那个按钮（刷视频功能）

### ISSUE THREAD

**Issue by zaizhe** [Richasy/Bili.Copilot#586]
### 问题描述

希望添加哔哩哔哩电脑版“精选”那个按钮（刷视频功能）![image](https://github.com/user-attachments/assets/a5c0f6dd-fe62-4e63-9971-a476d2668bb8)

### 描述解决方案

希望添加哔哩哔哩电脑版“精选”那个按钮（刷视频功能）

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
这里：
![image](https://github.com/user-attachments/assets/16701223-4a73-4ead-a5ff-1d859ebf52af)

**Comment by zaizhe** [comment]
不能用键盘的上下键或者鼠标滚轮切换视频
