### ISSUE TITLE
[Feature] 关闭Gemini 安全选项功能，而不是提高安全阈值

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Copilot#587]
### 问题描述

之前提过这个议题，回复是出于对RAI的考虑，只提高安全阈值，不关闭。
**但我觉得即使出于RAI的考虑，也可以选择直接关闭模型的安全阈值。因为即使关闭了安全阈值，模型本身的安全底线仍然存在，例如对于敏感问题的处理方式不会改变，该不回答的仍然不会回答。既然Gemini提供了用户调整配置的选项，说明这些配置的调整本身就是被允许的，用户可以根据自己的需求进行选择。**

### 描述解决方案

.

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
等新版本发布后建议先尝试后再决定是否要关闭。

我目前并不觉得B站的内容有敏感到必须要关闭安全阈值才能回答的底部
