### ISSUE TITLE
[Bug] 播放一个视频后关闭后界面会卡住

### ISSUE THREAD

**Issue by mohiko** [Richasy/Bili.Copilot#59]
### Bug 描述

播放一个视频一段时间后关闭回到哔哩助手页面会导致鼠标光标有一段时间无法操作

### 复现问题的步骤

```plain text
1播放任意一段视频2分钟以上
2关闭视频界面
3鼠标光标在主界面变成左右双箭头无法点击无法操控
4要等一段时间才会恢复正常
```

### 预期行为

关闭后能正常操控

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 专业版 Insider Preview 23H2 25921.1000

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
暂时无法复现此问题

**Comment by YHLShaw** [comment]
我也遇到了，卡主然后闪退了

**Comment by YHLShaw** [comment]
我崩溃在这一行，google了一圈但是没有找到啥信息，
![S75YGKU17N6IFQOAORR23FA](https://github.com/Richasy/Bili.Copilot/assets/25974848/5e26be50-7634-47ff-81b1-c57a110cd11e)
![HP@DI 3HD7AO_I_Y`ZN1L3D](https://github.com/Richasy/Bili.Copilot/assets/25974848/293a2f8f-ec48-4a6f-a2df-dad81432b0b6)
