### ISSUE TITLE
[Feature] 实现类似安卓的应用内自动小窗功能

### ISSUE THREAD

**Issue by TonyBlur** [Richasy/Bili.Copilot#597]
### 问题描述

希望能在设置中添加一个开关，以启用“离开正在播放的视频界面时，在新窗口中打开视频并进入小窗模式”的功能，以实现类似安卓的应用内自动小窗功能，即当从正在播放中的视频切换到软件其他页面中时，自动创建一个小窗继续播放当前视频，从而不打断视频观看体验

### 描述解决方案

在设置中添加一个开关以设置该功能
开关启用后，该功能的实现逻辑为：离开正在播放的视频界面时，在新窗口中打开视频并进入小窗模式

### 备选方案

暂无

### 附加信息

感谢大佬的付出

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
不搞。

WinUI3 的播放器实现不太能允许这种操作
