### ISSUE TITLE
[Bug] 应用所有界面无法加载

### ISSUE THREAD

**Issue by Frid-Yuandu** [Richasy/Bili.Copilot#598]
### Bug 描述

打开应用后所有界面均停滞在加载阶段，同时无法退出登录账号。同一网络环境下使用浏览器访问bilibili，可以正常登录和观看视频。重新安装后问题消失。

### 复现问题的步骤

```plain text
1.打开应用即可复现，复现率100%。
```

### 预期行为

应用各界面正常加载，或弹出错误指引窗口（如重新登录提醒）。

### 截图

![图片](https://github.com/user-attachments/assets/c0b54426-8bfd-4a7b-ba0c-7ca5a1f415e1)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 备注

推测可能由于此前修改密码所致。

### 人人为我，我为人人

None

**Comment by xcwl520** [comment]
我很早就遇到了这种情况，清除软件数据，重新登录就好了。
怀疑是B站Cookie过期导致的

**Comment by Frid-Yuandu** [comment]
你说得有道理，不过要是app端能有提示就更好了。
