### ISSUE TITLE
[Feature] 希望能实现类似网页端播放页面的宽屏功能

### ISSUE THREAD

**Issue by heichaowo** [Richasy/Bili.Copilot#603]
### 问题描述

![image](https://github.com/user-attachments/assets/9543e13e-be1d-43bc-9853-79061c6cd455)

### 描述解决方案

如图，就是把播放列表评论什么的都放到下方，聚焦视频内容

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by salomejou** [comment]
问一下这个软件没开大会员能看大会员画质吗？比如4k画质
