### ISSUE TITLE
"在新窗口中打开"出现错误

### ISSUE THREAD

**Issue by STU-TAN** [Richasy/Bili.Copilot#608]
### Bug 描述

在首页面，选中视频鼠标右击后使用"在新窗口中打开"后，会出现打开的不是选中视频而是曾观看过的视频（比较随机没细比较过），频率每天若观看1小时内会出现。还会出现无法播放的情况，频率很低一两次。

### 复现问题的步骤

```plain text
比较随机，我也不能肯定出现的时间。我惯用新窗口，多次使用应该会出现。
```

### 预期行为

"在新窗口中打开"不会出现错误。

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-09-17.log](https://github.com/user-attachments/files/17068418/applog.2024-09-17.log)
[applog.2024-09-19.log](https://github.com/user-attachments/files/17068419/applog.2024-09-19.log)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
暂时不能复现该问题，先关闭，如果新版本的岛播放器还有这个问题，请再打开它
