### ISSUE TITLE
[Bug] 无法安装

### ISSUE THREAD

**Issue by nanakura** [Richasy/Bili.Copilot#609]
### Bug 描述

![image](https://github.com/user-attachments/assets/b35db0ce-b735-4ef8-a385-016c6a36eda1)

### 复现问题的步骤

```plain text
右键执行ps1
```

### 预期行为

安装成功

### 截图

![image](https://github.com/user-attachments/assets/b35db0ce-b735-4ef8-a385-016c6a36eda1)
已开启开发者选项设置
![image](https://github.com/user-attachments/assets/18f61631-7981-4f04-819c-1277b2abacc9)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 日志记录

 Islatan@reika ~  Get-AppPackageLog -ActivityID 19bbc64f-edf0-0000-e59f-8d1bf0edda01

Time                      ID           Message
----                      --           -------
2024/9/20 10:51:52        604          已使用主参数 BiliCopilot.UI_2.2409.5.0_x64.msix、依赖关系参数 Microsoft.WindowsA
                                       ppRuntime.1.6.msix 以及选项 ForceApplicationShutdownOption 和 0 开始对程序包执行
                                       部署 Add 操作。要获取有关诊断应用部署问题的帮助，请参阅 http://go.microsoft.com/
                                       fwlink/?LinkId=235160。
2024/9/20 10:51:52        157          已针对 CN=Richasy 发布的应用包的核心内容验证应用包签名。在读取文件之前，不会验证
                                       负载。
2024/9/20 10:51:52        216          应用部件清单(manifest)验证警告: 声明的命名空间 http://schemas.microsoft.com/deve
                                       loper/appx/2015/build 不适用，在清单处理期间将忽略它。
2024/9/20 10:51:52        170          已成功为应用包 Richasy.BiliCopilot_2.2409.5.0_x64__g7ew4fxhv1f46 创建流读取器。
2024/9/20 10:51:52        157          已针对 CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washingto
                                       n, C=US 发布的应用包的核心内容验证应用包签名。在读取文件之前，不会验证负载。
2024/9/20 10:51:52        170          已成功为应用包 Microsoft.WindowsAppRuntime.1.6_6000.242.101.0_x64__8wekyb3d8bbwe
                                        创建流读取器。
2024/9/20 10:51:52        10002        正在为程序包 Richasy.BiliCopilot_2.2409.5.0_x64__g7ew4fxhv1f46 上的 Add 操作创建
                                       复原文件 C:\ProgramData\Microsoft\Windows\AppRepository\348e1eee-4be6-4e11-a371-
                                       2abd09abbe9b_S-1-5-21-4280667454-3791491049-4227926430-1002_2.rslc。
2024/9/20 10:51:52        607          已从队列中取消程序包 Richasy.BiliCopilot_2.2409.5.0_x64__g7ew4fxhv1f46 的部署 Ad
                                       d 操作，并且正在为用户 S-1-5-21-4280667454-3791491049-4227926430-1002 运行该部署
                                       。
2024/9/20 10:51:52        854          已成功添加以下待处理的 URI:  file:///E:/Downloads/BiliCopilot.UI_2.2409.5.0_x64/
                                       BiliCopilot.UI_2.2409.5.0_x64.msix file:///E:/Downloads/BiliCopilot.UI_2.2409.5.
                                       0_x64/Dependencies/x64/Microsoft.WindowsAppRuntime.1.6.msix。
2024/9/20 10:51:52        629          找不到程序包 Richasy.BiliCopilot_2.2409.5.0_x64__g7ew4fxhv1f46 适用的跨体系结构
                                       框架。将仅安装具有匹配的体系结构框架的程序包。
2024/9/20 10:51:52        855          已完成解决操作列表。DeploymentRequest 操作列表:  addPackageList: Microsoft.Windo
                                       wsAppRuntime.1.6_6000.242.101.0_x64__8wekyb3d8bbwe Richasy.BiliCopilot_2.2409.5.
                                       0_x64__g7ew4fxhv1f46。
2024/9/20 10:51:52        626          用户 S-1-5-21-4280667454-3791491049-4227926430-1002 对程序包 Richasy.BiliCopilot
                                       _2.2409.5.0_x64__g7ew4fxhv1f46 的部署 Add 操作已重新排队。
2024/9/20 10:51:52        607          已从队列中取消程序包 Richasy.BiliCopilot_2.2409.5.0_x64__g7ew4fxhv1f46 的部署 Ad
                                       d 操作，并且正在为用户 S-1-5-21-4280667454-3791491049-4227926430-1002 运行该部署
                                       。
2024/9/20 10:51:52        854          已成功添加以下待处理的 URI:  file:///E:/Downloads/BiliCopilot.UI_2.2409.5.0_x64/
                                       BiliCopilot.UI_2.2409.5.0_x64.msix file:///E:/Downloads/BiliCopilot.UI_2.2409.5.
                                       0_x64/Dependencies/x64/Microsoft.WindowsAppRuntime.1.6.msix。
2024/9/20 10:51:52        405          错误 0x80070003: 从位置 AppxManifest.xml 中打开文件失败，错误为: 系统找不到指定
                                       的路径。
                                       。
2024/9/20 10:51:52        402          错误 0x80070003: 从位置 AppxManifest.xml 中读取部件清单(manifest)失败，错误为:
                                       系统找不到指定的路径。
                                       。
2024/9/20 10:51:52        486          通过 API Package name from manifest path: Microsoft.WindowsAppRuntime.1.6_6000.2
                                       42.101.0_x64__8wekyb3d8bbwe; Package family name: Microsoft.WindowsAppRuntime.1.
                                       6_8wekyb3d8bbwe; Package: Microsoft.WindowsAppRuntime.1.6_6000.242.101.0_x64__8w
                                       ekyb3d8bbwe, Users: S-1-5-21-4280667454-3791491049-4227926430-1002 3 ; Package f
                                       older doesn't exist 进行的 AppX 部署操作失败，错误为 0x80070490
2024/9/20 10:51:52        605          上次达到的成功状态为 Indexed。在达到下一状态 Resolved 之前发生故障。hr: 0x80073C
                                       F0
2024/9/20 10:51:52        401          从  (BiliCopilot.UI_2.2409.5.0_x64.msix)  使用程序包 Richasy.BiliCopilot_2.2409.
                                       5.0_x64__g7ew4fxhv1f46 中的目标卷 C: 执行的部署 Add 操作失败，错误为 0x80073CF0
                                       。有关诊断应用部署问题的帮助，请参阅 http://go.microsoft.com/fwlink/?LinkId=2351
                                       60。
2024/9/20 10:51:52        404          程序包 Richasy.BiliCopilot_2.2409.5.0_x64__g7ew4fxhv1f46 的 AppX 部署操作失败，
                                       错误为 0x80073CF0。此失败的具体错误文本是: 错误 0x80070003: 从位置 AppxManifest.
                                       xml 中打开文件失败，错误为: 系统找不到指定的路径。
                                       。
2024/9/20 10:51:52        471          错误 0x12C: 删除文件 \\?\C:\Program Files\WindowsApps\Deleted\Microsoft.Windows.
                                       DevHome_0.1701.597.0_x64__8wekyb3d8bbwe8edb420a-71e5-4e33-964e-4910ec1fe391\ref\
                                       netstandard.dll 失败。
2024/9/20 10:51:52        471          错误 0x12C: 删除文件 \\?\C:\Program Files\WindowsApps\Deleted\Microsoft.Windows.
                                       DevHome_0.1701.597.0_x64__8wekyb3d8bbwe8edb420a-71e5-4e33-964e-4910ec1fe391\ref\
                                       System.Runtime.CompilerServices.Unsafe.dll 失败。
2024/9/20 10:51:52        471          错误 0x12C: 删除文件 \\?\C:\Program Files\WindowsApps\Deleted\Microsoft.Windows.
                                       DevHome_0.1701.597.0_x64__8wekyb3d8bbwe8edb420a-71e5-4e33-964e-4910ec1fe391\ref\
                                       System.Security.Cryptography.Algorithms.dll 失败。

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你的设备上是不是没有 Microsoft Store?

**Comment by nanakura** [comment]
> 你的设备上是不是没有 Microsoft Store?

![image](https://github.com/user-attachments/assets/124d38d3-b6f4-4044-b329-b499c23d30cf)

**Comment by Richasy** [comment]
那根据错误信息，你直接进安装包解压的 `Dependencies` 目录，打开 `x64`，双击安装 `Microsoft.WindowsAppRuntime.1.6.msix` 试试。

装完之后再跑 ps1 脚本

**Comment by nanakura** [comment]
> 那根据错误信息，你直接进安装包解压的 `Dependencies` 目录，打开 `x64`，双击安装 `Microsoft.WindowsAppRuntime.1.6.msix` 试试。
> 
> 装完之后再跑 ps1 脚本

在微软商店装好了，能用就行。。
