### ISSUE TITLE
[Bug] 在三倍速播放视频时出现闪退

### ISSUE THREAD

**Issue by ertutio** [Richasy/Bili.Copilot#610]
### Bug 描述

在三倍速播放视频时出现闪退情况，播放器选择的是内置mpv播放器

### 复现问题的步骤

```plain text
将视频速度设置为三倍速后，能正常播放很短的时间，随后便会闪退，错误日志已经附上
```

### 预期行为

1

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [X] 其它 (需注明)

### 其它系统版本

win11专业工作站版22635.4145Windows Feature Experience Pack 1000.22700.1039.0

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-09-20.log](https://github.com/user-attachments/files/17069936/applog.2024-09-20.log)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
请使用新的岛播放器观看视频，如果该问题依然出现，请再打开它
