### ISSUE TITLE
[Bug] 隐藏右边栏视频消失

### ISSUE THREAD

**Issue by CnTripto** [Richasy/Bili.Copilot#613]
### Bug 描述

视频播放中隐藏右侧，视频播放界面只显示弹幕和声音，没有画面。恢复侧边栏有的视频会恢复，有的不会，将页面向下滚动视频会恢复，似乎和视频高度有关。

### 复现问题的步骤

```plain text
1. 打开应用
2. 随便找一个视频
3. 滚动滚轮保持页面在顶部
4. 点击隐藏侧栏按钮
```

### 预期行为

视频应该正常播放

### 截图

**隐藏前：**
![Snipaste_2024-09-20_15-25-09](https://github.com/user-attachments/assets/f28fb602-5b58-4eda-972b-6a07023cc186)

**隐藏后：**
![Snipaste_2024-09-20_15-25-20](https://github.com/user-attachments/assets/ba933270-6225-43c4-9e90-f050e14a1974)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
关掉弹幕然后重新开启即可
