### ISSUE TITLE
[Bug] 空格键继续/暂停播放功能在点击任务栏图标缩小窗口时会一直启用

### ISSUE THREAD

**Issue by sekurodesu** [Richasy/Bili.Copilot#62]
### Bug 描述

如题，用alt+tab切换窗口和使用视频窗口右上角自带的缩小按钮则不会出现该BUG

### 复现问题的步骤

```plain text
1、打开应用
2、打开视频
3、点击任务栏的视频图标缩小窗口
4、此时在其他窗口按空格键，会暂停/继续视频，导致在当前页面的空格键失效
```

### 预期行为

希望修复此BUG

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows10 21H2（Build 19044）

### 运行设备

桌面/台式机

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
我不太明白你说的 `任务栏的视频图标` 是什么，有截图吗？

**Comment by sekurodesu** [comment]
![QQ图片20230810220749](https://github.com/Richasy/Bili.Copilot/assets/51750095/83f4b018-106d-4261-a118-f1ab0e5aa818)
就是任务栏那里的图标啊

**Comment by sekurodesu** [comment]
好的辛苦了

**Comment by Richasy** [comment]
没有复现，可能已经修复了？暂时先关闭这个bug
