### ISSUE TITLE
[Bug] 播放画面异常消失

### ISSUE THREAD

**Issue by zui872902726** [Richasy/Bili.Copilot#625]
### Bug 描述

在昨天发布的最新版本中出现新BUG，播放竖屏视频时，只要任意操作了播放界面，当你再次将左侧视频页拖到顶时画面就会消失（例如视频播放后暂停就能稳定触发bug），横屏视频没有此问题
![PixPin_2024-09-21_12-23-12](https://github.com/user-attachments/assets/94ea3dfc-cf2f-45eb-9c85-1ce5a7fdeb84)

### 复现问题的步骤

```plain text
1.启动哔哩助理
2.播放一个竖屏视频
3.暂停播放（或其他操作）
4.画面消失（仅限于画面触顶，如果用鼠标滚轮向下滚，画面仍会出现）
```

### 预期行为

解决bug

### 截图

![PixPin_2024-09-21_12-23-12](https://github.com/user-attachments/assets/d3c4eca4-61d6-411f-9795-43b1151e6b17)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
这是一个弹幕组件的问题，目前临时解决方案是关闭弹幕重新打开

**Comment by mchhhhhhh** [comment]
对对对，我也是昨天在开弹幕的时候，画面就消失了
