### ISSUE TITLE
[Feature] 稍后再看，我的收藏，历史外置

### ISSUE THREAD

**Issue by sae1025** [Richasy/Bili.Copilot#628]
### 问题描述

很多盗版课程都将收藏代替为稍后再看来再次观看。因为收藏会提高视频热度，导致视频下架。在手机设置了视频为稍后再看，外置稍后再看能更快寻回，网页版也将收藏，历史外置，bilibili evolevd，也提供了将稍后再看外置的选项。

### 描述解决方案

希望能将稍后再看，我的收藏，历史放在左侧栏里

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
做了的，下个版本发

**Comment by sae1025** [comment]
> 做了的，下个版本发

我还发现，在评论区里，如果评论没有全部显示，在打开评论后也无法全部显示，需在点开
![image](https://github.com/user-attachments/assets/89668c6d-7457-410a-81a1-a67dcd1eb713)
