### ISSUE TITLE
[Feature] 一些建议

### ISSUE THREAD

**Issue by mchhhhhhh** [Richasy/Bili.Copilot#629]
### 问题描述

1.建议增加能够使用空格控制视频暂停的功能
2.使用上下方向键调节音量时，像原来一样有提示

### 描述解决方案

1.建议增加能够使用空格控制视频暂停的功能
2.使用上下方向键调节音量时，像原来一样有提示

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
1. 支持空格键暂停，如果你的没有生效，可能是焦点转移了，点击一下播放区域即可。
2. 目前过多的UI元素盖在播放区域上可能引起崩溃，我正在调查原因，但目前暂无打算。

P.S. 不要使用 `一些建议` 这种表述，一个建议一个 issue

**Comment by mchhhhhhh** [comment]
收到，谢谢大佬回复，下次会注意的
