### ISSUE TITLE
[Feature] 希望添加默认选择字幕功能

### ISSUE THREAD

**Issue by simuleite** [Richasy/Bili.Copilot#630]
### 问题描述

每次想要加载字幕，都需要 点击导航栏CC字幕 -> 选择字幕 -> 点击空白处关闭字幕选择框 3步才能完成。
![图片](https://github.com/user-attachments/assets/bf66d105-b360-40ac-9b3f-34dbca1e0df3)
希望能够在加载视频，默认选择一个字幕，减少点击次数。不需要字幕时，关闭“显示字幕”按钮即可。

### 描述解决方案

加载视频时，默认选择一个字幕。
如果不需要字幕，关闭“显示字幕”按钮。

### 附加信息

每次加载视频，自动框选一个字幕。即打开一个视频，字幕默认是蓝色框选状态。
![图片](https://github.com/user-attachments/assets/afa58f1a-83a7-403b-a196-0260d98bc58c)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
AI字幕不会自动加载的，如果有上传的字幕会自动选择
