### ISSUE TITLE
[Feature] 进度条只在鼠标移至视频下方时出现

### ISSUE THREAD

**Issue by STU-TAN** [Richasy/Bili.Copilot#651]
### 问题描述

鼠标只要经过视频进度条就出现太影响观看了。

### 描述解决方案

进度条只在鼠标移至视频下方时出现

### 备选方案

锁定视频，不出现进度条，解锁再恢复出现。

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
现在可以在设置/播放器控制中调整播放控制器的弹出方式，你可以更改为手动弹出
