### ISSUE TITLE
[Feature] 希望能够在播放webdav内视频时能够选择视频的音轨和字幕轨

### ISSUE THREAD

**Issue by YUNDAN21** [Richasy/Bili.Copilot#653]
### 问题描述

在看来自webdav中的影片时，使用外部mpv播放器可以读取、选择对应的字幕轨和音频轨，但是使用内部自带mpv播放器似乎是禁用了字幕轨，在观看相同影片并不能看到视频内部自带字幕

### 描述解决方案

因此我希望可以能够在哔哩助理内部自带的mpv播放器中添加选择音频轨和字幕轨的功能，感谢作者大大

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
目前不会在 webdav 模块中追加新的功能，这只是初步实验，后续会分离出完整应用提供完善的支持

**Comment by YUNDAN21** [comment]
> 目前不会在 webdav 模块中追加新的功能，这只是初步实验，后续会分离出完整应用提供完善的支持

好的，感谢大佬回复，期待大佬的新作品
