### ISSUE TITLE
播放器类型选择为【原生】无法播放一直处于加载住哪个·状态

### ISSUE THREAD

**Issue by songchunyang0213** [Richasy/Bili.Copilot#669]
### Bug 描述

![PixPin_2024-09-27_15-35-41](https://github.com/user-attachments/assets/10f36f00-dca9-4a7f-89b5-d0be173c7d26)
CPU ADM      GPU 3060 
原生-无法播放视频一直加载中请稍后
mpv-有声音无画面（这个我了解）
网页-正常
想问一下为何什么原生无法播放啊，不想用网页的模式

### 复现问题的步骤

```plain text
使用原生模式无法播放时视频
```

### 预期行为

原生播放模式正常播放

### 截图

![PixPin_2024-09-27_15-35-41](https://github.com/user-attachments/assets/386420e9-cc09-4519-9c40-f6169fcf4402)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
请使用新的`岛播放器`播放视频

**Comment by songchunyang0213** [comment]
已解决感谢感谢
