### ISSUE TITLE
弹幕显示区域不完整

### ISSUE THREAD

**Issue by Srythm** [Richasy/Bili.Copilot#673]
### Bug 描述

2.2409.7.0版本 播放器：原生 在播放视频时，视频窗口左右边缘与弹幕显示范围不匹配

### 复现问题的步骤

```plain text
1.打开应用
2.点击播放视频
```

### 预期行为

弹幕显示范围与视频窗口一致

### 截图

![mmexport1727431619822](https://github.com/user-attachments/assets/7be505cb-910f-4037-98b3-41b8bdad3552)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
在之前的版本中，这个是为了避免视频画面消失做的妥协，不过新版本更改了设计，应该不需要再做这种事了
