### ISSUE TITLE
[Bug] AU最新版播放报错卡死

### ISSUE THREAD

**Issue by Kannkinnu** [Richasy/Bili.Copilot#685]
### Bug 描述

商店自动更新版本，播放视频   报错  exception processing message 0xc0000005 - unexpected parameters
CPU   8845HS

### 复现问题的步骤

```plain text
最新版播放视频
```

### 预期行为

正常使用

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
可以先在设置中的播放行为设置里切换到原生播放器，等待后续修复
