### ISSUE TITLE
[Bug] AI接入失败

### ISSUE THREAD

**Issue by feifei2005** [Richasy/Bili.Copilot#698]
### Bug 描述

向讯飞星火大模型申请数据时返回空信息

### 复现问题的步骤

```plain text
正确添加讯飞星火的API参数后，无法使用总结视频等AI功能
```

### 预期行为

正常总结视频内容

### 截图

![Uploading image.png…]()

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-09-28.log](https://github.com/user-attachments/files/17174827/applog.2024-09-28.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
该问题已经在2.2410.2.0中修复，商店应该是今天更新
