### ISSUE TITLE
[Bug] 岛新窗口播放视频有闪退

### ISSUE THREAD

**Issue by STU-TAN** [Richasy/Bili.Copilot#702]
### Bug 描述

岛、新窗口播放、闪退

### 复现问题的步骤

```plain text
发生一次，暂时不知道如何复现
```

### 预期行为

正常播放

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 日志记录

[applog.2024-09-29.log](https://github.com/user-attachments/files/17178338/applog.2024-09-29.log)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
新的版本 2.2410.3.0 已经可以在商店更新，请使用新版本，观察一下是否还会出现播放闪退的问题？
