### ISSUE TITLE
[Bug] 展开评论被视频遮挡

### ISSUE THREAD

**Issue by STU-TAN** [Richasy/Bili.Copilot#703]
### Bug 描述

看评论被视频遮挡
![image](https://github.com/user-attachments/assets/f86dad8c-a3a8-4a0d-b873-e77fc0f78c5e)

### 复现问题的步骤

```plain text
暂无
```

### 预期行为

正常观看

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
与 #691 重复，已修复

**Comment by STU-TAN** [comment]
![屏幕截图 2024-09-29 155057](https://github.com/user-attachments/assets/42e25b6e-cf3e-4d94-9707-c44e9838f3bd)
还卡住了

**Comment by Richasy** [comment]
你可以试着下载 Github Release 中的 2.2410.2.0 版本，这些问题都已经修复了。商店版本估计要到明天才会推送
