### ISSUE TITLE
[Bug] 视频突然错位

### ISSUE THREAD

**Issue by STU-TAN** [Richasy/Bili.Copilot#706]
### Bug 描述

![屏幕截图 2024-09-29 165452](https://github.com/user-attachments/assets/478232d7-9679-49d0-bb39-0a35bccc5aab)
![屏幕截图 2024-09-29 165458](https://github.com/user-attachments/assets/18a356a9-cba7-4d9d-99ac-261ee7a29e48)

### 复现问题的步骤

```plain text
暂无
```

### 预期行为

正常播放

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 日志记录

[applog.2024-09-29.log](https://github.com/user-attachments/files/17178663/applog.2024-09-29.log)

### 备注

有视频太大了等压小了在上传

### 人人为我，我为人人

None

**Comment by STU-TAN** [comment]
https://github.com/user-attachments/assets/f7bac8a2-3cdd-43bb-9e0c-25de01bf6252


https://github.com/user-attachments/assets/181eee75-1396-4b16-8ee0-bd9c41ad6be4

**Comment by Richasy** [comment]
是播放过程中突然出现的吗？

**Comment by STU-TAN** [comment]
点击播放，新窗口出来就这样。

**Comment by Richasy** [comment]
确认使用的是2.2410.2.0的版本吗

**Comment by STU-TAN** [comment]
确认

**Comment by STU-TAN** [comment]
不过，下午到现在，不过就出现一次。
