### ISSUE TITLE
[Bug] 弹幕几次关闭开启后无法正常显示

### ISSUE THREAD

**Issue by AllesUgo** [Richasy/Bili.Copilot#714]
### Bug 描述

弹幕几次关闭开启后无法正常显示

### 复现问题的步骤

```plain text
打开视频番剧等，将弹幕关闭打开几次重复后弹幕不显示
```

### 预期行为

正常显示

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
Win2D 的渲染有时候会莫名其妙地中断，这个 PR 只能降低复现概率，如果仍出现没有弹幕的情况，可以再开关一次
