### ISSUE TITLE
收藏夹的内容多的话打开就会卡死

### ISSUE THREAD

**Issue by Strivy-ZSY** [Richasy/Bili.Copilot#715]
### Bug 描述

还有一些地方，比如头像多点几次就会卡死

### 复现问题的步骤

```plain text
1.点击几次头像
或者
2.点开自己的我的收藏，往下翻几下
```

### 预期行为

希望能流畅运行，我的电脑是32线程的，所以我确信不是cpu性能的问题

### 截图

![image](https://github.com/user-attachments/assets/fd5e73ab-b112-4abc-b9ed-da52dfe0fbaa)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 其它系统版本

22631.4249

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
请更新到最新版本，UI 无响应的问题应该已经修复了
