### ISSUE TITLE
[Bug] log报 core : CUDA hwdec only works with OpenGL or Vulkan backends错误

### ISSUE THREAD

**Issue by zycha** [Richasy/Bili.Copilot#719]
### Bug 描述

2.2410.3.0版本更新后使用下图配置，log一直会报错，播放遇到进度条时间不正常，不确定是否与报错存在关联
![配置图](https://github.com/user-attachments/assets/b401ac46-ee13-4daa-b727-9d11f8029e9a)
![播放进度条异常](https://github.com/user-attachments/assets/44b88fd6-6777-44bf-afc6-3f3d6d0cedb3)

### 复现问题的步骤

```plain text
1.打开应用
2.进入设置
3.播放行为主要配置如下：
 - 播放器类型：岛(测试)
 - 解码偏好:NVDEC硬解(Nvdia 显卡)
4.播放视频
```

### 预期行为

1.log不报|Error|core: CUDA hwdec only works with OpenGL or Vulkan backends.
2.进度条不出现异常

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-09-30.log](https://github.com/user-attachments/files/17189201/applog.2024-09-30.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
1. 尝试更新显卡驱动
2. 切换回自动或D3D11

**Comment by zycha** [comment]
1.反馈前驱动已是最新561.09
2.切换回自动，目前log不再报此错误
