### ISSUE TITLE
[Bug] 点开视频评论有概率卡死/闪退

### ISSUE THREAD

**Issue by gnayoahnehc** [Richasy/Bili.Copilot#723]
### Bug 描述

播放视频时 点击评论会卡死 然后无响应  点击推荐视频则会闪退
![23333](https://github.com/user-attachments/assets/a91cbf4b-fa41-4b08-943c-0eaf261ae6b6)

### 复现问题的步骤

```plain text
随便点击一个视频查看 然后点击评论 就会卡住 这时点击鼠标会失效 过几秒就会出现程序未响应
如果是点击推荐视频则会立刻闪退
```

### 预期行为

修复bug 目前无法正常使用

### 截图

![23333](https://github.com/user-attachments/assets/42e3a107-2877-447b-bfe0-00bccd5b056f)
![3333](https://github.com/user-attachments/assets/7295bfe7-3821-4909-8737-78d340e3f044)
![w](https://github.com/user-attachments/assets/7b0a13bd-60a9-4db7-910e-94ded1e956cd)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-09-18.log](https://github.com/user-attachments/files/17193001/applog.2024-09-18.log)
[applog.2024-09-19.log](https://github.com/user-attachments/files/17193002/applog.2024-09-19.log)
[applog.2024-09-21.log](https://github.com/user-attachments/files/17193003/applog.2024-09-21.log)
[applog.2024-09-22.log](https://github.com/user-attachments/files/17193005/applog.2024-09-22.log)
[applog.2024-09-24.log](https://github.com/user-attachments/files/17193006/applog.2024-09-24.log)
[applog.2024-09-25.log](https://github.com/user-attachments/files/17193007/applog.2024-09-25.log)
[applog.2024-09-28.log](https://github.com/user-attachments/files/17193008/applog.2024-09-28.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
1. 尝试更新到最新版本，并使用岛播放器播放视频。
2. 确认当前系统的缩放是否被调整为了一个自定义值（比如 115% 这种需要手动输入的缩放比例）

**Comment by gnayoahnehc** [comment]
已更新版本 问题解决👍👍👍



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月1日(周二) 上午9:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Richasy/Bili.Copilot] [Bug] 点开视频评论有概率卡死/闪退 (Issue #723)




  
尝试更新到最新版本，并使用岛播放器播放视频。
 
确认当前系统的缩放是否被调整为了一个自定义值（比如 115% 这种需要手动输入的缩放比例）
