### ISSUE TITLE
[Bug] 弹幕卡顿

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Copilot#729]
### Bug 描述

新版本问题，在[2.2409.4.0](https://github.com/Richasy/Bili.Copilot/releases/tag/v2.2409.4.0)并无此问题
表现为弹幕大概隔着几秒钟略微卡一下

### 复现问题的步骤

```plain text
1.打开应用
2.打开视频
```

### 预期行为

正常行为

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
可以看下最新版本 2.2410.5.0 是否还有这个问题
