### ISSUE TITLE
[Bug]（UI）主窗口搜索页标题栏与返回按钮冲突

### ISSUE THREAD

**Issue by MSEDGE-CORE** [Richasy/Bili.Copilot#73]
### Bug 描述

主窗口搜索页标题栏与返回按钮冲突，使返回按钮无法点击。

### 复现问题的步骤

```plain text
1.打开应用
2.点击搜索框
3.输入“云之幻”
4.点击左上角的左上角部分
```

### 预期行为

点击左上角时应返回而不是打开标题栏右键菜单

### 截图

![image](https://github.com/Richasy/Bili.Copilot/assets/74437699/519cff08-56e7-4b8f-a051-4cdd5c5eca1c)
![image](https://github.com/Richasy/Bili.Copilot/assets/74437699/594c88ea-5d93-40cd-ab4d-361bc9b3961b)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 Beta Build 22631

### 运行设备

桌面/台式机, 桌面/平板或笔记本, ARM64 设备

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这个暂时没找到原因，在按钮顶部有大概8x8像素的区域不可点击，其它区域可以。如果要准确返回，目前可以使用快捷键 `Backspace` 来退回上一页面
