### ISSUE TITLE
使用岛播放视频时，有几率暂停按钮和进度条无效的情况

### ISSUE THREAD

**Issue by songchunyang0213** [Richasy/Bili.Copilot#730]
### Bug 描述

播放器类型使用【岛（测试）】播放视频时有小概率：
1、暂停按钮点击无反应
2、视频正在播放，但进度条始终显示为00:00，且不可拖动

### 复现问题的步骤

```plain text
1、打开应用
2、播放视频
3、问题出现
```

### 预期行为

进度条功能正常
播放按钮功能正常

### 截图

![Uploading PixPin_2024-10-01_13-19-38.gif…]()
![Uploading PixPin_2024-10-01_13-19-16.png…]()

### 应用来源

- [x] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
可以尝试右键播放区域，然后选择重载。该问题应该可以在下个版本得到修复
