### ISSUE TITLE
建议添加折叠分类区

### ISSUE THREAD

**Issue by songchunyang0213** [Richasy/Bili.Copilot#731]
### 问题描述

![PixPin_2024-10-01_13-35-23](https://github.com/user-attachments/assets/76d3d17d-a0c3-4759-b115-293719f7e9b5)

### 描述解决方案

建议添加可以折叠或者隐藏

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
鼠标移到分割线中间，自有折叠按钮出现
