### ISSUE TITLE
[Bug] 播放器无法正常消失

### ISSUE THREAD

**Issue by Tirehar** [Richasy/Bili.Copilot#735]
### Bug 描述

在经过之前版本对播放器消失问题的修复后，播放器在多数情况下都可以正常消失，但唯独指针从视频区域的下方直接移出软件窗口时，播放器无法消失

### 复现问题的步骤

```plain text
1. 打开任意视频
2. 将指针从视频区域下方移出窗口
3. 问题出现
```

### 预期行为

指针从视频区域下方移出窗口时播放器可以正常消失

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你说的是播放控制器吗？暂时无法复现这个问题，它可能不会立即消失，但过2-3秒左右就会消失，如果你的播放控制器显示模式是`自动`的话

**Comment by Richasy** [comment]
目前推荐使用岛播放器，原生播放器不再积极更新，只作为回退方案的一种存在

**Comment by Tirehar** [comment]
> 目前推荐使用岛播放器，原生播放器不再积极更新，只作为回退方案的一种存在

明白了，但我个人不太喜欢这个延迟2-3秒消失，这是bug还是刻意设计呢，希望有办法可以修改为立即消失
