### ISSUE TITLE
[Bug] 在使用N卡的情况下，使用NVDEC硬解 时视频黑屏

### ISSUE THREAD

**Issue by xelr233** [Richasy/Bili.Copilot#744]
### Bug 描述

在使用N卡的情况下，使用NVDEC硬解 时视频黑屏

### 复现问题的步骤

```plain text
1. 确认显卡为N卡（笔记本确认打开独显直连）
2. 在设置里使用内置的mpv 播放器
3. 修改解码偏好为 NVDEC 硬解
4. 播放视频
```

### 预期行为

正常播放

### 截图

![image](https://github.com/user-attachments/assets/e683a893-be32-4afa-8c39-4543310c9db8)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

无日志产生

### 备注

显卡为4060 laptop

### 人人为我，我为人人

None

**Comment by wsndshx** [comment]
`Windows 10 (Build 19041 - 19045)` 下出现同样的情况，使用的显卡为2060，安装来源 `微软商店（Microsoft Store）`
![设置页](https://github.com/user-attachments/assets/5d66769e-8e3d-4b48-9a8b-16910f0ccf21)
![播放黑屏](https://github.com/user-attachments/assets/2aea8896-efbc-49f4-8bb0-5d54c18fb274)
同时日志记录中并未出现播放或解码相关的异常信息。

**Comment by Richasy** [comment]
驱动是否更新到了最新？

**Comment by yjr815jun** [comment]
我也同样的情况。只有声音
显卡：2080S  驱动最新的GAME驱动565.90

**Comment by Richasy** [comment]
下个版本发布
