### ISSUE TITLE
[Feature] 改进cc字幕的样式

### ISSUE THREAD

**Issue by nanakura** [Richasy/Bili.Copilot#746]
### 问题描述

![image](https://github.com/user-attachments/assets/f75973a3-70a7-4aea-a2fe-2483b379b557)
cc字幕样式有一些缺陷：字幕框的圆角导致字幕边缘的字母与字幕框紧贴，字幕的字号也过小

### 描述解决方案

![image](https://github.com/user-attachments/assets/d8a0ea6e-103f-4617-b59f-ef54922013da)
更大的字号，合理的padding

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你是否没更新到最新版本（2.2410.5.0）？该问题在这个版本中修复了
