### ISSUE TITLE
[Bug] 弹幕开关不稳定

### ISSUE THREAD

**Issue by ZzzzRyan** [Richasy/Bili.Copilot#747]
### Bug 描述

在播放视频时开关弹幕的效果不稳定，有时关闭了弹幕后就无法打开了（一定概率）。

其中比较突出的是，弹幕的开关貌似和视频的暂停与否存在着一定的、不可知的联系。例如，当我在暂停视频时点击按钮关闭弹幕，开始播放后再点击按钮打开弹幕，弹幕未能出现，重载视频依旧未能解决。

### 复现问题的步骤

```plain text
> 这两个复现步骤对我而言是可以稳定复现的，不确定其他人怎么样

复现1：
1. 点击一个流行的、弹幕较多的视频（初始时弹幕处于打开状态）；
2. 暂停播放视频；
3. 点击按钮关闭弹幕；
4. 开始播放视频；
5. 点击按钮开启弹幕；
6. 弹幕未出现；
7. 右键视频点击重载，弹幕依旧未能出现。

复现2：
1. 打开本视频：https://www.bilibili.com/video/av41495631
2. 点击按钮关闭弹幕；
3. 点击按钮开启弹幕；
4. 弹幕未出现；
5. 右键视频点击重载，弹幕依旧未能出现。
```

### 预期行为

弹幕开关按钮稳定。

### 截图

https://github.com/user-attachments/assets/46006819-77d3-4b1a-a675-e4d0845fd1cf

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

无当日日志

### 备注

本机CPU：AMD Ryzen 9 7940HX
本机独显：NVIDIA GeForce RTX 4060
电脑设置中图形首选项为哔哩助理选择了“高性能”，运行在独显上。

哔哩助理版本：2.2410.5.0
哔哩助理播放器：岛（MPV）
哔哩助理解码偏好：逐一测试过，皆能复现

### 人人为我，我为人人

我更擅长发现问题

**Comment by clover-yan** [comment]
我在 Windows 10 和助理 2.2410.5.0 上遇到了一样的问题。
