### ISSUE TITLE
[Bug] 在 收藏/稍后再看/历史记录 页面中点击正处于的左侧选项，顶部导航栏显示不刷新

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Copilot#751]
### Bug 描述

首先是这样
![image](https://github.com/user-attachments/assets/8976f11f-93cf-4276-b8bf-7721d1fd60e4)
然后点一下
![image](https://github.com/user-attachments/assets/d65a3424-e80f-4717-904e-92819c2ccb7c)
就会发现
![image](https://github.com/user-attachments/assets/2884ab8b-7f40-4a45-bc7c-f53e435c4856)

### 复现问题的步骤

```plain text
1.打开应用
2.选择任意左侧栏目
3.打开收藏/稍后再看/历史记录中任意一个
4.再次点击选中栏目
5.复现
```

### 预期行为

正常

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Ziphyrien** [comment]
还真是，你不说，我都没发现
