### ISSUE TITLE
视频字体乱码

### ISSUE THREAD

**Issue by Strivy-ZSY** [Richasy/Bili.Copilot#753]
### Bug 描述

视频的标题字体乱码
![image](https://github.com/user-attachments/assets/0b10cfe0-9091-45fc-a59e-cdf9c37a60ed)
应该显示的原本字体如下
![image](https://github.com/user-attachments/assets/9c6a868d-eebb-4c71-b615-cb0b08300c49)

### 复现问题的步骤

```plain text
https://www.bilibili.com/video/av413729561
看看这个视频就可以
```

### 预期行为

期望显示的是正确的文字

### 截图

![image](https://github.com/user-attachments/assets/8774ef70-7da3-4c12-8c16-133007a8d0a9)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 其它系统版本

22631.4249

### 人人为我，我为人人

None

**Comment by Strivy-ZSY** [comment]
感谢您的优化，以及鸣谢🤗🥺🤓👍

**Comment by Richasy** [comment]
这不是软件的问题，是该作者修改了视频合集内的标题，和视频标题并不一致，网页上就是无法识别的乱码：

![image](https://github.com/user-attachments/assets/b45686a8-2a49-4f37-b737-6a006dcc2a11)

**Comment by Strivy-ZSY** [comment]
好滴，抱歉，前面我没发现，非常感谢您！❤️🤗
