### ISSUE TITLE
感觉像是堆栈溢出

### ISSUE THREAD

**Issue by Strivy-ZSY** [Richasy/Bili.Copilot#756]
### Bug 描述

系统蓝屏，感觉像是网络数据爬取还是什么的问题，抱歉，我不太懂

### 复现问题的步骤

```plain text
当软件在后台挂上半小时左右，且不播放视频时，电脑其他软件视频声音会消失，相继产生网络卡顿，稍等5-10分钟左右系统会蓝屏。系统日志显示错误为：“服务 GameInput Service 意外停止。这发生了 6 次。”
```

### 预期行为

期望正常，当然，如果我在其他软件没有声音的时候，关闭该软件，等待2-3分钟又可以正常上网，恢复声音，不蓝屏

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
1. 请提交应用日志
2. 系统出现蓝屏，声音失常等问题应该和软件关系不大，在不对软件做任何操作，且没有播放视频的情况下，应用内唯一定时运行的只有尝试获取最新动态。你要是有这方面的疑虑，可以在设置里关掉动态通知。

**Comment by Strivy-ZSY** [comment]
2024/10/03 22:43:23.077|Error|core: Failed to open https://xy122x228x71x30xy240eyf7yc000y212y0y1y0y30xy.mcdn.bilivideo.cn:4483/upgcxcode/11/19/507251911/507251911-1-30064.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1727966310&gen=playurlv2&os=mcdn&oi=1863464213&trid=00002786aa3288e74a479760ddea48e96e63u&mid=1767287699&platform=pc&og=cos&upsig=38eea83d42bd7cb6e8ccda1a906d06e5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&mcdnid=50009823&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&f=u_0_0&agrr=0&bw=161469&logo=A0020000.
|
2024/10/03 22:43:23.077|Error|core: Subprocess failed: init
|
2024/10/03 22:43:23.081|Error|core: Subprocess failed: init
|
2024/10/03 22:43:23.081|Error|core: Subprocess failed: init
|
2024/10/03 22:43:23.081|Error|core: 
|
2024/10/03 22:43:23.081|Error|core: youtube-dl failed: not found or not enough permissions
|
2024/10/03 22:43:23.140|Error|core: tls: Unknown error
|
2024/10/03 22:43:24.061|Error|尝试播放音频失败.|

感谢您的解答🤗🤗🤗

**Comment by cxw620** [comment]
尝试把效率模式关了(虽然好像只能用 Process Lasso, 系统没给选项, 目前应该就浏览器有相应配置). 我 Firefox 放视频后台放久了再打开也会卡死然后 dam.sys 蓝屏, 最后拿 Process Lasso 强制关掉效率模式就没这事儿了. 大概率挂后台触发效率模式冻结内存云云.

**Comment by Strivy-ZSY** [comment]
好嘞，谢谢您！❤️我在最近一次更新后再没遇到该问题🤗但依然感谢您的建议，如果下次问题复现我会尝试您提供的方式❤️🤓
