### ISSUE TITLE
[Bug] 点击左上角的“观看历史”必闪退重启

### ISSUE THREAD

**Issue by QtHamster** [Richasy/Bili.Copilot#758]
### Bug 描述

不知道是不是我个人电脑的问题，点击左上角“观看历史”必闪退然后自动重新打开。

### 复现问题的步骤

```plain text
点击左上角“观看历史”必闪退然后自动重新打开
```

### 预期行为

修复闪退重启

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-10-04.log](https://github.com/user-attachments/files/17254374/applog.2024-10-04.log)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
尝试调整一下窗口大小或者更改系统缩放比例（特别是如果你正在使用自定义的缩放比例，那么很大概率会出现布局崩溃）

**Comment by QtHamster** [comment]
> 尝试调整一下窗口大小或者更改系统缩放比例（特别是如果你正在使用自定义的缩放比例，那么很大概率会出现布局崩溃）
感谢老哥解答，取消自定义缩放比例，已正常
