### ISSUE TITLE
[Feature] 关于视频发布时间

### ISSUE THREAD

**Issue by panda2423wre** [Richasy/Bili.Copilot#759]
### 问题描述

没有具体视频发布时间

### 描述解决方案

希望在视频流界面有具体的视频发布时间，就是b站首页的那种up名字右边的视频发布时间

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
如果你没有在视频卡片上看到发布时间，那是因为 API 没有返回对应的数据，这我无能为力
