### ISSUE TITLE
[Bug] 视频弹幕数量较多时，应用容易卡死

### ISSUE THREAD

**Issue by mchhhhhhh** [Richasy/Bili.Copilot#76]
### Bug 描述

视频弹幕数量较多时，应用容易卡死

### 复现问题的步骤

```plain text
比如这个视频BV118411X7dS
打开弹幕的情况下拖动进度条，视频缓冲过程中应用就会卡死
```

### 预期行为

优化弹幕性能（或者是视频加载时候的性能）

### 截图

![屏幕截图 2023-08-16 213821](https://github.com/Richasy/Bili.Copilot/assets/142414235/2454c3ef-ffa7-4fbc-987c-8d04b93a7aef)
![屏幕截图 2023-08-16 213757](https://github.com/Richasy/Bili.Copilot/assets/142414235/13f0add7-850c-476b-9e58-cd4bbe5c3818)

### 应用来源

- [X] Github
- [ ] AppCenter
- [ ] 其它

### 系统版本

- [ ] Windows 11 21H2 (Build 22000)
- [X] Windows 11 22H2 (Build 22621)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
试一下切换到ffmpeg，最近的一些更新应该可以缓解这个问题
