### ISSUE TITLE
[Feature] 想在设置里加一个外观选项，里面可以选择使用云母mica或者亚克力blur

### ISSUE THREAD

**Issue by System32laoma** [Richasy/Bili.Copilot#760]
### 问题描述

想在设置里加一个外观选项，里面可以选择使用云母mica或者亚克力blur，能够让用户选择这两种外观，从而达到高度自定义，比如本人认为亚克力更好看。

### 描述解决方案

https://github.com/COLORREF/QWidget-FancyUI
这里面有关于亚克力的源码

### 备选方案

https://www.bilibili.com/video/av367201835
这个是亚克力源码来源视频

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
那是 QT 的，我这个是 Windows App SDK，框架不同，不能混为一谈。

我不能直接设置窗口背景，WinUI 有自己的渲染方式，它虽然提供了 Acrylic 的背景选项，但效果很差，还不如纯色。

所以目前没有增加亚克力背景的计划
