### ISSUE TITLE
[Bug] 开启代理后关闭代理会无法加载内容

### ISSUE THREAD

**Issue by Slipstream-Max** [Richasy/Bili.Copilot#767]
### Bug 描述

起初哔哩助手正常工作。打开clash verge rev，设置为系统代理，规则模式，随后关闭代理即无法加载内容。之后试过重新打开哔哩助手也无法显示内容，无法点击任何设置和按钮。我为了正常观看必须一直挂代理才可以。

### 复现问题的步骤

```plain text
1 打开哔哩助手
2 打开clash verge
3 随意刷新哔哩助手
4 退出clash
5 刷新哔哩助手 此时无法刷新内容
6 关闭哔哩助手再打开 此时无法操作任何内容
7 打开代理 重新启动哔哩助手 此时可以正常刷新
```

### 预期行为

打开或关闭代理应该都能够正常浏览

### 截图

打开代理可显示内容
![屏幕截图(40)](https://github.com/user-attachments/assets/8a131461-be96-4446-9039-db8a5b4913e2)
关闭代理无法加载
![屏幕截图(41)](https://github.com/user-attachments/assets/b2a5d511-71d5-49b7-af52-661208cf243e)
关闭哔哩助手重新打开 无法操作
![屏幕截图(42)](https://github.com/user-attachments/assets/e9e3025d-c261-4cd4-956a-40a6fe6081b4)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

ARM64 设备

### 日志记录

[applog.2024-10-05.log](https://github.com/user-attachments/files/17265607/applog.2024-10-05.log)

### 备注

使用surface pro 11 16＋512gb
代理也是arm64的版本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
这属于系统网络层面的问题，跟应用无关

**Comment by Slipstream-Max** [comment]
好的 谢谢作者回复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月6日(周日) 上午9:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Richasy/Bili.Copilot] [Bug] 开启代理后关闭代理会无法加载内容 (Issue #767)




 
这属于系统网络层面的问题，跟应用无关
