### ISSUE TITLE
[Bug] 播放控制器的显示方式有问题

### ISSUE THREAD

**Issue by mchhhhhhh** [Richasy/Bili.Copilot#768]
### Bug 描述

播放控制器的显示方式调为自动之后，并不能自动的隐藏。问题发生频率很高。

### 复现问题的步骤

```plain text
1.播放视频。
二，开始播放。
三，将鼠标移至空白处。控制器不会消失
```

### 预期行为

播放控制器能够自动隐藏

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
下个版本发布
