### ISSUE TITLE
[Feature] 希望稍后再看列表，可以增加逆向顺序播放按钮

### ISSUE THREAD

**Issue by mchhhhhhh** [Richasy/Bili.Copilot#769]
### 问题描述

点击播放全部按钮，在列表播放中显示反向播放按钮

### 描述解决方案

点击播放全部按钮，在列表播放中显示反向播放按钮

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
我不太明白，如果你需要看之前的视频，在播放列表里点击就行了。

`播放下一个` 的使用频率远高于 `播放上一个`，目前没有计划在播放控制器里添加

**Comment by mchhhhhhh** [comment]
![image](https://github.com/user-attachments/assets/6de6566e-4ffb-47e9-88d2-871fe229b6b9)
![image](https://github.com/user-attachments/assets/14c45b2c-b1cc-43d9-bcdf-47dac1c1ae51)
就是像网页端这样的效果

**Comment by mchhhhhhh** [comment]
> 我不太明白，如果你需要看之前的视频，在播放列表里点击就行了。
> 
> `播放下一个` 的使用频率远高于 `播放上一个`，目前没有计划在播放控制器里添加

嗯嗯好的
