### ISSUE TITLE
[Feature] 希望稍后再看列表可以增加删除选项

### ISSUE THREAD

**Issue by mchhhhhhh** [Richasy/Bili.Copilot#770]
### 问题描述

就像网页端在一个视频模块的右下角有一个删除按钮

### 描述解决方案

在一个视频模块的右下角有一个删除按钮

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
右键

![image](https://github.com/user-attachments/assets/542d9af1-3529-4be6-81b9-6c3c09915ea4)
