### ISSUE TITLE
[Bug] 观看直播时，开始几秒内程序容易闪退

### ISSUE THREAD

**Issue by zelbloo** [Richasy/Bili.Copilot#772]
### Bug 描述

在观看单机游戏分区时，程序极容易闪退

### 复现问题的步骤

```plain text
1、打开直播tab
2、打开单机游戏分区
3、任意点击一个直播
4、几秒内程序会闪退
```

### 预期行为

正常播放

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2024-10-06.log](https://github.com/user-attachments/files/17268437/applog.2024-10-06.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
现在该问题应该已经修复
