### ISSUE TITLE
[Bug] ai总结视频内容时返回空响应

### ISSUE THREAD

**Issue by weijianxian** [Richasy/Bili.Copilot#789]
### Bug 描述

在视频BV1LN2YY6En6视频总结时提示返回空响应，似乎是需要的token过多

### 复现问题的步骤

```plain text
在视频BV1LN2YY6En6进行视频总结
```

### 预期行为

正常总结

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2024-10-13.log](https://github.com/user-attachments/files/17350748/applog.2024-10-13.log)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
从报错信息来看是的。

这个是服务端无法处理过长的字幕内容，你可以换用上下文窗口更大的模型。

不过有意思的是，我在尝试使用 Azure Open AI 的 gpt-4o mini 总结这个视频的时候没什么问题，所以不太确定这是不是跟模型配置有关

![image](https://github.com/user-attachments/assets/9bfd6bd1-d519-4a04-a02d-b9411733c868)
