### ISSUE TITLE
[Bug] 弹幕关闭后无法显示

### ISSUE THREAD

**Issue by AllayFocalors** [Richasy/Bili.Copilot#802]
### Bug 描述

视频播放页面中弹幕点击隐藏后再次点击显示，按钮将切换状态而视频播放器中没有出现弹幕

### 复现问题的步骤

```plain text
1. 打开app，点进一个视频
2. 点击隐藏弹幕，此时弹幕消失
3. 再次点击，此时弹幕无法出现
```

### 预期行为

应该正常出现

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
下个版本修复
