### ISSUE TITLE
[Bug] 无法播放动漫

### ISSUE THREAD

**Issue by AllayFocalors** [Richasy/Bili.Copilot#804]
### Bug 描述

在动漫播放中，视频无法正常出现，却没有加载条，怎么更改选集都没用。

### 复现问题的步骤

```plain text
1. 搜索一个动漫，点进去观看
2. 视频播放器无法正常播放，任何按钮按了都没反应，怎么切换选集都没用
```

### 预期行为

视频正常播放

### 截图

![屏幕截图 2024-10-13 175143](https://github.com/user-attachments/assets/c96acca3-5986-45a6-9d4b-f77c337b1c91)
![屏幕截图 2024-10-13 175130](https://github.com/user-attachments/assets/9875a442-d667-4da1-9f7e-6884c9448d15)

### 应用来源

- [ ] Github
- [x] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [x] 其它 (需注明)

### 其它系统版本

Windows 11 24H2 (OS内部版本 26120.1930)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
你是否为大会员？

**Comment by AllayFocalors** [comment]
不是，但是应该能试看3分钟的啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月13日 17:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Richasy/Bili.Copilot] [Bug] 无法播放动漫 (Issue #804) |

你是否为大会员？

**Comment by Richasy** [comment]
这个感觉不是很有必要……但目前非大会员是不能看会员内容的
