### ISSUE TITLE
[Bug] 视频播放1秒后闪退

### ISSUE THREAD

**Issue by TonyBlur** [Richasy/Bili.Copilot#814]
### Bug 描述

视频播放1秒后闪退，多次出现，版本号为最新的2.2410.6.0，使用系统的修复应用和重启系统无法解决该闪退情况

### 复现问题的步骤

```plain text
多次出现，不确定是否由下述步骤导致：
播放任意视频，点击小窗播放，在小窗状态中点击全屏/全窗口播放
```

### 预期行为

不闪退，正常播放视频

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [X] 其它 (需注明)

### 其它系统版本

Windows11 Dev 27723.1000

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-10-14.log](https://github.com/user-attachments/files/17371730/applog.2024-10-14.log)
[applog.2024-10-15.log](https://github.com/user-attachments/files/17371731/applog.2024-10-15.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by TonyBlur** [comment]
使用商店下载的版本也是出现相同问题了，log如下：
[applog.2024-10-15.log](https://github.com/user-attachments/files/17371823/applog.2024-10-15.log)

**Comment by DocksToBox** [comment]
我也有这个问题
