### ISSUE TITLE
[Bug] 岛播放器自定义配置在新窗口中无法播放

### ISSUE THREAD

**Issue by Ptilopsis01** [Richasy/Bili.Copilot#820]
### Bug 描述

如题，在设置为自定义时，新窗口模式也无法正常播放

### 复现问题的步骤

```plain text
将MPV的解码方式设置为自定义，然后播放任意视频
视频窗口卡死
```

### 预期行为

新窗口模式下岛播放器自定义配置可正常生效

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

未生成日志

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你的自定义配置是什么？

**Comment by Ptilopsis01** [comment]
> 你的自定义配置是什么？

和我配置应该没关系，直接空配置也能复现出来

**Comment by Richasy** [comment]
哦，那应该在另一个PR中修了，今天会发一个热修版本
