### ISSUE TITLE
[Bug] app在microsoft Store上搜索不到了QVQ

### ISSUE THREAD

**Issue by csXone** [Richasy/Bili.Copilot#827]
### Bug 描述

如下图所示..
![microsoft Store搜索哔哩助理](https://github.com/user-attachments/assets/13f97b55-6ae6-4445-b0d9-c28d544de17c)

### 复现问题的步骤

```plain text
1.打开microsoft Store 搜索哔哩助理
```

### 预期行为

出现可以安装的应用软件

### 应用来源

- [ ] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
能搜到才有问题，我可不想再收律师函。
请从项目主页里点击Microsoft Store 图片链接下载，哔哩助理没有开启公开搜素
