### ISSUE TITLE
[Bug] 岛（MPV）播放器下 热搜页面与视频页面 的遮罩关系不正确

### ISSUE THREAD

**Issue by HChaZZY** [Richasy/Bili.Copilot#840]
### Bug 描述

在播放器设置为`岛（MPV）`时，在视频播放页面点击热搜按钮弹出热搜菜单，热搜菜单会出现在播放器下方

运行环境：
Windows 笔记本
Windows 11 专业工作站版 23H2
AMD Ryzen 7 5800H with Radeon Graphics
NVIDIA GeForce RTX 3060 Laptop GPU

软件版本：Github 2.2410.7.0

### 复现问题的步骤

1. 打开应用
2. 在设置 -> 播放行为 中，设置播放器类型为`岛（MPV）`
3. 进入一个视频
4. 点击热搜按钮弹出热搜菜单

### 预期行为

热搜菜单应出现在视频播放器上方

### 截图

![image](https://github.com/user-attachments/assets/2479f6ef-6006-47c3-871e-ea5ffc8bfcc7)

应该是（这是播放器选择为`原生`的表现）：

![image](https://github.com/user-attachments/assets/56444b40-f523-44a5-b34e-0bb8598a53cd)

**Comment by Richasy** [comment]
最新版本已经修复了这个问题，请更新到2.2410.8.0
