### ISSUE TITLE
[Bug] 点开视频页面后右侧的视频合集无法切换回初始看的视频

### ISSUE THREAD

**Issue by AllesUgo** [Richasy/Bili.Copilot#841]
### Bug 描述

点开视频页面后右侧的视频合集点击其他视频后无法再切换回原本的视频
具体详见视频

### 复现问题的步骤

```plain text
点击一个包含在合集中的视频，然后切换至合集中的其他视频，再尝试切换回最初打开的视频
```

### 预期行为

能够正常切换

### 截图

https://github.com/user-attachments/assets/093e6890-6bdc-490b-8138-0a3499db0707

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
最新版本已经修复了这个问题，请更新到2.2410.8.0
