### ISSUE TITLE
[Bug] 视频页面切换视频评论内容不会切换

### ISSUE THREAD

**Issue by AllesUgo** [Richasy/Bili.Copilot#843]
### Bug 描述

视频页面切换视频评论内容不会切换，还会保留之前视频的评论内容。除此之外合集等内容好像也不会更改

### 复现问题的步骤

```plain text
1. 打开应用
2. 在推荐页面打开一个视频
3. 点击评论列表
4. 点击推荐视频并随意点击其中的一个视频
5. 再次点击评论列表
6. 发现评论内容还是上一个视频的评论内容
```

### 预期行为

正常显示评论。

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
最新版本已经修复了这个问题，请更新到2.2410.8.0

**Comment by AllesUgo** [comment]
视频合集的问题还是没有修复。点击一个包含在合集中的视频，然后在推荐视频页面切换视频，视频合集内容没有变化。
