### ISSUE TITLE
[Bug] Ai服务报错：2024/10/22 15:45:26.897|Error|总结视频内容失败|Richasy.BiliKernel.KernelException: 获取字幕元数据失败

### ISSUE THREAD

**Issue by HKLHaoBin** [Richasy/Bili.Copilot#848]
### Bug 描述

遇到的问题是与 BiliCopilot 相关的一个异常，具体表现为获取视频字幕元数据失败。错误信息表明，SubtitleClient.GetSubtitleMetasAsync 方法在尝试获取视频的字幕元数据时出现了异常，导致 EvaluateVideoAsync 方法无法正常执行。根本原因似乎是 BiliKernel 内核模块在处理字幕元数据时出现了问题。

### 复现问题的步骤

```plain text
1.
打开应用
2.
随便进入一个视频
3.
点击AI服务，视频总结或视频评价
5.
发现问题，报错：获取字幕元数据失败
```

### 预期行为

点击AI服务，视频总结或视频评价不报错

### 截图

![Clip_2024-10-22_16-24-38](https://github.com/user-attachments/assets/ca0a675b-2295-4ccc-8541-e4d0e8822850)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 其它系统版本

Windows 10 专业版 22H2 (Build 19045.4957)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-10-22.log](https://github.com/user-attachments/files/17472742/applog.2024-10-22.log)

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩助理中

**Comment by zss2430922519** [comment]
修复了吗

**Comment by Richasy** [comment]
> 修复了吗

晚上回去上传新版本，明天应该能收到商店推送了

**Comment by zss2430922519** [comment]
你好，github今晚能先收到推送吗
