### ISSUE TITLE
期望添加字幕显示功能

### ISSUE THREAD

**Issue by zss2430922519** [Richasy/Bili.Copilot#857]
### 问题描述

很多视频明明已经有了字幕文件，但是却没有显示字幕的功能，看某些视频有字幕更有思路一点

### 描述解决方案

希望能像B站客户端一样添加一个显示字幕的功能

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
本来支持字幕的，b站最近关闭了我使用的字幕接口导致字幕组件加载失败，现在已经修复，商店版本会在晚些时候推送，版本是2.2410.9.0
