### ISSUE TITLE
[Bug] 原生播放器播放影视4K画质时卡死

### ISSUE THREAD

**Issue by mpbizn** [Richasy/Bili.Copilot#864]
### Bug 描述

使用原生播放器加载或拖动支持4K画质的电影时，视频会黑屏并且播放按钮持续转圈，但普通UP主的视频中未发现此问题。

### 复现问题的步骤

```plain text
1.打开软件，切换到影视分区
2.播放任一支持4K画质的电影
3.切换到4K画质等待加载
4.出现上述行为，且4K/1080P互切换画质时会概率出现白屏现象
```

### 预期行为

影视任一画质可正常加载播放

### 截图

![image](https://github.com/user-attachments/assets/0e001969-9696-489c-b2a6-2d756824d416)
![image](https://github.com/user-attachments/assets/1109baca-1a15-4a35-bcaf-835e30f67dc5)

### 应用来源

- [ ] Github
- [x] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 备注

编码方式使用AV1和H.264均可复现，但在使用H.265时问题消失

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
建议使用岛播放器播放4K视频，原生的解码能力有限

**Comment by mpbizn** [comment]
> 建议使用岛播放器播放4K视频，原生的解码能力有限

但岛播放器不支持激发激发杜比世界画质啊
