### ISSUE TITLE
[Feature] B站大会员专属画质被取消了吗？

### ISSUE THREAD

**Issue by sekurodesu** [Richasy/Bili.Copilot#867]
### 问题描述

如题，我记得以前老版本的哔哩助理是可以直接选择1080P 60帧和4K画质的，现在选项直接灰色了，是需要设置什么吗？还是就取消这个功能了？

### 描述解决方案

希望能加上这个功能

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
哔哩助理从来不支持非大会员观看大会员视频，以前是bug，即便可选也不能切换
