### ISSUE TITLE
[Feature] 建议移除图标上的New字样

### ISSUE THREAD

**Issue by PandaFiredoge** [Richasy/Bili.Copilot#877]
### 问题描述

如题

### 描述解决方案

移除New字样，最好换回哔哩UWP的图标

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Ziphyrien** [comment]
确实，好丑

**Comment by MuLin4396** [comment]
可以找一些手机图标设计师要一个授权，可能会简单一些
