### ISSUE TITLE
[Bug] 软件无法安装

### ISSUE THREAD

**Issue by larry-xhm** [Richasy/Bili.Copilot#900]
### Bug 描述

安装软件时报错

### 复现问题的步骤

```plain text
1.下载MSIX安装包并安装
2.安装错误
or
1.使用Microsoft store安装
2.安装错误
```

### 预期行为

可以正常安装软件

### 截图

![屏幕截图 2024-11-16 212002](https://github.com/user-attachments/assets/35af49f9-28aa-425f-9d33-18c9c19d954f)
![屏幕截图 2024-11-16 211904](https://github.com/user-attachments/assets/5b2fdbce-d778-4368-9f56-a937f9d7eedc)

### 应用来源

- [X] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本, ARM64 设备

### 人人为我，我为人人

我更擅长发现问题

**Comment by Ziphyrien** [comment]
你的问题，我可以正常安装

**Comment by dodo939** [comment]
我也不能正常安装，我在微软商店里和下载msix两种办法都不能安装，后者报错和上面一样，Windows版本 Windows 11 24H2 (Build 26100)

**Comment by ongiei** [comment]
一样通过ms商店无法安装

**Comment by Ran-Yijiu** [comment]
微软商店无法安装
代码: 0x80246019

**Comment by Ziphyrien** [comment]
msix怎么可以直接双击安装，前置都没装，一群**，肯定是用脚本安装啊，怕是连安装教程都没看就直接下的吧

**Comment by Richasy** [comment]
这可能是微软商店的bug。

1. 无法从微软商店下载，可以尝试切换不同的网络环境，开启或关闭梯子。
2. 依然无法下载，可以从 Github Release 下载包，并按照仓库自述说明里的步骤，通过 install.ps1 脚本安装

**Comment by Richasy** [comment]
补充一下，商店的依赖可能没有同步更新到最新的 WinAppSDK，所以如果从商店下载有问题的同学可以尝试先手动安装最新的 1.6.2 SDK
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads
![image](https://github.com/user-attachments/assets/8112ec0b-0a64-49d7-98c7-564d4dc76443)

**Comment by binw666** [comment]
一样，我还以为是我刚安装的visual studio有冲突，还特意删了重装，还是不行

**Comment by binw666** [comment]
> 补充一下，商店的依赖可能没有同步更新到最新的 WinAppSDK，所以如果从商店下载有问题的同学可以尝试先手动安装最新的 1.6.2 SDK https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads ![image](https://private-user-images.githubusercontent.com/27713596/386919315-8112ec0b-0a64-49d7-98c7-564d4dc76443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzAzNDAsIm5iZiI6MTczMTgzMDA0MCwicGF0aCI6Ii8yNzcxMzU5Ni8zODY5MTkzMTUtODExMmVjMGItMGE2NC00OWQ3LTk4YzctNTY0ZDRkYzc2NDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3NTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MWY2NzIyYTJkNDY5NDIzYjczY2M5NWY1YTI5NjI1NDIxOWFmNWMxODE1NGQ1NWU1OTZlOWU5NTY1NTAzNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tSzqJcc1l_0MVMlsQcQ_5GSOb8A5funkptfE8dFFd1s)

安装SDK后，成功解决，感谢！

**Comment by TheWindSing** [comment]
GitHub：
`windowsappruntimeinstall-x64.exe --force`下载安装SDK后出现了这个错误
![image](https://github.com/user-attachments/assets/8e899559-e30f-450d-900d-eb69c93d7064)
powershell安装卡在这个位置
![image](https://github.com/user-attachments/assets/e9945981-210f-4f91-b37f-fa938bb32440)
Microsoft Store：
![image](https://github.com/user-attachments/assets/5a6d8054-b06a-408f-87a2-8d8386f5400c)
```
版本	Windows 10 专业版
版本号	22H2
安装日期	‎29/‎10/‎2024
操作系统内部版本	19045.5131
体验	Windows Feature Experience Pack 1000.19060.1000.0
```


> 补充一下，商店的依赖可能没有同步更新到最新的 WinAppSDK，所以如果从商店下载有问题的同学可以尝试先手动安装最新的 1.6.2 SDK https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads ![image](https://private-user-images.githubusercontent.com/27713596/386919315-8112ec0b-0a64-49d7-98c7-564d4dc76443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTUyMDksIm5iZiI6MTczMTg1NDkwOSwicGF0aCI6Ii8yNzcxMzU5Ni8zODY5MTkzMTUtODExMmVjMGItMGE2NC00OWQ3LTk4YzctNTY0ZDRkYzc2NDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDE0NDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNTdhM2Y1Yjc2ODE4NTliNGE5NTkyMzlkNTdhYzU0N2QyM2I2MDYwMmIxMDQ1MmNjMWY1ODE1NzE2MGI2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g10-h4foGhtidUyukZ-_AOoaH9d58uuaJLPyv5U2tNs)

**Comment by ongiei** [comment]
什么几把杠精啊？你眼睛有问题还是脑子有问题？说了是商店无法安装，傻逼吧你？当爹当github了？

________________________________
发件人: Ziphyrien ***@***.***>
发送时间: 2024年11月17日 11:57
收件人: Richasy/Bili.Copilot ***@***.***>
抄送: ongiei ***@***.***>; Comment ***@***.***>
主题: Re: [Richasy/Bili.Copilot] [Bug] 软件无法安装 (Issue #900)


msix怎么可以直接双击安装，前置都没装，一群**，肯定是用脚本安装啊，怕是连安装教程都没看就直接下的吧

―

**Comment by Richasy** [comment]
现在更新了新的版本，应该可以正常下载安装了
