### ISSUE TITLE
[Bug] 历史记录无法显示

### ISSUE THREAD

**Issue by KuonjiEri** [Richasy/Bili.Copilot#903]
### Bug 描述

历史记录无法显示，打开是一片空白

### 复现问题的步骤

```plain text
1、打开哔哩助理
2、点击头像观看历史
3、一片空白
```

### 预期行为

历史记录正常显示

### 截图

![ad8362cc-4ee8-41c7-98cf-8f44961159f7](https://github.com/user-attachments/assets/4e5cda76-b0cf-432c-95d6-ff0fe35513c1)

### 应用来源

- [ ] Github
- [x] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
可以在设置里找到当天的日志，发上来我看下

**Comment by KuonjiEri** [comment]
[applog.2024-11-17.log](https://github.com/user-attachments/files/17789109/applog.2024-11-17.log)
发现问题了，是被adguard拦截了...
