### ISSUE TITLE
[Bug] 问题反馈

### ISSUE THREAD

**Issue by RainyGrass** [Richasy/Bili.Copilot#904]
### Bug 描述

目前遇到的问题是：
1. 首页推荐视频刷新后还是原来的推荐，要刷新几次后才会不一样。
2. 网络连接正常，但是搜索却一片空白，刷新也没有作用
![PixPin_2024-11-18_09-43-54](https://github.com/user-attachments/assets/f78313a9-9406-4f74-b927-1dd5114bcccf)

### 复现问题的步骤

```plain text
1. 开启应用程序
2. 首页推荐刷新，发现刷新后还是原来推荐
3. 搜索结果一片空白，刷新也毫无作用
```

### 预期行为

1. 每次刷新推荐的视频都能尽量不重复
2.  搜索不要再出问题了

### 截图

（上面已经交了截图了）

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 其它系统版本

没有

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
搜索的问题已经修了，在商店更新一下

**Comment by RainyGrass** [comment]
> 搜索的问题已经修了，在商店更新一下

您好，微软商店更新失败了怎么办？![image](https://github.com/user-attachments/assets/53142c69-9d06-484d-944d-f6cb1531d401)

**Comment by Richasy** [comment]
更新了新的版本，如果不出意外的话应该可以装
