### ISSUE TITLE
[Feature] 动态页面视频栏新增稍后再看按钮

### ISSUE THREAD

**Issue by MuLin4396** [Richasy/Bili.Copilot#906]
### 问题描述

希望和网页版一样能支持一键稍后再看!
![屏幕截图 2024-11-19 105606](https://github.com/user-attachments/assets/15161781-75d6-48ab-be78-4f617b1ac1a1)
![屏幕截图 2024-11-19 105714](https://github.com/user-attachments/assets/375188d9-781b-43bb-87a1-f4fe5abf9dd8)

### 描述解决方案

在框的右下角或者在评论的右边增加一个稍后再看按钮，按一下加入稍后再看，再按一下删除稍后再看

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
右键->添加到稍后再看

**Comment by MuLin4396** [comment]
希望有类似的独立开关
类似于这样的
![image](https://github.com/user-attachments/assets/c539c3d7-310b-4ed3-8367-fd5502d798f0)
（纯个人看法
