### ISSUE TITLE
[Bug] 新依赖也装了 商店还是无法更新 侧加载也不行 WIN10升到最新版了 就差重做系统了

### ISSUE THREAD

**Issue by WOJIAOSHIYI** [Richasy/Bili.Copilot#907]
### Bug 描述

无法更新 无法侧载

### 复现问题的步骤

```plain text
打开商店更新失败
侧加载无法安装
```

### 预期行为

软件正常更新

### 应用来源

- [X] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [X] 其它 (需注明)

### 其它系统版本

Win10 22H2 

### 运行设备

桌面/台式机

### 备注

大佬考虑做便携版吗？

### 人人为我，我为人人

None

**Comment by WOJIAOSHIYI** [comment]
侧载失败 Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CF9, 无法安装。请联系你的软件供应商。 (异常来自 HRESULT:0x80073CF9)

**Comment by Richasy** [comment]
之前的版本由于一些WinAppSDK框架的问题，导致win10无法安装，现在更新了新的版本，如果不出意外的话应该可以装

**Comment by WOJIAOSHIYI** [comment]
> 之前的版本由于一些WinAppSDK框架的问题，导致win10无法安装，现在更新了新的版本，如果不出意外的话应该可以装
新版毫无问题
