### ISSUE TITLE
[Bug] 微小bug报告“暂停时播放条遮挡视频底部’‘调整清晰度栏激活后点击视频取消会导致暂停“

### ISSUE THREAD

**Issue by offlineface** [Richasy/Bili.Copilot#909]
### Bug 描述

1. 播放条仅在播放时会自动隐藏，暂停时常显会遮挡视频内容；
2. 点击清晰度弹出清晰度选择窗口后，如果点击旁边视频取消会导致暂停，其他播放条上的功能按钮同理；
3. 弹幕移动卡顿、忽快忽慢
以上是体验到现在的bug

### 复现问题的步骤

```plain text
已在描述中体现
```

### 预期行为

1. 无论暂停还是播放，播放条都能自如地隐藏
2. 第一下点击旁边取消次级选择框，第二下才是视频暂停
3. 弹幕移动不卡顿，不变速。

### 截图

1
![image](https://github.com/user-attachments/assets/8547f34f-914a-47c5-b072-bc95dc84f88a)
2
![image](https://github.com/user-attachments/assets/e1cc1a2e-98b7-4837-8520-fe7d338e9151)
3
https://github.com/user-attachments/assets/d6c3bae6-2e66-4658-b0a1-46dda8a27284

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2024-11-19.log](https://github.com/user-attachments/files/17822940/applog.2024-11-19.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Ziphyrien** [comment]
Bug1确实很影响体验
