### ISSUE TITLE
1.25X

### ISSUE THREAD

**Issue by 536143095** [Richasy/Bili.Copilot#918]
### 问题描述

我需要1.25X的播放速率，但现在只有1X和1.5X
![1 5X](https://github.com/user-attachments/assets/5e6c3e48-8c11-4df9-a9a4-9d3770acaa25)

### 描述解决方案

滑动条无级变化

### 备选方案

增加1.25X播放速率

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
与 #919 合并
