### ISSUE TITLE
[Bug] 严重的播放逻辑错误

### ISSUE THREAD

**Issue by ljlofficial** [Richasy/Bili.Copilot#921]
### Bug 描述

在恶劣的网络环境下，点击播放视频时会出现只有视频流没有音频流的情况，加载半天才提示需要重载

### 复现问题的步骤

```plain text
在恶劣的网络环境下播放视频
```

### 预期行为

直接提示加载中，不要加载视频流

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [X] 其它 (需注明)

### 其它系统版本

Windows DEV 测试版本

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你预期的这种行为是原生播放器。

对于默认的岛（MPV）播放器，我必须先加载一个视频流，然后才能把音频流附加上去

**Comment by ljlofficial** [comment]
但是目前存在的问题是在网络不佳的情况下，只会有视频流传输但音频流传输无法完成的情况，请问能不能加判断处理一下，谢谢。
