### ISSUE TITLE
[Bug] AI总结bug，只显示一部分后就不显示了

### ISSUE THREAD

**Issue by zss2430922519** [Richasy/Bili.Copilot#923]
### Bug 描述

AI总结经常出bug，有时候能显示完，但也非常多时候显示不全，老版本也出现了这个问题，有同样出现这个问题的吗？

### 复现问题的步骤

```plain text
如题，总结内容显示不全
```

### 预期行为

修复它！谢谢

### 截图

![屏幕截图 2024-11-27 205911](https://github.com/user-attachments/assets/0d881821-4054-4d3f-8d88-9ec2da89af3e)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 备注

疑似是稍复杂一点的模型给出的稍复杂一点的内容就不显示，OpenAI 4o-mini可以完整显示，但OpenAI 4o和Open AI 4-all就不能显示完全

### 人人为我，我为人人

None

**Comment by zss2430922519** [comment]
顺带问下作者，如何查看软件日志，我看看是软件问题，还是模型问题，我看看模型是否有返回完全回答

**Comment by Richasy** [comment]
你可以尝试在设置/AI服务中调整自定义提示词。可能是视频内容比较长，超过了 AI 上下文限制。
BTW，如果日志里没有信息，说明这不是一个错误，也就是说在 APP 这边是完成了整个请求，导致输出不全的原因可能发生在服务端

**Comment by zss2430922519** [comment]
> 你可以尝试在设置/AI服务中调整自定义提示词。可能是视频内容比较长，超过了 AI 上下文限制。 BTW，如果日志里没有信息，说明这不是一个错误，也就是说在 APP 这边是完成了整个请求，导致输出不全的原因可能发生在服务端

好的谢谢，有空我再测试下
