### ISSUE TITLE
[Feature] 希望在UP更新时收到通知，和哔哩一样

### ISSUE THREAD

**Issue by whwdzg** [Richasy/Bili.Copilot#93]
### 问题描述

希望在UP更新时收到通知，和哔哩一样

### 描述解决方案

在UP更新时收到通知，和哔哩一样

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
目前 WinAppSDK 在处理 background task 时还有一些 bug，我可能需要更多的时间来研究这个问题
