### ISSUE TITLE
[Bug] 搜索功能似乎有bug

### ISSUE THREAD

**Issue by LazyCuteLion** [Richasy/Bili.Copilot#934]
### Bug 描述

搜索功能无数据，但是调整一下排序，就会有了。
![image](https://github.com/user-attachments/assets/440d133f-2510-4b18-8f52-5beece279251)
![image](https://github.com/user-attachments/assets/43780ed8-3a80-455d-a118-93af886ac61d)

### 复现问题的步骤

```plain text
1、打开应用
2、顶部搜索框输入任意内容
3、回车
```

### 预期行为

能正常搜索到内容

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
看最新发行的说明

**Comment by Richasy** [comment]
与 #931 合并
