### ISSUE TITLE
[Bug] Windows11触摸模式下，启动时自动最大化存在bug

### ISSUE THREAD

**Issue by Waximell** [Richasy/Bili.Copilot#936]
### Bug 描述

Windows11的触摸模式在开启软件时会默认最大化窗口，但此时bili助理会卡在它以为自己最大化了，实际没有的状态（即边缘无圆角，实际不填满屏幕）（如图）

### 复现问题的步骤

```plain text
在触摸模式下打开软件，100%复现，取消最大化后再次最大化恢复正常。
```

### 预期行为

启动时正常最大化

### 截图

![屏幕截图 2024-12-06 095258](https://github.com/user-attachments/assets/c9f66949-b265-42fe-91ac-255bfb5b2291)

### 应用来源

- [ ] Github
- [X] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [ ] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

ARM64 设备

### 备注

关于切换为触摸模式，我在我的Win平板上（arm64设备）是修改注册表：
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\PriorityControl]
"ConvertibleSlateMode"=dword:00000000
可能同时需要触摸屏存在才可切换，此注册表项在我的笔记本上无效，无法测试此bug在x86设备上是否复现

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
我无法在正常的触屏设备（ARM64）上复现这个问题

**Comment by Starfallan** [comment]
Surface Pro7 在
系统版本：Win24H2 26100.2454 
应用版本：2.2411.2.0
正常打开应用正常可以自动全屏显示，无法复现该问题。

且在默认设置下，注册表对应项目默认为0。即断开外接键盘系统默认为平板模式，连接键盘后，该注册表项自动修改为1。

**Comment by Waximell** [comment]
那可能是我自己设备的问题？虽然问题确实存在，但，反正影响也不大，那就这样吧

**Comment by Waximell** [comment]
那可能是我自己设备的问题？虽然问题确实存在，但，反正影响也不大，那就这样吧
