### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by martinezyh2077** [Richasy/Bili.Copilot#944]
### Bug 描述

视频无法播放视频无法播放

### 复现问题的步骤

```plain text
打开视频就无法播放
```

### 预期行为

正常播放

### 截图

![屏幕截图 2024-12-08 222102](https://github.com/user-attachments/assets/824ea9d6-6046-437e-b188-1f20a601367c)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2024-12-08.log](https://github.com/user-attachments/files/18052600/applog.2024-12-08.log)

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
看上去岛播放器在你的设备上不能正常初始化，那建议你还是在设置/播放行为里把播放器类型调整为原生或者网页吧
