### ISSUE TITLE
[Bug]收藏页面无了

### ISSUE THREAD

**Issue by nerononero** [Richasy/Bili.Copilot#951]
### Bug 描述

![image](https://github.com/user-attachments/assets/21476049-b72a-42f4-b925-abe66f19ae47)
收藏页面无了

### 复现问题的步骤

```plain text
1.打开应用
2.点开头像
3.点我的收藏
4.出现问题
```

### 预期行为

修复一下收藏页面

### 截图

![image](https://github.com/user-attachments/assets/21476049-b72a-42f4-b925-abe66f19ae47)

### 应用来源

- [X] Github
- [ ] 微软商店（Microsoft Store）
- [ ] 其它

### 系统版本

- [X] Windows 10 (Build 19041 - 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩助理中

**Comment by Richasy** [comment]
把广告屏蔽软件关了，或者去除对 grpc.biliapi.net 的屏蔽
