### ISSUE TITLE
[Feature] 非常创新但有待打磨的UI，现阶段界面交互体验却糟透了

### ISSUE THREAD

**Issue by TobyLi223** [Richasy/Bili.Copilot#97]
### 问题描述

只有首页才有搜索栏
需要加载较长时间的每一页
图块太大导致同屏信息量太少
常用但是相对小的按钮
底栏按钮辨识度低，且无法自定义
刷新按钮不够显眼且点击面积小
键盘更多常用操作不支持
希望添加选项关闭热搜这一有政治宣传意味的界面

### 描述解决方案

既然想做成手机的感觉，那就参考下安卓旧版客户端和您上一个uwp的操作逻辑，适当加入键盘按钮操作。
不要把我的收藏，稍后再看，历史记录放在离核心操作区太远的位置，最好也不要藏在二级菜单里

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
感谢你的建议，你说的有道理，从桌面应用设计的角度，我不否认哔哩 UWP 的设计观感要更讨喜。

不过就目前我对于哔哩助理的定位来说，它应该是一个简单的工具类应用。

哔哩助理并未考虑做成所谓 `手机` 的感觉，这个在桌面应用开发中是不合时宜的。之所以限制窗口大小和 UI 布局，是为了
1. 降低信息密度
2. 降低用户在应用上花费的时间，避免无意义地刷刷刷
3. 规范各个功能模块的层级
4. 为了以后的工具集计划

所以，当下哔哩助理不是一个为了留住用户而设计的应用，当前我不会对UI界面进行大的调整
